### PR TITLE
Enable prodsig read for jtag3 programmers

### PR DESCRIPTION
**Pull request by stefanrueger**
@MCUdude @mcuee Please test.

This concludes my review of prodsig read. Some programmers won't be able to, eg, `flip1` and `flip2` but it looks like they cannot even read calibration.

### CODE REVIEW

**Comment by MCUdude** [comment]
Doesn't work, sorry.

I tried reading the ATmega324PB `prodsig` using a Power Debugger in JTAG and ISP mode, and the ATmega328PB `prodsig` using an Xplained Mini in ISP mode:

```
$ ./avrdude -cpowerdebugger_jtag -patmega324pb -Uprodsig:r:-:h
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9517 (probably m324pb)

avrdude: processing -U prodsig:r:-:h
avrdude: reading prodsig/sigrow memory ...
avrdude error: unable to read byte at address 0x0006
avrdude error: read operation not supported for memory prodsig
avrdude error: unable to read all of prodsig/sigrow memory, rc=-2

avrdude done.  Thank you.

$ ./avrdude -cpowerdebugger_isp -patmega324pb -Uprodsig:r:-:h
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9517 (probably m324pb)

avrdude: processing -U prodsig:r:-:h
avrdude: reading prodsig/sigrow memory ...
avrdude error: unknown command
avrdude error: timeout/error communicating with programmer
avrdude error: unable to read byte at address 0x0000
avrdude error: read operation not supported for memory prodsig
avrdude error: unable to read all of prodsig/sigrow memory, rc=-2

avrdude done.  Thank you.

$ ./avrdude -cxplainedmini_isp -patmega328pb -Uprodsig:r:-:h
avrdude error: command failed
avrdude warning: target prepared for ISP, signed off
        now retrying without power-cycling the target
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9516 (probably m328pb)

avrdude: processing -U prodsig:r:-:h
avrdude: reading prodsig/sigrow memory ...
avrdude error: unknown command
avrdude error: timeout/error communicating with programmer
avrdude error: unable to read byte at address 0x0000
avrdude error: read operation not supported for memory prodsig
avrdude error: unable to read all of prodsig/sigrow memory, rc=-2

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
Thanks! So bytes 1-5 *can* be read using `powerdebugger_jtag`, ie,
```
$ avrdude -cpowerdebugger_jtag -patmega324pb -qqT "read prodsig 0 5" && echo OK
```
is fine? My technique might be given short shrift by an overzealous firmware! This will need support from someone knowing the JTAGICE3 firmware.

I hope `-c powerdebugger_isp` and `-c xplainedmini_isp` will both work using PR #1520 for STK500v2 based programmers

**Comment by MCUdude** [comment]
It seems like it can read part of the prodsig memory, yes:

```
$ ./avrdude -cpowerdebugger_jtag -patmega324pb -qqT "read prodsig 0 5" && echo OK
0000  1e 83 95 1e 17                                    |.....           |
OK
```

@xedbg is probably the right person to ask. He knows way more about the EDBG protocol than I do.

**Comment by xedbg** [comment]
Its been a while... @MCUdude what you see there looks like the "signature/device ID" to me:  1e9517 (in middle-ish-endian?)
One thing that I seem to remember is that these calibration bytes may have been routed into the "OSCCAL" memtype - on the older parts - if you can give a debug output that shows the read() packet, i can trace it through from there.

**Comment by stefanrueger** [comment]
OK, I won't merge this PR. Yes, best to wait for a hot tip from @xedbg re how to read sigrow for the classic `m324pb` and `m328pb`. I have scanned [the EDGB documentation](https://ww1.microchip.com/downloads/en/DeviceDoc/50002630A.pdf) but pages 79ff don't look hopeful. 

Out of interest: have you tried this with git main? Maybe has this worked all along? I don't hold my breath, though. I think `prodsig` read should, at least for PDI and UPDI parts and we may simply be out of luck for classic parts with the EDBG specification (page 80 suggests only bytes 0-5 and 7 can be read using the technique of this PR). 

I suggest merging all other PRs, *including* the untested code for `jtagmkI`, too, as it should do no harm, even though we don't know whether it works.

**Comment by stefanrueger** [comment]
@xedbg: only two classic parts (m324pb and 328pb) document `sigrow`, an 24 byte extended signature-interleaved-with-calibration field. These *can* be read with ISP calls (12 bytes signature and 12 bytes calibration) and then interleaving them for the `sigrow` memory. They also *can* be read by direct JTAG calls, see PR #1521, but using `-c powerdebugger_jtag` via the EDBG protocol runs into firmware limitations that the protocol only returns max 3 bytes from the signature memory and max 4 bytes from the calibration memory. See page 80 of  [this EDGB documentation](https://ww1.microchip.com/downloads/en/DeviceDoc/50002630A.pdf). Any trick to elicit the full sigrow memory falling short of rewriting the firmware?

(Note AVRDUDE used to call this `prodsig` memory and `sigrow` is an alias for this).

**Comment by MCUdude** [comment]
> if you can give a debug output that shows the read() packet, i can trace it through from there.

sure!

<details>
<summary>verbose prodsig output (-Uprodsig:r:-:h -vvvv)</summary>

```
$ ./avrdude -cpowerdebugger_jtag -patmega324pb -Uprodsig:r:-:h -vvvv

avrdude: Version 7.2-20230720
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is /Users/hans/Downloads/avrdude-terminal/src/avrdude.conf
         User configuration file is /Users/hans/.avrduderc

         Using Port                    : usb
         Using Programmer              : powerdebugger_jtag
avrdude: jtag3_open()
avrdude: usbhid_open(): probing for max packet size
avrdude: usbhid_open(): setting max_xfer from DAP_Info response to 512
avrdude: found CMSIS-DAP compliant device, using EDBG protocol
avrdude: jtag3_getsync()

avrdude: jtag3_edbg_prepare()
avrdude: jtag3_edbg_prepare(): connection status 0x01
avrdude: sending sign-on command: 
avrdude: jtag3_edbg_send(): sending 3 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 0 (command_sequence == 0)

Raw message:
01  80  00  
[general] OK
         AVR Part                      : ATmega324PB
         Chip Erase delay              : 55000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : possible i/o
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom                 65    10     4    0 no       1024    4      0  9000  9000 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           flash                  65    10   128    0 yes     32768  128    256  4500  4500 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           lfuse                   0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           hfuse                   0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           efuse                   0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           lock                    0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           io                      0     0     0    0 no        224    1      0     0     0 0x00 0x00
                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           prodsig     sigrow      0     0     0    0 no         24    1      0     0     0 0x00 0x00

         Programmer Type : JTAGICE3
         Description     : Atmel PowerDebugger (ARM/AVR) in JTAG mode
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 0, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 1 (command_sequence == 1)

Raw message:
01  84  01  01  01  3d  b8  00  00  
[general] Data returned:
0x01 0x01 0x01 0x3d 0xb8 0x00 0x00 
         ICE HW version  : 1
         ICE FW version  : 1.61 (rel. 184)
         Serial number   : J51800002930
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 0, parm 1) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 2 (command_sequence == 2)

Raw message:
01  84  01  01  3d  00  
[general] Data returned:
0x01 0x01 0x3d 0x00 
avrdude: jtag3_setparm()
avrdude: sending set parameter (scope 0x12, section 0, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 7 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 3 (command_sequence == 3)

Raw message:
12  80  00  
[AVR] OK
avrdude: jtag3_setparm()
avrdude: sending set parameter (scope 0x12, section 0, parm 1) command: 
avrdude: jtag3_edbg_send(): sending 7 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 4 (command_sequence == 4)

Raw message:
12  80  00  
[AVR] OK
avrdude: jtag3_setparm()
avrdude: sending set parameter (scope 0x12, section 1, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 7 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 5 (command_sequence == 5)

Raw message:
12  80  00  
[AVR] OK
avrdude: jtag3_initialize(): trying to set JTAG daisy-chain info to 0,0,0,0
avrdude: jtag3_setparm()
avrdude: sending set parameter (scope 0x12, section 1, parm 1) command: 
avrdude: jtag3_edbg_send(): sending 10 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 6 (command_sequence == 6)

Raw message:
12  80  00  
[AVR] OK
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 7 (command_sequence == 7)

Raw message:
01  84  01  da  13  00  
[general] Data returned:
0x01 0xda 0x13 0x00 
         Vtarget         : 5.08 V
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x12, section 1, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 8 (command_sequence == 8)

Raw message:
12  84  00  04  00  
[AVR] Data returned:
0x00 0x04 0x00 
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x12, section 0, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 9 (command_sequence == 9)

Raw message:
12  84  00  02  00  
[AVR] Data returned:
0x00 0x02 0x00 
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x12, section 1, parm 32) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 10 (command_sequence == 10)

Raw message:
12  84  00  fa  00  00  
[AVR] Data returned:
0x00 0xfa 0x00 0x00 
         JTAG clk prog.  : 250 kHz
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x12, section 1, parm 33) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 11 (command_sequence == 11)

Raw message:
12  84  00  c8  00  00  
[AVR] Data returned:
0x00 0xc8 0x00 0x00 
         JTAG clk debug  : 200 kHz
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 32) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 12 (command_sequence == 12)

Raw message:
01  84  01  00  00  00  
[general] Data returned:
0x01 0x00 0x00 0x00 
         Vout set        : 0.00 V
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 20) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 13 (command_sequence == 13)

Raw message:
01  84  01  3e  d9  00  
[general] Data returned:
0x01 0x3e 0xd9 0x00 
         Vout measured   : 1.48 V
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 17) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 14 (command_sequence == 14)

Raw message:
01  84  01  2e  da  00  
[general] Data returned:
0x01 0x2e 0xda 0x00 
         Ch A voltage    : 1.470 V
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 16) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 15 (command_sequence == 15)

Raw message:
01  84  01  90  fe  d9  00  
[general] Data returned:
0x01 0x90 0xfe 0xd9 0x00 
         Ch A current    : -1.024 mA
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 19) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 16 (command_sequence == 16)

Raw message:
01  84  01  1e  cf  00  
[general] Data returned:
0x01 0x1e 0xcf 0x00 
         Ch B voltage    : 1.525 V
avrdude: jtag3_getparm()
avrdude: sending get parameter (scope 0x01, section 1, parm 18) command: 
avrdude: jtag3_edbg_send(): sending 6 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 17 (command_sequence == 17)

Raw message:
01  84  01  00  00  1e  cf  00  
[general] Data returned:
0x01 0x00 0x00 0x1e 0xcf 0x00 
         Ch B current    : 0.000 mA

avrdude: jtag3_setparm()
avrdude: sending set parameter (scope 0x12, section 2, parm 0) command: 
avrdude: jtag3_edbg_send(): sending 37 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 18 (command_sequence == 18)

Raw message:
12  80  00  
[AVR] OK
avrdude: sending AVR sign-on command: 
avrdude: jtag3_edbg_send(): sending 4 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 19 (command_sequence == 19)

Raw message:
12  84  00  3f  70  51  99  00  
[AVR] Data returned:
0x00 0x3f 0x70 0x51 0x99 0x00 
avrdude: JTAG ID returned: 0x3f 0x70 0x51 0x99
avrdude: AVR device initialized and ready to accept instructions
Reading |                                                    | 0% 0.00 s 
avrdude: jtag3_read_byte(.., signature, 0x0, ...)
avrdude: sending enter progmode command: 
avrdude: jtag3_edbg_send(): sending 3 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 20 (command_sequence == 20)

Raw message:
12  80  00  
[AVR] OK
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 21 (command_sequence == 21)

Raw message:
12  84  00  1e  95  17  00  
[AVR] Data returned:
0x00 0x1e 0x95 0x17 0x00 
avrdude: jtag3_read_byte(.., signature, 0x1, ...)
Reading | #################                                  | 33% 0.07 s 
avrdude: jtag3_read_byte(.., signature, 0x2, ...)
Reading | ################################################## | 100% 0.07 s 
avrdude: device signature = 0x1e9517 (probably m324pb)

avrdude: processing -U prodsig:r:-:h
avrdude: reading prodsig/sigrow memory ...
Reading |                                                    | 0% 0.00 s 
avrdude: jtag3_read_byte(.., prodsig, 0x0, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 22 (command_sequence == 22)

Raw message:
12  84  00  1e  00  
[AVR] Data returned:
0x00 0x1e 0x00 
avrdude: jtag3_read_byte(.., prodsig, 0x1, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 23 (command_sequence == 23)

Raw message:
12  84  00  83  00  
[AVR] Data returned:
0x00 0x83 0x00 
Reading | ##                                                 | 4% 0.00 s 
avrdude: jtag3_read_byte(.., prodsig, 0x2, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 24 (command_sequence == 24)

Raw message:
12  84  00  95  00  
[AVR] Data returned:
0x00 0x95 0x00 
Reading | ####                                               | 8% 0.00 s 
avrdude: jtag3_read_byte(.., prodsig, 0x3, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 25 (command_sequence == 25)

Raw message:
12  84  00  1e  00  
[AVR] Data returned:
0x00 0x1e 0x00 
Reading | ######                                             | 12% 0.01 s 
avrdude: jtag3_read_byte(.., prodsig, 0x4, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 26 (command_sequence == 26)

Raw message:
12  84  00  17  00  
[AVR] Data returned:
0x00 0x17 0x00 
Reading | ########                                           | 16% 0.01 s 
avrdude: jtag3_read_byte(.., prodsig, 0x5, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 27 (command_sequence == 27)

Raw message:
12  84  00  01  00  
[AVR] Data returned:
0x00 0x01 0x00 
Reading | ##########                                         | 20% 0.01 s 
avrdude: jtag3_read_byte(.., prodsig, 0x6, ...)
avrdude: sending read memory command: 
avrdude: jtag3_edbg_send(): sending 12 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 28 (command_sequence == 28)

Raw message:
12  a0  00  36  
[AVR] FAILED, reason: 0x36
avrdude: bad response to read memory command: 0xa0
Reading | ##########---------------------------------------- | 20% 0.01 s 
avrdude avr_read_mem() [avr.c:454] error: unable to read byte at address 0x0006
avrdude avr_read_mem() [avr.c:456] error: read operation not supported for memory prodsig
avrdude do_op() [update.c:426] error: unable to read all of prodsig/sigrow memory, rc=-2
avrdude: sending leave progmode command: 
avrdude: jtag3_edbg_send(): sending 3 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 29 (command_sequence == 29)

Raw message:
12  80  00  
[AVR] OK
avrdude: jtag3_close()
avrdude: sending AVR sign-off command: 
avrdude: jtag3_edbg_send(): sending 3 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 30 (command_sequence == 30)

Raw message:
12  80  00  
[AVR] OK
avrdude: sending sign-off command: 
avrdude: jtag3_edbg_send(): sending 4 bytes
avrdude: jtag3_edbg_recv():
avrdude: jtag3_recv(): Got message seqno 31 (command_sequence == 31)

Raw message:
01  80  00  
[general] OK

avrdude: jtag3_edbg_signoff()

avrdude done.  Thank you.
```

</details>

<details>
<summary>Even more verbose prodsig output (-Uprodsig:r:-:h -vvvvv)</summary>

[Pasted at gist.github.com, as the Outputis too long to fit within the 65536 character limit)](https://gist.github.com/MCUdude/aef1924e4a44246bb995e124ca4e9157)

</details>

> Out of interest: have you tried this with git main? Maybe has this worked all along?

Doesn't work with git main:
```
$ ./avrdude -cpowerdebugger_jtag -patmega324pb -qqT "read prodsig" && echo OK
avrdude error: (read) error reading prodsig address 0x00000 of part ATmega324PB
               read operation not supported on memory type prodsig
```

**Comment by xedbg** [comment]
Ah, thanks @stefanrueger - I had no idea these limitations were in place :/ 
It looks like they are a hard blocker in firmware, I'm afraid.  We could change this, but that would have to wait for the next release opportunity, and right now we don't have one scheduled yet.

**Comment by stefanrueger** [comment]
OK, in absence of other odeas if it's a FW limitation we could merge this PR, so that if that limitation were to be removed this could work straight away (even though it looks like the limitation will not be changed).

**Pull request merged**
