### PR TITLE
doc: Stop building and installing .ps and .dvi

### PR DESCRIPTION
**Pull request by ndim**
Building info, pdf, and HTML is enough.

ps and dvi are not needed any more.

### CODE REVIEW

**Comment by mcuee** [comment]
The change seems to be good based on the github action runs.

**Comment by stefanrueger** [comment]
Not merging now as earmarked as draft

**Comment by ndim** [comment]
Could not change it from draft to non-draft from the GitHub Android client, had to wait to get back to a proper computer.

**Comment by stefanrueger** [comment]
@ndim Thanks, will merge next round.

**Pull request merged**
