### PR TITLE
Fix Issue #474 FT232H support for ATmega2560 et al (load extended address)

### PR DESCRIPTION
**Pull request by stefanrueger**
Untested fix for Issue #474 

@mcuee might want to test this.

### CODE REVIEW

**Comment by mcuee** [comment]
Works perfectly.

```
C:\work\avr\avrdude_test\avrdude-7.0_bin64> .\avrdude_sr474v1.exe -c jtagkey -patmega2560 -D -U flash:w:.\hex\entest_offset_0x21000.hex:i

avrdude_sr474v1.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude_sr474v1.exe: Device signature = 0x1e9801 (probably m2560)
avrdude_sr474v1.exe: reading input file ".\hex\entest_offset_0x21000.hex"
avrdude_sr474v1.exe: writing flash (135680 bytes):

Writing | ################################################## | 100% 0.00s

avrdude_sr474v1.exe: 135680 bytes of flash written
avrdude_sr474v1.exe: verifying flash memory against .\hex\entest_offset_0x21000.hex:

Reading | ################################################## | 100% 0.00s

avrdude_sr474v1.exe: 135680 bytes of flash verified

avrdude_sr474v1.exe done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude-7.0_bin64> .\avrdude_sr474v1.exe -c jtagkey -patmega2560 -D -U flash:v:.\hex\entest_offset_0x21000.hex:i

avrdude_sr474v1.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude_sr474v1.exe: Device signature = 0x1e9801 (probably m2560)
avrdude_sr474v1.exe: verifying flash memory against .\hex\entest_offset_0x21000.hex:

Reading | ################################################## | 100% 0.00s

avrdude_sr474v1.exe: 135680 bytes of flash verified

avrdude_sr474v1.exe done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude-7.0_bin64> .\avrdude_sr474v1.exe -c usbasp -patmega2560 -D -U flash:v:.\hex\entest_offset_0x21000.hex:i

avrdude_sr474v1.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude_sr474v1.exe: Device signature = 0x1e9801 (probably m2560)
avrdude_sr474v1.exe: verifying flash memory against .\hex\entest_offset_0x21000.hex:

Reading | ################################################## | 100% 0.00s

avrdude_sr474v1.exe: 135680 bytes of flash verified

avrdude_sr474v1.exe done.  Thank you.
```

**Comment by stefanrueger** [comment]
I mistakenly overclaimed in the commit message. Apologies, I don't know how to change that.

@mcuee Great, thanks for testing!
@mariusgreuel Would be amazing if you could review the code (only 22 lines)

This could help @dl8dtl decide on whether or not to merge.

@mcuee BTW, I have created a *dedicated small and working* [blink-mega2560+lext-test.hex](https://github.com/avrdudes/avrdude/files/8943338/blink-mega2560%2Blext-test.txt) for this problem with *some different* bytes in every 64k section:
```
$ avrdude -qqp m2560 -c ... -U flash:w:blink-mega2560+lext-test.hex:i && echo OK
OK
```

This way you only see the problems (and not much output when all is good). You might want to convince ourself that defective
programmers trigger errors and good ones not.

The .hex file is designed to trigger verification errors with programmers that don't support flash > 128k. I created it with
```
$ yes "Bonjour le monde" | head -10 | srec_cat - -raw -offset 0x11234 -o - -intel >/tmp/1
$ yes "Hello, world"     | head -10 | srec_cat - -raw -offset 0x21234 -o - -intel >/tmp/2
$ yes "Hei Verden"       | head -10 | srec_cat - -raw -offset 0x31234 -o - -intel >/tmp/3
$ srec_cat blink.hex -intel /tmp/1 -intel /tmp/2 -intel /tmp/3 -intel -o - -intel >blink-mega2560+lext-test.hex
$ rm /tmp/1 /tmp/2 /tmp/3
```

**Review by mariusgreuel — APPROVED** [review]
I have not tried it myself, but it looks correct to me, especially the code that checks for a change in the upper bits. Thanks for the fix!

**Comment by stefanrueger** [comment]
Awesome, @mcuee @mariusgreuel many thanks.

 @dl8dtl. I think this is ready for merging.

**Review by dl8dtl — APPROVED** [review]

**Comment by stefanrueger** [comment]
Many thanks to @mcuee for testing and to @mariusgreuel and @dl8dtl for reviewing/comments. Will read up on git, so next time there'll defo be fewer commits than lines changed ;)

**Pull request merged**
