### PR TITLE
Adds configuration for Kanda's AVRISP-U programmer.

### PR DESCRIPTION
**Pull request by KantBe**
At EPFL, as part of the _Microcontrollers and digital systems_ course ([EE-208](https://edu.epfl.ch/coursebook/en/microcontrollers-and-digital-systems-EE-208)), we are using Kanda's AVRISP-U programmer for a project. Unfortunately, this programmer is only supported by their in-house proprietary software.

This commit aims to add support for the AVRISP-U programmer in avrdude.
Credits to Kanda for the [initial configuration](https://www.kanda.com/blog/microcontrollers/avr-microcontrollers/avrdude-kanda-avrisp/). _Although we had to update the configuration by ourselves..._
Thanks to @danielpanero for the initial guidance.

### CODE REVIEW

**Comment by mcuee** [comment]
Looks good to me.

**Comment by stefanrueger** [comment]
@KantBe But yes, as @mcuee said, it looks good otherwise. Thanks for contribution.

**Comment by KantBe** [comment]
@stefanrueger Thanks for the feedback !
I thought I got the formatting right but it looks like I missed a whitespace...

I updated the PR with the output of `avrdude -cavrisp-u/s`.

**Comment by KantBe** [comment]
Today, I tested the configuration on 3 more avrisp-u programmers at my school.
It worked on 2 of them. On the last one, the PID was 6001 instead of 6010.

How should I update the PR to take this into account ?
Add a new configuration "avrisp-u-2", have it inherit "avrisp-u" and change the PID configuration ?

What I struggle with is the naming. There are no differences between the programmers beside the USB PID...
So maybe call them avrisp-u-6001 and avrisp-u-6010 ?

**Comment by MCUdude** [comment]
Have a look at how multiple USB PIDs use used with the PICkit4. I think it's possible to do the same for the Kanda programmer

https://github.com/avrdudes/avrdude/blob/07bda5e9139b9ec8dc43787dfddaef3d9bd58052/src/avrdude.conf.in#L2454-L2467

**Comment by KantBe** [comment]
@MCUdude It does not unfortunately :(
`avrdude: Warning: using PID 0x6010, ignoring remaining PIDs in list`

**Comment by MCUdude** [comment]
0x6001 indicates that the chip is an FT245 rather than an FT2232. Are you sure you can use this PR with the 0x6001 programmer just by changing the USB PID?

https://github.com/avrdudes/avrdude/blob/07bda5e9139b9ec8dc43787dfddaef3d9bd58052/src/usbdevs.h#L49-L51

**Comment by KantBe** [comment]
@MCUdude Absolutely. I flashed an Atmega128 with it. 
This is @danielpanero's programmer by the way. He had trouble with my initial configuration and showed me that his programmer was detected as 0x6001 instead. Today I tried using it with my computer and just had to change the PID in the configuration to make it work.

By the way, 0x6001 was the PID used in the [initial Kanda configuration](https://www.kanda.com/blog/microcontrollers/avr-microcontrollers/avrdude-kanda-avrisp/).

**Comment by mcuee** [comment]
@KantBe 

0x6001 should not be used for FT2232D/FT2232H. It is for FT232/FT245 series. 

If Kanda is really using 0x60001 for FT2232D then it is abusing the PID in this case. It has absolute no reason to do that.

**Comment by mcuee** [comment]
@KantBe 

By the way, FT232R and FT245R are supported with another programmer type `ftdi_syncbb`.
```
#------------------------------------------------------------
# ft245r
#------------------------------------------------------------

programmer
    id                     = "ft245r";
    desc                   = "FT245R based generic programmer";
    type                   = "ftdi_syncbb";
    prog_modes             = PM_TPI | PM_ISP;
    connection_type        = usb;
    reset                  = 4; # D4
    sck                    = 0; # D0
    sdo                    = 2; # D2
    sdi                    = 1; # D1
;

#------------------------------------------------------------
# ft232r
#------------------------------------------------------------

programmer
    id                     = "ft232r";
    desc                   = "FT232R based generic programmer";
    type                   = "ftdi_syncbb";
    prog_modes             = PM_TPI | PM_ISP;
    connection_type        = usb;
    reset                  = 4;  # DTR
    sck                    = 0;  # TxD
    sdo                    = 2;  # RTS
    sdi                    = 1;  # RxD
;

```

**Comment by KantBe** [comment]
Fine by me !

I tried using `ftdi_syncbb` to be sure but it definitely does not work. I guess at some point Kanda abused PID as you said, which would not surprise me given the configuration they provided on their blog...

**Comment by stefanrueger** [comment]
Unless I hear otherwise, I am looking to merge this PR as is at next opp.

**Pull request merged**
