### PR TITLE
Make USB product string available

### PR DESCRIPTION
**Pull request by MCUdude**
I figured it would be nice to have the actual USB string available so we could print it using `pgm->display`. Especially now that PR #1863 supports multiple different programmers using `-c pickit5`.

@stefanrueger I know we generally shouldn't touch the existing code formatting, but the usb_libusb.c formatting was _completely broken_, to a point where no text editor tabs/spaces setting could make the code acceptable. Indents were everywhere, and things were just a mess. I took the liberty to re-format the file as a separate commit.

### CODE REVIEW

**Comment by MCUdude** [comment]
Damnit! That merge conflict is there because I somehow forgot to update my dev branch before creating this PR. I'll open a new PR when I've figured it out...

**Comment by dl8dtl** [comment]
> but the usb_libusb.c formatting was _completely broken_

It was using hard TABs each 8 columns (yet 2-column indentation levels) – something that once used to be *the* standard, back when terminals defaulted to 8-column TABs.

Here's how my Emacs displays it (with the hard TABs dimmed a bit, to show where they are).
screenshot-2024-08-11T231729

**Comment by stefanrueger** [comment]
Yes, the trouble is no-one knows (or indeed can know) which file expects tab to be expanded to how many spaces. 8 used to be the default, but then people told their editors to use 4 spaces (or even 2).

My suggestion is to have a single PR before the release that re-formats the source to have two-space indentation. And no tabs. 

There are disadvantages to that. Weighing up the advantages my scales tip in favour of re-formatting.

**Comment by MCUdude** [comment]
> It was using hard TABs each 8 columns

8 "spaces" per tab made the code readable. However, there are lots of spaces there as well. Why place the curly braces on the next line _with_ two additional spaces as well?

``` c
  for (bus = usb_get_busses(); bus; bus = bus->next)
    {
      for (dev = bus->devices; dev; dev = dev->next)
	{
	  if (dev->descriptor.idVendor == pinfo.usbinfo.vid &&
	      dev->descriptor.idProduct == pinfo.usbinfo.pid)
	    {
	      udev = usb_open(dev);
	      if (udev)
		{
```

> My suggestion is to have a single PR before the release that re-formats the source to have two-space indentation. And no tabs.

I'm all for this! A file with _just_ tabs is OK, I think. It's when they are mixed it becomes a problem.

**Pull request closed without merging**
