### PR TITLE
Add CH343 USB to serial adapter

### PR DESCRIPTION
**Pull request by MCUdude**
The CH343 is WCH's latest generation of USB to serial chips and should work with "standard" USB drivers.

Chip details:
[https://github.com/avrdudes/avrdude/discussions/1639#discussioncomment-8252816](https://github.com/avrdudes/avrdude/discussions/1639#discussioncomment-8252816)
https://www.cnx-software.com/2022/04/19/wch-ch343-usb-to-serial-chips-support-1-8v-to-5v-io-voltage-6-mbps-baud-rate-custom-vid-pi
https://www.lcsc.com/search?q=ch343

Can you give this a try @cederom. You need to build with libserialport installed, and test with `-P ch343`.

### CODE REVIEW

**Comment by cederom** [comment]
Hmm I also have created the configuration in the meantime:

```
#------------------------------------------------------------
 # ch343
 #------------------------------------------------------------
 # CH343G chip https://www.wch-ic.com/downloads/CH343DS1_PDF.html

serialadapter # ch343
    id                     = "ch343";
    desc                   = "WCH CH343 USB to serial adapter";
    usbvid                 = 0x1a86;
    usbpid                 = 0x55d3;
;
```

Updated the `avrdude.conf` in the build directory and it fails to find the programmer. Any hints welcome :-)

```
% uname -a
FreeBSD XXX 13.2-RELEASE-p8 FreeBSD 13.2-RELEASE-p8 GENERIC amd64

% usbconfig -d 0.7 dump_device_desc
ugen0.7: <vendor 0x1a86 USB Single Serial> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (134mA)

  bLength = 0x0012
  bDescriptorType = 0x0001
  bcdUSB = 0x0110
  bDeviceClass = 0x0002  <Communication device>
  bDeviceSubClass = 0x0000
  bDeviceProtocol = 0x0000
  bMaxPacketSize0 = 0x0008
  idVendor = 0x1a86
  idProduct = 0x55d3
  bcdDevice = 0x0443
  iManufacturer = 0x0000  <no string>
  iProduct = 0x0002  <USB Single Serial>
  iSerialNumber = 0x0003  <5434023603>
  bNumConfigurations = 0x0001

% ./avrdude -c ch343
avrdude error: cannot find programmer id ch343
similar programmer name:
  ch341a = ch341a programmer (AVR must have minimum F_CPU of 6.8 MHz)
use -c? to see all possible programmers

% ./avrdude -c ch343:5434023603
avrdude error: cannot find programmer id ch343:5434023603
use -c? to see all possible programmers
```

**Comment by MCUdude** [comment]
@cederom Sorry, It's a bit too early for me. What I meant was  `-P`, so `-P ch343` instead of the serial port name/path

**Comment by cederom** [comment]
> @cederom Sorry, It's a bit too early for me. What I meant was `-P`, so `-P ch343` instead of the serial port name/path

No worries @MCUdude its 8AM and you probably did not sleep yet or are already running since 4AM just like me :-) :-)

```
% ./avrdude -P ch343
avrdude error: no programmer has been specified on the command line or in the
        config file(s); specify one using the -c option and try again
```

It seems CD340 and CH343 are serial adapters only not programmers. I have ordered CH341 board it will arrive next friday so I will be able to test. Can I test anything more at this point? :-)

ps/2: Please add datasheet reference to the configuration too (see my example above) :-)

**Comment by MCUdude** [comment]
> No worries @MCUdude its 8AM and you probably did not sleep yet or are already running since 4AM just like me :-) :-)

My 4-year-old daughter woke me up at 06:00, which is way earlier than what I'm used to. And Norway is also so dark in the winter, so that contributes as well!

Can you try `avrdude -c urclock -P ?`

This should list all available serial ports without starting a programming session

**Comment by cederom** [comment]
```
% ./avrdude -c urclock "-P ?"
avrdude OS error: cannot open port  ?: No such file or directory
avrdude error: unable to open port  ? for programmer urclock
Possible candidate serial ports are:
  -P /dev/cuau0
  -P /dev/cuaU0 or -P ch343
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.


% ./avrdude -c urclock -P /dev/cuaU0
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
avrdude warning: attempt 4 of 10: not in sync
avrdude warning: attempt 5 of 10: not in sync
avrdude warning: attempt 6 of 10: not in sync
avrdude warning: attempt 7 of 10: not in sync
avrdude warning: attempt 8 of 10: not in sync
avrdude warning: attempt 9 of 10: not in sync
avrdude warning: attempt 10 of 10: not in sync
avrdude warning: programmer is not responding; try -xstrict and/or vary -xdelay=100
avrdude error: unable to open port /dev/cuaU0 for programmer urclock
Possible candidate serial ports are:
  -P /dev/cuau0
  -P /dev/cuaU0 or -P ch343
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.


% ./avrdude -c urclock -P ch343
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
avrdude warning: attempt 4 of 10: not in sync
avrdude warning: attempt 5 of 10: not in sync
avrdude warning: attempt 6 of 10: not in sync
avrdude warning: attempt 7 of 10: not in sync
avrdude warning: attempt 8 of 10: not in sync
avrdude warning: attempt 9 of 10: not in sync
avrdude warning: attempt 10 of 10: not in sync
avrdude warning: programmer is not responding; try -xstrict and/or vary -xdelay=100
avrdude error: unable to open port /dev/cuaU0 for programmer urclock
Possible candidate serial ports are:
  -P /dev/cuau0
  -P /dev/cuaU0 or -P ch343
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

Btw I have found AtTiny104-Xplained-Nano is it supported already? :-)

**Comment by MCUdude** [comment]
```
% ./avrdude -c urclock "-P ?"
avrdude OS error: cannot open port  ?: No such file or directory
avrdude error: unable to open port  ? for programmer urclock
Possible candidate serial ports are:
  -P /dev/cuau0
  -P /dev/cuaU0 or -P ch343
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

Excellent! This means that Avrdude/libserialport can detect the CH343 VID/PID and correctly identify it. Thank you!

> Btw I have found AtTiny104-Xplained-Nano is it supported already? :-)

Correct! Use `avrdude -cxplainedmini_tpi -pattiny104`

**Comment by cederom** [comment]
I need to refresh my AVR setup :D I also found BusPirate and I have FT2232H (ktlink) that seems supported.. just how to connect them to AVR?

**Comment by cederom** [comment]
```
% avrdude -cxplainedmini_tpi -pattiny104
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e900b (probably t104)

avrdude done.  Thank you.

% avrdude -cxplainedmini_tpi -pattiny104 -P ch343
avrdude error: JTAGICE3/EDBG port names must start with usb
avrdude error: unable to open programmer xplainedmini_tpi on port ch343

avrdude done.  Thank you.
```

**Comment by MCUdude** [comment]
> I need to refresh my AVR setup :D I also found BusPirate and I have FT2232H (ktlink) that seems supported.. just how to connect them to AVR?

Yes, Avrdude has gotten a ton of new features lately, including a bund of new and exciting hardware.

I have an FT2232 board that can be used as a JTAG programmer, and it's fairly easy to get working:

```
#------------------------------------------------------------
# ft2232h_jtag
#------------------------------------------------------------

# Here a FTDI ft2232h chip is used for JTAG programming.

programmer # ft2232h_jtag
    id                     = "ft2232h_jtag";
    desc                   = "FT2232H based generic JTAG programmer";
    type                   = "avrftdi_jtag";
    prog_modes             = PM_JTAG;
    connection_type        = usb;
    usbvid                 = 0x0403;
    usbpid                 = 0x6010;
    usbdev                 = "A";
# JTAG-signals - lower ADBUS-Nibble (default)
    tck                    = 0; # AD0 (TCK)
    tdi                    = 1; # AD1 (TDI)
    tdo                    = 2; # AD2 (TDO)
    tms                    = 3; # AD3 (TMS)
;
```

```
% avrdude -cxplainedmini_tpi -pattiny104
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e900b (probably t104)

avrdude done.  Thank you.

% avrdude -cxplainedmini_tpi -pattiny104 -P ch343
avrdude error: JTAGICE3/EDBG port names must start with usb
avrdude error: unable to open programmer xplainedmini_tpi on port ch343

avrdude done.  Thank you.
```

This is to be expected. The `xplainedmini_tpi` is a USB device, so the only port that will work is `-P usb`

**Comment by stefanrueger** [comment]
Thanks! Cool new addition

> ps/2: Please add datasheet reference to the configuration too (see my example above) :-)

Agreed!
```
# CH343G chip https://www.wch-ic.com/downloads/CH343DS1_PDF.html
```

**Comment by mcuee** [comment]
This PR should be good to be merged.

**Pull request merged**
