### PR TITLE
Implement -T cmd to mix terminal commands with -U commands

### LINKED ISSUE #1322: Specify optional start address when writing to memory using -U
This could be a useful feature if Avrdude is used to write "raw data" or a binary file to a specific memory.
Currently, the -U flag always starts writing data from address 0 unless a hex file where addresses are pre-defined is used.

Let's say you want to write a 4-byte serial number to a fixed address in the flash memory, and this serial number is stored in a file.
Currently, you'll either have to somehow pipe this data into terminal mode, or that file needs to be a hex file that contains the fixed address.

How about another field(?) to the -U flag so that an optional start address could be specified as well?
Perhaps it can be used to flash hex files with a user-defined offset as well?

Then this would be possible:

```
# Write user program, serial_number.bin starting from flash address 0x10000
avrdude -cusbasp -patmega1284p -Uflash:w:userprog.hex:i -Uflash:w:0x10000:serial_number.bin:r

# Write stdin starting from flash address 0x11000
echo "0x01,0x02,0x03,0x04"| avrdude -cusbasp -patmega1284p -Uflash:w:userprog.hex:i  -Uflash:w:0x11000:-:r

# Write bootloader and OSCCAL byte to flash
 avrdude -cusbasp -patmega1284p -Uflash:w:bootloader.hex:i  -Uflash:w:0x1FE00:osccal_byte.hex:i
```

It can also be used to "burn in" an OSCCAL value into a specific flash memory address where the bootloader expects it to be, for instance with Urboot.

Is this something others also might find useful? Thoughts? Other ideas?

### PR DESCRIPTION
**Pull request by stefanrueger**
A new option `-T cmd` slots a terminal command line `cmd` into an intermixed list of `-T` terminal commands and `-U` memory operations.  The terminal command line is executed when it is its turn in the mixed list. This is done by externalising the new terminal function `terminal_line()`. As this could be *very* useful for simple high-level `libavrdude` applications, this PR moves `term.c` into `libavrdude`. As the list of to be processed operations can become long, this PR experiments with putting a paragraph before processing every `-T` and `-U`, see Discussion #1359.

Fixes #1322 in a more generic way. Example:
```
$ avrdude -qc dryrun -p m328p \
          -U urboot_m328p_1s_autobaud_uart0_pr_ee_ce.hex \
          -T 'write flash 0x7000 0xc0cac01a 0xcafe "secret Coca Cola recipe"' \
          -U flash:w:cola-vending-machine.hex \
          -T "config -v bod=*2v7" \
          -U flash:r:app+data.hex:I

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e950f (probably m328p)
avrdude: Note: flash memory has been specified, an erase cycle will be performed.
         To disable this feature, specify the -D option.
avrdude: erasing chip

avrdude: processing -U flash:w:urboot_m328p_1s_autobaud_uart0_pr_ee_ce.hex:i
avrdude: reading input file urboot_m328p_1s_autobaud_uart0_pr_ee_ce.hex for flash
         with 368 bytes in 2 sections within [0x7e80, 0x7fff]
         using 3 pages and 16 pad bytes
avrdude: writing 368 bytes flash ...
avrdude: 368 bytes of flash written
avrdude: verifying flash memory against urboot_m328p_1s_autobaud_uart0_pr_ee_ce.hex
avrdude: 368 bytes of flash verified

avrdude: processing -T write flash 0x7000 0xc0cac01a 0xcafe "secret Coca Cola recipe"

avrdude: processing -T flush
avrdude: synching cache to device ... done

avrdude: processing -U flash:w:cola-vending-machine.hex:i
avrdude: reading input file cola-vending-machine.hex for flash
         with 736 bytes in 1 section within [0, 0x2df]
         using 6 pages and 32 pad bytes
avrdude: writing 736 bytes flash ...
avrdude: 736 bytes of flash written
avrdude: verifying flash memory against cola-vending-machine.hex
avrdude: 736 bytes of flash verified

avrdude: processing -T config -v bod=*2v7
config bodlevel=bod_2v7 # 5

avrdude: processing -T flush

avrdude: processing -U flash:r:app+data.hex:I
avrdude: reading flash memory ...
avrdude: writing output file app+data.hex

avrdude done.  Thank you.
```

### CODE REVIEW

**Comment by MCUdude** [comment]
Thank you for your PR! I'd love to review this right away, but I'm leaving for a business trip in 30 minutes and won't be back until June 10th.

**Comment by mcuee** [comment]
> Thank you for your PR! I'd love to review this right away, but I'm leaving for a business trip in 30 minutes and won't be back until June 10th.

Enjoy your business trip!

**Comment by stefanrueger** [comment]
> Shenzhen 

Safe travels and enjoy China

**Comment by mcuee** [comment]
Nice PR.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1373 -c usbasp -p m2560 
-U .\urboot_m2560_1s_autobaud_uart0_rxe0_txe1_led+b7_pr_ee_ce.hex 
-T 'write flash 0x7000 0xc0cac01a 0xcafe "secret Coca Cola recipe"' 
-T 'write eeprom 0 0x10 "Hello work from avrdude"' 
-T "config -v bod=*2v7"
avrdude_pr1373: AVR device initialized and ready to accept instructions
avrdude_pr1373: device signature = 0x1e9801 (probably m2560)
avrdude_pr1373: Note: flash memory has been specified, an erase cycle will be performed.
                To disable this feature, specify the -D option.
avrdude_pr1373: erasing chip

avrdude_pr1373: processing -U flash:w:.\urboot_m2560_1s_autobaud_uart0_rxe0_txe1_led+b7_pr_ee_ce.hex:i
avrdude_pr1373: reading input file .\urboot_m2560_1s_autobaud_uart0_rxe0_txe1_led+b7_pr_ee_ce.hex for flash
                with 396 bytes in 2 sections within [0x3fe00, 0x3ffff]
                using 2 pages and 116 pad bytes
avrdude_pr1373: writing 396 bytes flash ...
Writing | ################################################## | 100% 0.05 s
avrdude_pr1373: 396 bytes of flash written
avrdude_pr1373: verifying flash memory against .\urboot_m2560_1s_autobaud_uart0_rxe0_txe1_led+b7_pr_ee_ce.hex
Reading | ################################################## | 100% 0.00 s
avrdude_pr1373: 396 bytes of flash verified

avrdude_pr1373: processing -T write flash 0x7000 0xc0cac01a 0xcafe "secret Coca Cola recipe"
Caching | ################################################## | 100% 0.12 s

avrdude_pr1373: processing -T write eeprom 0 0x10 "Hello work from avrdude"
Caching | ################################################## | 100% 0.08 s

avrdude_pr1373: processing -T config -v bod=*2v7
config bodlevel=bod_2v7 # 5
avrdude_pr1373: synching cache to device ...
Writing | ################################################## | 100% 0.36 s

avrdude_pr1373 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1373 -c usbasp -p m2560 -qqt
avrdude> dump flash 0x7000 0x20
07000  1a c0 ca c0 fe ca 73 65  63 72 65 74 20 43 6f 63  |......secret Coc|
07010  61 20 43 6f 6c 61 20 72  65 63 69 70 65 00 ff ff  |a Cola recipe...|
avrdude> dump eeprom 0 0x20
0000  10 48 65 6c 6c 6f 20 77  6f 72 6b 20 66 72 6f 6d  |.Hello work from|
0010  20 61 76 72 64 75 64 65  00 20 6f 76 65 72 20 74  | avrdude. over t|
avrdude> config bod= -vv
# Mask 0x07 of efuse: brownout detection trigger level
# conf bodlevel=bod_4v3      # 4 = 0b100 = 0x04>>0 (brownout detection at 4.3 V)
config bodlevel=bod_2v7      # 5 = 0b101 = 0x05>>0 (brownout detection at 2.7 V)
# conf bodlevel=bod_1v8      # 6 = 0b110 = 0x06>>0 (brownout detection at 1.8 V)
# conf bodlevel=bod_disabled # 7 = 0b111 = 0x07>>0 (brownout detection disabled, factory)
avrdude> quit
```

**Comment by mcuee** [comment]
Another test:

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1373 -c urclock -p m2560 -P COM43 -U eeprom:w:entest.hex:i -T 'write flash 0x100 0xaa 0x55 0xaa 0x55' -T 'write eeprom 0 0xaa 0x55 0xaa 0x55'
avrdude_pr1373: AVR device initialized and ready to accept instructions
avrdude_pr1373: device signature = 0x1e9801 (probably m2560)

avrdude_pr1373: processing -U eeprom:w:entest.hex:i
avrdude_pr1373: reading input file entest.hex for eeprom
                with 512 bytes in 1 section within [0, 0x1ff]
                using 64 pages and 0 pad bytes
avrdude_pr1373: writing 512 bytes eeprom ...
Writing | ################################################## | 100% 2.09 s
avrdude_pr1373: 512 bytes of eeprom written
avrdude_pr1373: verifying eeprom memory against entest.hex
Reading | ################################################## | 100% 0.34 s
avrdude_pr1373: 512 bytes of eeprom verified

avrdude_pr1373: processing -T write flash 0x100 0xaa 0x55 0xaa 0x55
Caching | ################################################## | 100% 0.06 s

avrdude_pr1373: processing -T write eeprom 0 0xaa 0x55 0xaa 0x55
Caching | ################################################## | 100% 0.01 s
avrdude_pr1373: synching cache to device ...
Writing | ################################################## | 100% 0.06 s

avrdude_pr1373 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1373 -c urclock -p m2560 -P COM43 -qqt
avrdude> dump flash 0x100 0x20
00100  aa 55 aa 55 ff ff ff ff  ff ff ff ff ff ff ff ff  |.U.U............|
00110  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> dump eeprom
0000  aa 55 aa 55 71 75 69 63  6b 20 62 72 6f 77 6e 20  |.U.Uquick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
0030  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
0040  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
0050  61 7a 79 20 64 6f 67 0a  54 68 65 20 71 75 69 63  |azy dog The quic|
0060  6b 20 62 72 6f 77 6e 20  66 6f 78 20 6a 75 6d 70  |k brown fox jump|
0070  73 20 6f 76 65 72 20 74  68 65 20 6c 61 7a 79 20  |s over the lazy |
0080  64 6f 67 0a 54 68 65 20  71 75 69 63 6b 20 62 72  |dog The quick br|
0090  6f 77 6e 20 66 6f 78 20  6a 75 6d 70 73 20 6f 76  |own fox jumps ov|
00a0  65 72 20 74 68 65 20 6c  61 7a 79 20 64 6f 67 0a  |er the lazy dog |
00b0  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
00c0  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
00d0  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
00e0  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
00f0  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
avrdude> quit
```

**Comment by mcuee** [comment]
As far as I am concerned, this PR is good to go.

But I am not so sure if @MCUdude wants to review after his business trip.

**Comment by stefanrueger** [comment]
Merging to lower risk of merge conflicts for further development. @MCUdude can still review at his leisure. I am confident that problems, if any, will only affect new features and can be rectified later on.

**Pull request merged**
