### PR TITLE
Enable stdin file verification and display correct number of bytes written/verified

### PR DESCRIPTION
**Pull request by stefanrueger**
This PR fixes Issues #1044, #441 and #1005, and should help for PR #1036

Counting the number of bytes written to a memory and/or verified is not trivial owing to potential holes in the input file and to potential trailing 0xff bytes in flash memory that are not written per default (but see -A). The new function memstats(), which is best called just after an input file has been read into mem->buf/mem->tags, computes the right number of bytes written and allows easy computation of the number of bytes verified.

This PR also changes the strategy for the default verification after writing to a chip memory, so that the input file only needs reading once thus enabling successful verification of stdin input files.

Other, minor changes:
 - Improving the grammar of AVRDUDE output, eg, 1 byte written instead of 1 bytes written
 - Better description of the input file structure in terms of its sections, the interval it spans, the number  of pages, the number of padding bytes in pages, and the number of actually cut off trailing 0xff bytes for flash
 - Printing <stdin> or <stdout> instead of - in the -U routines
 - Option -V no longer needs to be specified before option -U in order to work

As an aside this PR also provides useful helper functions for printing plural(), inname(), outname() and interval() all of which return strings fit for printing.

Examples using  [blink-mega2560+lext-test.hex](https://github.com/avrdudes/avrdude/files/9236425/blink-mega2560%2Blext-test.hex.txt) and [sketch-ending-in-ff.hex](https://github.com/avrdudes/avrdude/files/9236427/sketch-ending-in-ff.hex.txt):

```
$ avrdude -qp ATmega2560 -c ... -U blink-mega2560+lext-test.hex

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: input file blink-mega2560+lext-test.hex auto detected as Intel Hex
avrdude: reading input file blink-mega2560+lext-test.hex
         with 1346 bytes in 4 sections within [0, 0x3106d]
         using 7 pages and 446 pad bytes
avrdude: writing 1346 bytes flash ...
avrdude: 1346 bytes of flash written
avrdude: verifying flash memory against blink-mega2560+lext-test.hex
avrdude: 1346 bytes of flash verified

avrdude done.  Thank you.
```

```
$ avrdude -qp ATmega328P -c ... -U sketch-ending-in-ff.hex

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: input file sketch-ending-in-ff.hex auto detected as Intel Hex
avrdude: reading input file sketch-ending-in-ff.hex
         with 2160 bytes in 1 section within [0, 0x888]
         using 17 pages and 16 pad bytes, cutting off 25 trailing 0xff bytes
avrdude: writing 2160 bytes flash ...
avrdude: 2160 bytes of flash written
avrdude: verifying flash memory against sketch-ending-in-ff.hex
avrdude: 2185 bytes of flash verified

avrdude done.  Thank you.
```

```
$ echo "Hello, world..." | avrdude -qp ATmega328P -c ... -U eeprom:w:-:r

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file <stdin>
          with 16 bytes in 1 section within [0, 0xf]
         using 4 pages and 0 pad bytes
avrdude: writing 16 bytes eeprom ...
avrdude: 16 bytes of eeprom written
avrdude: verifying eeprom memory against <stdin>
avrdude: 16 bytes of eeprom verified

avrdude done.  Thank you.
```

### CODE REVIEW

**Comment by MCUdude** [comment]
Thank you Stefan! I can confirm that #1005 and #1044 is resolved by this PR

## Without this PR:
Arduino sketch with bootloader in the same hex file:

<details>

```
$ ./avrdude -cusbasp -patmega328p -Uflash:w:/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_563573/Blink.ino.with_bootloader.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_563573/Blink.ino.with_bootloader.hex"
avrdude: writing flash (32768 bytes):

Writing | ################################################## | 100% 0.31s

avrdude: 32768 bytes of flash written
avrdude: verifying flash memory against /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_563573/Blink.ino.with_bootloader.hex:

Reading | ################################################## | 100% 0.18s

avrdude: 32768 bytes of flash verified

avrdude done.  Thank you.
```

</details>

Write to EEPROM from stdin:

<details>

```
$ yes "The quick brown fox jumps over the lazy dog"| head -2 | ./avrdude -cusbasp -p atmega328p -U eeprom:w:-:r

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file <stdin>
         with 88 bytes in 1 section within [0, 0x57]
         using 22 pages and 0 pad bytes
avrdude: writing 88 bytes eeprom ...

Writing | ################################################## | 100% 0.92s

avrdude: 88 bytes of eeprom written
avrdude: verifying eeprom memory against <stdin>

Reading | ################################################## | 100% 0.03s

avrdude: 88 bytes of eeprom verified

avrdude done.  Thank you.
```

</details>

<br/>
<br/>

## With this PR:

Arduino sketch with bootloader in the same hex file:

<details>

```
$ ./avrdude -cusbasp -patmega328p -Uflash:w:/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_563573/Blink.ino.with_bootloader.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_563573/Blink.ino.with_bootloader.hex
         with 1514 bytes in 3 sections within [0, 0x7fff]
         using 13 pages and 150 pad bytes
avrdude: writing 1514 bytes flash ...

Writing | ################################################## | 100% 0.30s

avrdude: 1514 bytes of flash written
avrdude: verifying flash memory against /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_563573/Blink.ino.with_bootloader.hex

Reading | ################################################## | 100% 0.20s

avrdude: 1514 bytes of flash verified

avrdude done.  Thank you.
```

</details>

Write to EEPROM from stdin:

<details>

```
$ yes "The quick brown fox jumps over the lazy dog"| head -2 | ./avrdude -cusbasp -p atmega328p -U eeprom:w:-:r

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file "<stdin>"
avrdude: writing eeprom (88 bytes):

Writing | ################################################## | 100% 0.91s

avrdude: 88 bytes of eeprom written
avrdude: verifying eeprom memory against -:

Reading | ################################################## | 100% 0.00s

avrdude: 0 bytes of eeprom verified

avrdude done.  Thank you.
```

</details>

**Comment by MCUdude** [comment]
Another thing to point out is that previously, a memory with size 0 would be ignored, but now it doesn't continue.

This is how the "fake" efuse defined for ATmega8 in avrdude.conf. This trick is currently being used by Arduino IDE.
```
    memory "efuse"
        size            = 0;
      ;
```

Without this PR:
```
$ ./avrdude -C /Users/hans/Documents/Arduino/hardware/MiniCore/avr/avrdude.conf -c usbasp -p atmega8 -Uefuse:w:0xff:m -Ulfuse:w:0xff:m

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9307 (probably m8)
avrdude: reading input file "0xff"
avrdude: writing efuse (0 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 0 bytes of efuse written
avrdude: verifying efuse memory against 0xff:

Reading | ################################################## | 100% 0.00s

avrdude: 0 bytes of efuse verified
avrdude: reading input file "0xff"
avrdude: writing lfuse (1 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 1 bytes of lfuse written
avrdude: verifying lfuse memory against 0xff:

Reading | ################################################## | 100% 0.00s

avrdude: 1 bytes of lfuse verified

avrdude done.  Thank you.
```

With this PR:
```
./avrdude -C /Users/hans/Documents/Arduino/hardware/MiniCore/avr/avrdude.conf -c usbasp -p atmega8 -Uefuse:w:0xff:m -Ulfuse:w:0xff:m

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9307 (probably m8)
avrdude: reading input file 0xff
avrdude: ATmega8 efuse size 0 or page size 1 not set

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
> a memory with size 0 would be ignored

@MCUdude Great catch! I have relaxed the sanity checks, so memory size zero is OK again

```
$ avrdude -qp m8 -F -c ... -U efuse:w:0xff:m && echo OK

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: Expected signature for ATmega8 is 1E 93 07
avrdude: reading input file 0xff
         with 0 bytes in 0 sections within [0, -1]
avrdude: writing 0 bytes efuse ...
avrdude: 0 bytes of efuse written
avrdude: verifying efuse memory against 0xff
avrdude: 0 bytes of efuse verified

avrdude done.  Thank you.

OK
```

File reads are limited to the memory they are destined for, which explains the 0 bytes read (of the immediate file with one byte).

**Comment by mcuee** [comment]
I can confirm that #441 is now fixed.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1051 -c usbasp -qp m2560 
-U .\blink-mega2560+lext-test.hex -V

avrdude_pr1051.exe: AVR device initialized and ready to accept instructions
avrdude_pr1051.exe: Device signature = 0x1e9801 (probably m2560)
avrdude_pr1051.exe: NOTE: "flash" memory has been specified, an erase cycle will be performed
                    To disable this feature, specify the -D option.
avrdude_pr1051.exe: erasing chip
avrdude_pr1051.exe: input file .\blink-mega2560+lext-test.hex auto detected as Intel Hex
avrdude_pr1051.exe: reading input file .\blink-mega2560+lext-test.hex for flash
                    with 1346 bytes in 4 sections within [0, 0x3106d]
                    using 7 pages and 446 pad bytes
avrdude_pr1051.exe: writing 1346 bytes flash ...
avrdude_pr1051.exe: 1346 bytes of flash written

avrdude_pr1051.exe done.  Thank you.
```

**Comment by mcuee** [comment]
#1044 is also okay now.

```
$ yes "The quick brown fox jumps over the lazy dog" | ./avrdude -c usbasp -p m2560 -U eeprom:w:-:r

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude.exe: Device signature = 0x1e9801 (probably m2560)
avrdude.exe: reading input file <stdin> for eeprom
             with 4096 bytes in 1 section within [0, 0xfff]
             using 512 pages and 0 pad bytes
avrdude.exe: writing 4096 bytes eeprom ...

Writing | ################################################## | 100% 42.54s

avrdude.exe: 4096 bytes of eeprom written
avrdude.exe: verifying eeprom memory against <stdin>

Reading | ################################################## | 100% 1.15s

avrdude.exe: 4096 bytes of eeprom verified

avrdude.exe done.  Thank you.

```

**Comment by MCUdude** [comment]
@stefanrueger I _think_ something went wrong when updating your fork. You just added 44 commits to this PR, and all of them have already been merged into main.

**Comment by stefanrueger** [comment]
@MCUdude One of my goals in July was to understand  git rebase upstream/main main followed by a local rebase of my branch followed by an elegant git push upstream without using a clickety-dickety web interface ... and I failed (again): git reports diverging branches, refuses to do what I *think* needs doing and suggests a solution that works but is inelegant: Technically, the PR is still what need doing (I can tell by looking at the changes that this PR effects), but has the disadvantage of a non-linear history (as you spotted redoing commits that already were done). I can abandon this PR and copy over the changed files for a new attempt (OK because I did not have an elaborate commit history for this PR) or we tolerate the non-linear history. *Thoughts?* I am OK either way.

**Comment by MCUdude** [comment]
It's fairly easy to just drop the commits that doesn't belong in this PR.

* First, do a backup, just in case.
* Run `git log --oneline` and copy the 2nd short hash in the list (should be 84fa3ee I think)
* Run `git rebase -i 84fa3ee`
* In the text file that shows up, replace the first-word `pick` with `drop` on every commit that you want to remove from this branch.
* When you're done, save the file and force-push the changes by using `git push -f`.

**Comment by stefanrueger** [comment]
@MCUdude Thanks for tips. I can confirm this has worked, and the source stayed the same. git log shows me that I am where I want to be (I *think*!): a rebased branch with the additions at the end. However, now the [branch on my fork](https://github.com/stefanrueger/avrdude/tree/rwv-stats) is 48 commits ahead, 57 commits behind avrdudes:main. So, it looks like if I was to merge this we'd be at some weird commit history (again). The git guru in my company reckons there is a simple solution: delete my repositories, remove my account, recursively delete my home directory, uninstall the OS, raze my disks, give notice, apply for a new identity, relocate under a witness protection scheme, and start again :)

**Pull request closed without merging**
