### PR TITLE
Add xplainedpro_pdi programmer

### PR DESCRIPTION
**Pull request by mcuee**
This will fix https://github.com/avrdudes/avrdude/issues/1143.

Xplained Pro should be able to support PDI mode as per the documentation.

Reference: take note that the following document does not cover UPDI support. https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-42096-Microcontrollers-Embedded-Debugger_User-Guide.pdf

Reference discussion:
* https://github.com/avrdudes/avrdude/pull/1139#issuecomment-1286760773
* https://github.com/avrdudes/avrdude/discussions/1019#discussioncomment-3569440

Sign-off by xiaofanc@gmail.com

### CODE REVIEW

**Comment by mcuee** [comment]
Even though I can not test it, I think it is correct based on the documentation.

**Comment by MCUdude** [comment]
Thanks for the PR!

You're correct in your assumption that the Xplained Pro in PDI mode _should_ work with Avrdude out of the box. I've used several JTAG3/EDBG-based programmers to program Xmegas.

However, since I don't own any Xplained Pro hardware, I'm not able to test this either. Even though this PR _should_ work, I'm not sure I'm comfortable merging this without testing it on actual hardware.

**Comment by mcuee** [comment]
@MCUdude 

You are right, it is better to wait for someone to test this PR first before merging.

**Comment by MCUdude** [comment]
PR can safely be merged, but the new programming option should be added to the docs.
https://avrdudes.github.io/avrdude/current/avrdude_3.html#Option-Descriptions

```
$ ./avrdude -cxplainedpro_pdi -patxmega128a1u -v -Uflash:w:0x55_128kib.hex:i

avrdude: Version 7.0-20220508
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is /Users/hans/Downloads/avrdude-terminal/src/avrdude.conf
         User configuration file is /Users/hans/.avrduderc

         Using Port                    : usb
         Using Programmer              : xplainedpro_pdi
avrdude: found CMSIS-DAP compliant device, using EDBG protocol
         AVR Part                      : ATxmega128A1U
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           fuse1                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse2                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse4                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse5                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           lock                    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
           prodsig                 0     0     0    0 no         50   50      0     0     0 0x00 0x00
           data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
           eeprom                  0     0     0    0 no       2048   32      0     0     0 0x00 0x00
           flash                   0     0     0    0 no     139264  512      0     0     0 0x00 0x00
           application             0     0     0    0 no     131072  512      0     0     0 0x00 0x00
           apptable                0     0     0    0 no       8192  512      0     0     0 0x00 0x00
           boot                    0     0     0    0 no       8192  512      0     0     0 0x00 0x00
           usersig                 0     0     0    0 no        512  512      0     0     0 0x00 0x00
           fuse0                   0     0     0    0 no          1    1      0     0     0 0x00 0x00

         Programmer Type : JTAGICE3_PDI
         Description     : Atmel AVR XplainedPro in PDI mode
         ICE HW version  : 240
         ICE FW version  : 3.37 (rel. 438)
         Serial number   : ATML1802041800004588
         Vtarget         : 3.29 V
         JTAG clock megaAVR/program   : 1000 kHz
         JTAG clock megaAVR/debug     : 1000 kHz
         JTAG clock Xmega             : 1000 kHz
         PDI/UPDI clock Xmega/megaAVR : 1000 kHz
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e974c (probably x128a1u)
avrdude: Note: programmer supports page erase for Xmega devices.
         Each page will be erased before programming it, but no chip erase is performed.
         To disable page erases, specify the -D option; for a chip-erase, use the -e option.
avrdude: reading input file 0x55_128kib.hex for flash
         with 131071 bytes in 1 section within [0, 0x1fffe]
         using 256 pages and 1 pad byte
avrdude: writing 131071 bytes flash ...

Writing | ################################################## | 100% 5.69 s 

avrdude: 131071 bytes of flash written
avrdude: verifying flash memory against 0x55_128kib.hex

Reading | ################################################## | 100% 2.65 s 

avrdude: 131071 bytes of flash verified

avrdude done.  Thank you.
```

**Comment by mcuee** [comment]
@MCUdude 
Great. Thanks a lot for the help. So I think this can be merged as well.

**Pull request merged**
