### PR TITLE
Adapt stk500 readback values for usbtiny.c

### LINKED ISSUE #1508: Eeprom file written correctly with avrdude 7.1 generates error with 7.2
Overview                                                                                                                                 
                                                                                                                                         
An eeprom file, which is correctly written to an atmega328p by avrdude 6.3 7.0 and 7.1, generates a verification error when written with avrdude 7.2. Looking at the eeprom in -t mode shows that the eeprom has not been correctly written.                                                                                                   
                                                                                                                                         
Example error                                                                                                                            
                                                                                                                                         
The original eeprom file is relatively large but a similar error                                                                      
can be reproduced with this small hex file.                                                                                              
                                                                                                                                         
With 7.2 this hex file is incorrectly written, but with 7.1 no error                                                                     
```                                                                                                                                         
:02000200AABB97
:00000001FF
```                                                                                                                                         
I tried a few more examples                                                                                                              
                                                                                                                                         
Add a line and it is correctly written with 7.2 and 7.1                                                                                  
```                                                                                                                                         
:02000000DDCC55
:02000200AABB97
:00000001FF
```                                                                                                                                         
But this file is also correctly written with 7.2 and 7.1                                                                                 
```                                                                                                                                         
:02000400AABB95
:00000001FF
```                                                                                                                                         
And finally this is the line from the original file which caused the                                                                     
error with 7.2 but not 7.1 7.0 and 6.3                                                                                                   
```                                                                                                                                         
:10003400FFFFF00AC4019000F1095C00B008EB0A6C
:00000001FF
```
Is is possible to confirm this behaviour (outside of my setup)?

Kind regards and thanks,
Tristan

### PR DESCRIPTION
**Pull request by stefanrueger**
Fixes #1508

### CODE REVIEW

**Comment by mcuee** [comment]
Yes, this PR is good. The two problematic hex files are now okay with `-c usbtiny`.

```
PS C:\work\avr\avrdude_test\avrdude_bin> cat .\eep.hex
:02000200AABB97
:00000001FF
PS C:\work\avr\avrdude_test\avrdude_bin> cat .\eep2.hex
:10003400FFFFF00AC4019000F1095C00B008EB0A6C
:00000001FF
```

1) erase the EEPROM and then test with the second hex file -- now it is okay.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1511 -C .\avrdude_pr1511.conf -c usbtiny -p m328p -U eeprom:w:eep2.hex:i
avrdude_pr1511: AVR device initialized and ready to accept instructions
avrdude_pr1511: device signature = 0x1e950f (probably m328p)

avrdude_pr1511: processing -U eeprom:w:eep2.hex:i
avrdude_pr1511: reading input file eep2.hex for eeprom
                with 16 bytes in 1 section within [0x34, 0x43]
                using 4 pages and 0 pad bytes
avrdude_pr1511: writing 16 bytes eeprom ...
Writing | ################################################## | 100% 0.01 s
avrdude_pr1511: 16 bytes of eeprom written
avrdude_pr1511: verifying eeprom memory against eep2.hex
Reading | ################################################## | 100% 0.01 s
avrdude_pr1511: 16 bytes of eeprom verified

avrdude_pr1511 done.  Thank you.
```

2) erase the EEPROM and then test with the first hex file -- now it is okay.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1511 -C .\avrdude_pr1511.conf -c usbtiny -p m328p -U eeprom:w:eep.hex:i
avrdude_pr1511: AVR device initialized and ready to accept instructions
avrdude_pr1511: device signature = 0x1e950f (probably m328p)

avrdude_pr1511: processing -U eeprom:w:eep.hex:i
avrdude_pr1511: reading input file eep.hex for eeprom
                with 2 bytes in 1 section within [2, 3]
                using 1 page and 2 pad bytes
avrdude_pr1511: writing 2 bytes eeprom ...
Writing | ################################################## | 100% 0.04 s
avrdude_pr1511: 2 bytes of eeprom written
avrdude_pr1511: verifying eeprom memory against eep.hex
Reading | ################################################## | 100% 0.01 s
avrdude_pr1511: 2 bytes of eeprom verified

avrdude_pr1511 done.  Thank you.
```

**Comment by MCUdude** [comment]
Looks good to me!

**Comment by stefanrueger** [comment]
It might be helpful if some other STK500v2 programmers were tested besides `usbtiny`. If they get it wrong then this PR needs a different approach. I suggest testing with
```
avrdude  -c ... -p ... -qq -U eeprom:w:0xaaff:m -U eeprom:w:0xffaa:m && echo OK
```

**Comment by mcuee** [comment]
> It might be helpful if some other STK500v2 programmers were tested besides `usbtiny`. If they get it wrong then this PR needs a different approach. I suggest testing with
> 
> ```
> avrdude  -c ... -p ... -qq -U eeprom:w:0xaaff:m -U eeprom:w:0xffaa:m && echo OK
> ```

Looks good.

```
C:\work\avr\avrdude_test\avrdude_bin> function prompt { }

PS>.\avrdude_pr1511 -C .\avrdude_pr1511.conf -c avrisp2 -p m328p -qq -U eeprom:w:0xaaff:m -U eeprom:w:0xffaa:m && echo OK
OK

PS>.\avrdude_pr1511 -C .\avrdude_pr1511.conf -c avrisp2 -p m328p -qq -U eeprom:w:eep.hex:i && echo OK
OK

PS>.\avrdude_pr1511 -C .\avrdude_pr1511.conf -c avrisp2 -p m328p -qq -U eeprom:w:eep2.hex:i && echo OK
OK

PS>cat .\eep.hex
:02000200AABB97
:00000001FF

PS>cat .\eep2.hex
:10003400FFFFF00AC4019000F1095C00B008EB0A6C
:00000001FF
```

**Comment by mcuee** [comment]
I think this PR is good to go.

**Pull request merged**
