### PR TITLE
Writing BOOTROW for Curiosity Nano

### PR DESCRIPTION
**Pull request by askn37**
https://github.com/avrdudes/avrdude/issues/1868

This suggestion is valid for the following products. It may also be valid for PICKit4 + AVR-DU/EB series configurations.
This does not affect program drivers that do not use "jtag3.c".

- Curiosity Nano AVR16EB32
- Curiosity Nano AVR64DU32

Before the PR, BOOTROW can only be read, rewriting fails, and pages cannot be erased.

After PR, BOOTROW can be rewritten with the following exceptions:

- For AVR-DU series, bits can only be changed from 1 to 0. Page erase still does not work, meaning it can only be successfully written once after chip erase. This issue may not occur for AVR-EB series. Other chips do not have BOOTROW, so it is not relevant.
- On AVR-DU series, erasing BOOTROW only succeeds with chip erase, not if the protection bits in FUSE_SYSCFG0 are enabled.

Any open issues regarding "jtag3.c" are summarized at the top of the file.

### CODE REVIEW

**Comment by stefanrueger** [comment]
@askn37 Thank you! That's great. Happy to merge once it's been tested @mcuee? @MCUdude? Alternatively, if you have a short example of a run without the PR and one with the PR, this would also help.

I like the summary on top of the file. Vvv helpful. Are you OK with me pushing a commit directly onto your branch for minor changes (typos, adapting to AVRDUDE style etc)? If so, what is your preference when merging? Squash merge or normal merge?

Thanks again

**Comment by askn37** [comment]
@stefanrueger 

> I like the summary on top of the file. Vvv helpful. Are you OK with me pushing a commit directly onto your branch for minor changes (typos, adapting to AVRDUDE style etc)? If so, what is your preference when merging? Squash merge or normal merge?

Please proofread. I expect any conflicts will be minor, so a squash merge is fine.

**Comment by MCUdude** [comment]
PR works great!

```
$ ./avrdude -cpkobn_updi -pavr16eb32 -T 'write bootrow 0 "Hello World!"'
Caching | ################################################## | 100% 0.01 s 
Synching cache to device ... 
Writing | ################################################## | 100% 0.05 s 

Avrdude done.  Thank you.

$ ./avrdude -cpkobn_updi -pavr16eb32 -T 'read bootrow'
Reading | ################################################## | 100% 0.02 s 
0000  48 65 6c 6c 6f 20 57 6f  72 6c 64 21 00 ff ff ff  |Hello World!....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.



$ ./avrdude -cpkobn_updi -pavr64du32 -T 'write bootrow 0 "Lorem ipsum dolor sit amet"'
Caching | ################################################## | 100% 0.04 s 
Synching cache to device ... 
Writing | ################################################## | 100% 0.16 s 

Avrdude done.  Thank you.

$ ./avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.05 s 
0000  4c 6f 72 65 6d 20 69 70  73 75 6d 20 64 6f 6c 6f  |Lorem ipsum dolo|
0010  72 20 73 69 74 20 61 6d  65 74 00 ff ff ff ff ff  |r sit amet......|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.

$ ./avrdude -cpickit4_updi -pavr64du32 -T 'write bootrow 0 "The quick brown fox jumps over the lazy dog"'
Device signature = 1E 96 22 (AVR64DU28)
Error: expected signature for AVR64DU32 is 1E 96 21; double
check chip or use -F to carry on regardless

Avrdude done.  Thank you.
Hanss-MacBook-Pro:src hans$ ./avrdude -cpickit4_updi -pavr64du28 -T 'write bootrow 0 "The quick brown fox jumps over the lazy dog"'
Caching | ################################################## | 100% 0.05 s 
Synching cache to device ... 
Writing | ################################################## | 100% 0.17 s 

Avrdude done.  Thank you.

$ ./avrdude -cpickit4_updi -pavr64du28 -T 'read bootrow'
Reading | ################################################## | 100% 0.05 s 
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 00 ff ff ff ff  |he lazy dog.....|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
```

**Comment by askn37** [comment]
@MCUdude 

By all means, try `-T erase bootrow` after messing with memory too.

My guess is that the AVR-Ex series has an NVM ERWR (overwrite) mechanism to rewrite any byte or word, so as long as the programmer uses that, page erase isn't needed at all.

But in the AVR-Dx series, NVM ERWR is only available for FUSE or EEPROM, so page erase is required for FLASH, USERROW and BOOTROW.  Curiosity's firmware seems to have trouble with this behavior.

*Implementations like JTAG2UPDI and UPDI4AVR that have their own dirty page check and erase algorithms don't need page erase.*

**Comment by stefanrueger** [comment]
I initially also thought "Wow, this PR even works without page erase". But note that the examples that @MCUdude shows are with *different* parts. @MCUdude Could you please try and new and different text over existing text in `bootrow`? Then we know!

**Comment by MCUdude** [comment]
@stefanrueger apparently it works flawlessly!

```
$ ./avrdude -cpkobn_updi -pavr16eb32 -T 'read bootrow'
Reading | ################################################## | 100% 0.02 s 
0000  48 65 6c 6c 6f 20 57 6f  72 6c 64 21 00 ff ff ff  |Hello World!....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.

$ ./avrdude -cpkobn_updi -pavr16eb32 -T 'write bootrow 0 "Bootrow test"'
Caching | ################################################## | 100% 0.01 s 
Synching cache to device ... done

Avrdude done.  Thank you.

$ ./avrdude -cpkobn_updi -pavr16eb32 -T 'read bootrow'
Reading | ################################################## | 100% 0.01 s 
0000  42 6f 6f 74 72 6f 77 20  74 65 73 74 00 ff ff ff  |Bootrow test....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
```

**Comment by askn37** [comment]
@MCUdude @stefanrueger 

Good news!

AVR-EB seems fine. Currently only AVR-DU has limitations, but I think this is due to a bug in Microchip's firmware. Apart from that this PR works as expected.

**Comment by askn37** [comment]
For comparison, here are the results on the AVR64DU32:

```
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -v
Avrdude version 7.3-20240806 (5adbf441)
Copyright see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

System wide configuration file is /Users/askn/Collaborator/avrdude_preq/build_darwin/src/avrdude.conf
User configuration file is /Users/askn/.avrduderc

Using port            : usb
Using programmer      : pkobn_updi
AVR part              : AVR64DU32
Programming modes     : SPM, UPDI
Programmer type       : JTAGICE3_UPDI
Description           : Curiosity nano (nEDBG) in UPDI mode
ICE HW version        : 0
ICE FW version        : 1.31 (rel. 39)
Serial number         : MC020059804RYN000159
Vtarget               : 5.01 V
PDI/UPDI clk          : 100 kHz

Partial Family_ID returned: "AVR "
Silicon revision: 1.3

AVR device initialized and ready to accept instructions
Device signature = 1E 96 21 (AVR64DU32)

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'write bootrow 0 "Hello World!"'
Caching | ################################################## | 100% 0.04 s 
Synching cache to device ... 
Writing | ################################################## | 100% 0.16 s 

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  48 65 6c 6c 6f 20 57 6f  72 6c 64 21 00 ff ff ff  |Hello World!....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'write bootrow 0 "Bootrow test"'
Caching | ################################################## | 100% 0.04 s 
Synching cache to device ... 
Writing | -------------------------------------------------- | 0% 0.16 s 
Error: verification mismatch at bootrow page addr 0x0000

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  40 65 6c 64 62 20 57 20  70 64 60 20 00 ff ff ff  |@eldb W pd` ....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -e -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
```

**Comment by mcuee** [comment]
Nice PR.

I do not have the following two boards so I can not test this PR myself.
Curiosity Nano AVR16EB32
Curiosity Nano AVR64DU32

**Comment by askn37** [comment]
Bad news: Weird code found in "jtag3.c"

- jtag3_initialize_tpi() calls mmt_free(resp) multiple times even though resp is a local variable.

Should I fix it now and merge it with this PR, or should I make it a separate PR?

https://github.com/avrdudes/avrdude/blob/f06b436fe7bbe51b28feb14ef67340e6c1d18201/src/jtag3.c#L2890-L2946

**Comment by stefanrueger** [comment]
> jtag3_initialize_tpi() calls mmt_free(resp) multiple times 

I think the code is correct. Each time `resp` is set to allocated space just a couple of lines before: https://github.com/avrdudes/avrdude/blob/f06b436fe7bbe51b28feb14ef67340e6c1d18201/src/jtag3.c#L2933-L2935

I know, it's a wild goose chase to find the exact place `resp` is *actually* set and to verify that all is correct. But I think it is (I've done the goose chases before).

More could be done to make the code more robust against double `free(p)`, eg, setting `p` to `NULL` after the free() but it's not advisable to do so just before a release (mid August).

**Comment by askn37** [comment]
@stefanrueger 

> I think the code is correct. Each time resp is set to allocated space just a couple of lines before:

Thanks for your comment. The trick is very confusing, but I found that all these similar statements allocate memory via the following code:

https://github.com/avrdudes/avrdude/blob/f06b436fe7bbe51b28feb14ef67340e6c1d18201/src/jtag3.c#L632-L661

This seems like an essential piece of maintenance knowledge.

**Comment by stefanrueger** [comment]
@askn37 I think your introductory comment for jtag3.c is an excellent idea. Other source files should have similar comments. I added a Scope section and changed the comment style to AVRDUDE style (no all-caps with exception of AVRDUDE, only use quotes when absolutely necessary, etc).

Please check whether the comments are still correct.

Also: I changed the terminal cache behaviour. It should now do a read/CE/write cycle if the programmer cannot set a bit in bootrow, Please try that out in your branch.

**Comment by stefanrueger** [comment]
OK, if all works, I'll commit this PR soonish. Thanks all round

**Comment by askn37** [comment]
Again, a confirmation test was carried out.

```
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -v
Avrdude version 7.3-20240807 (ceaaeb64)
Copyright see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

System wide configuration file is /Users/askn/Collaborator/avrdude_preq/build_darwin/src/avrdude.conf
User configuration file is /Users/askn/.avrduderc

Using port            : usb
Using programmer      : pkobn_updi
AVR part              : AVR64DU32
Programming modes     : SPM, UPDI
Programmer type       : JTAGICE3_UPDI
Description           : Curiosity nano (nEDBG) in UPDI mode
ICE HW version        : 0
ICE FW version        : 1.31 (rel. 39)
Serial number         : MC020059804RYN000159
Vtarget               : 5.01 V
PDI/UPDI clk          : 100 kHz

Partial Family_ID returned: "AVR "
Silicon revision: 1.3

AVR device initialized and ready to accept instructions
Device signature = 1E 96 21 (AVR64DU32)

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'write bootrow 0 "Hello World!"'
Caching | ################################################## | 100% 0.04 s 
Synching cache to device ... 
Writing | ################################################## | 100% 0.16 s 

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  48 65 6c 6c 6f 20 57 6f  72 6c 64 21 00 ff ff ff  |Hello World!....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'write bootrow 0 "Bootrow test"'
Caching | ################################################## | 100% 0.04 s 
Synching cache to device ... 
Reading | ################################################## | 100% 12.04 s 
Erasing | ################################################## | 100% 0.02 s 
Writing | ################################################## | 100% 5.48 s 

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  42 6f 6f 74 72 6f 77 20  74 65 73 74 00 ff ff ff  |Bootrow test....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
bash-3.2$ ./build_darwin/src/avrdude -cpkobn_updi -pavr64du32 -e -T 'read bootrow'
Reading | ################################################## | 100% 0.04 s 
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

Avrdude done.  Thank you.
```

The second write was slower but it's working perfectly!

**Comment by stefanrueger** [comment]
Brilliant, thanks for confirming @askn37

**Comment by MCUdude** [comment]
> As an aside, here are the results of running it on the UPDI4AVR-USB currently under development. The firmware fully understands the characteristics of the NVM controller and manages the memory, so there is no delay for the user. (Preparing for release)

@askn37 very, very cool! On what hardware are you planning to run the UPDI4AVR-USB? Can it be done on an AVR-DU? 🚀

**Comment by askn37** [comment]
@MCUdude 

> @askn37 very, very cool! On what hardware are you planning to run the UPDI4AVR-USB? Can it be done on an AVR-DU? 🚀

It can only be installed on the AVR-DU series. The USB Full-Speed protocol stack was written from scratch relying only on the USB-IF standard and datasheets. This is a generic OS standard CDC-ACM/HID composite device with basic CMSIS-DAP/EDBG/JTAGICE3 functionality. No dWire and OCD. VIP:PID can be changed in EEPROM. Supports UPDI and TPI, perfectly replacing legacy JTAG2UPDI and microUPDI. PDI may be added in the future. Optional features such as HV control are determined by package size, but the 16KiB/14P model offers a 1Mbps VCP-UART bridge and DTR signal. Please stay tuned.

**Pull request merged**
