### PR TITLE
Add `extra_features` to easily identify a programmers special abilities

### PR DESCRIPTION
**Pull request by MCUdude**
#1235 related.

It's now possible to specify "extra features" a programmer might have in avrdude.conf.
I've also added three features that Avrdude can utilize: `HAS_SUFFER`, `HAS_VTARG_SWITCH`, and `HAS_VTARG_ADJ`, 

Xplained Mini boards can read and write the mEDBG SUFFER value using `-xsuffer`:
```
$ ./avrdude -cxplainedmini_isp -patmega328pb -xsuffer
SUFFER register value read as 0xfe
```

```
$ ./avrdude -cxplainedmini_isp -patmega328pb -xsuffer=0xff
SUFFER register value changed from 0xfe to 0xff
```

Xplained Mini boards can now also control their target power switch if they have one:

```
$ ./avrdude -cxplainedmini_isp -patmega328pb -xvtarg_switch
Vtarg switch setting read as 1. Target power is switched on
```

```
$ ./avrdude -cxplainedmini_isp -patmega328pb -xvtarg_switch=0
Vtarg switch setting changed from 1 to 0
```

I haven't done anything significant with `HAS_VTARG_ADJ` other than replacing the code that checks the programmer ID before determining if it has target power adjust capabilities or not:

From this:
```c
  for(LNODEID ln=lfirst(pgm->id); ln; ln=lnext(ln)) {
    if (matches(ldata(ln), "powerdebugger") ||
        matches(ldata(ln), "pkob")) {
      pgm->set_vtarget  = jtag3_set_vtarget;
      break;
    }
  }
```

To this:
```c
  if (pgm->extra_features & HAS_VTARG_ADJ)
    pgm->set_vtarget  = jtag3_set_vtarget;
```

### CODE REVIEW

**Comment by stefanrueger** [comment]
Please test whether the output of `avrdude -c*/s`  (canonical programmer definitions) can be parsed by `avrdude` and if so, whether it differs from the programmer definitions in `avrdude.conf.in`?

**Comment by MCUdude** [comment]
> Please test whether the output of avrdude -c*/s (canonical programmer definitions) can be parsed by avrdude and if so, whether it differs from the programmer definitions in avrdude.conf.in

Thanks! I've pushed a tiny correction to avrdude.conf.in

**Comment by stefanrueger** [comment]
|  tiny correction to avrdude.conf.in

And ... does `avrdude` now parse the changed `avrdude.conf.in` and does `-c*/s` output the same as was in `avrdude.conf`? The whole circle needs to work - if not there is an error in the implementation of the component.

**Comment by MCUdude** [comment]
> And ... does avrdude now parse the changed avrdude.conf.in and does -c*/s output the same as was in avrdude.conf? The whole circle needs to work - if not there is an error in the implementation of the component.

That's obviously something to check. And I found a typo! But yes, the whole circle works now.

**Comment by stefanrueger** [comment]
@MCUdude Neat piece of work! I particularly like that programmers now can be described in more detail. And that we don't have to rely on the programmer name any more.

 I cannot comment on functionality so only a few (tiny) comments otherwise:

`avrdude.1` and `avrdude.texi`
 - Update the date in line 21 of avrdude.1 (I always forget this, too :)
 - not providing an equal sign and a value. `->` -xvtarg_switch alone.
 - always be on after power cycle `->` always be on after a power cycle

`avrdude.conf.in`
 - Maybe change `HAS_<ft.> {| has_<ft.>}`  to  `HAS_<fea> {| HAS_<fea>}` (in particular, note capital HAS_)
 - I noted that (for the first time!) the id of programmers is given as a list (eg, `id = "powerdebugger", "powerdebugger_jtag";`); out of curiosity: what does this achieve and where is that feature used and where could it be used?

`jtag3.c`
 - read as %u. Target power `->` read as %u: target power
 - I personally find `PDATA(pgm)->suffer_data` easier to read than `&(PDATA(pgm)->suffer_data[0])` (multiple times, but it's your prerogative how to code)
 - Similarly `PDATA(pgm)->suffer_data+1` instead of `&(PDATA(pgm)->suffer_data[1])` or `(&PDATA(pgm)->suffer_data[1])` but, again, it's your code)
 - The documentation doesn't say the suffer value *must* be given as hex string; I'd suggest using sscanf with %hhi instead. Then the user can specify 0x80 or 128 or 0200. Neater. In fact, at some point, I plan to review all number input in AVRDUDE and make it so that *everywhere* one can use hex, decimal or octal.
 - Similarly %hhu later on might be too restrictive, too, %hhi might be neater?
 - I would change `( ~PDATA(pgm)->suffer_data[1] & 0x78)` to `(PDATA(pgm)->suffer_data[1] & ~0x87)`: it's easier for me to visualise the valid bits 0x87 than the invalid bits 0x78; also you then don't need the comment (masked out with 0x78 in the code below)
 - A couple of things that I suggest considering solving *en passant* while you are at this
     + Change `matches(` to `str_starts(` in that file for code clarity
     + Add `-xhelp` functionality :wink: I realise it's a bit tricky as the available options depend on `extra_features` 

`stk500v2.c`
 - Similar comments as above

**Comment by stefanrueger** [comment]
Just realised the code wants the reserved bits of the SUFFER value to be set. So my recommendation above is not good. Perhaps, rather than throwing an error, set the bits, eg, to the effect of
```
          if (sscanf(extended_param, "suffer=%hhi", PDATA(pgm)->suffer_data+1) < 1) {
            pmsg_error("invalid -xsuffer=<value> '%s'\n", extended_param);
            rv = -1;
            break;
          }
          if((PDATA(pgm)->suffer_data[1] & 0x78) != 0x78) {
            PDATA(pgm)->suffer_data[1] |= 0x78;
            pmsg_info("setting -xsuffer=0x%02x so that reserved bits 3..6 are set\n",
              PDATA(pgm)->suffer_data[1]);
          }
```
and comment earlier like `// Bits 6..3: Reserved (must be set to 1)`

**Comment by MCUdude** [comment]
> Add -xhelp functionality 😉 I realise it's a bit tricky as the available options depend on extra_features

I don't have time to look into this just yet. The way you implemented this in urclock.c was very neat, and my implementation would probably be much more "hacky" and hard-coded.

**Comment by stefanrueger** [comment]
Thanks - looks great. *Needs thorough testing, though.* I only read the code, don't even know if it compiles. 

One last thing: It looks like your recent update  [6749c36](https://github.com/avrdudes/avrdude/pull/1286/commits/6749c36862276bccefbd86b5329ddfdc4bb10b6c) of the docs has undone @mcuee's PR #1276; please reinstate.

| Make sure that binary input (0b) is also a valid

Of course :smile: I had this in mind, too, poss more :grin:

| [hardcoded -xhelp implementation]

Nothing wrong with that!

You can tell I like tables b/c it makes adding, removing or renaming options easier; but it's swings and roundabouts.

**Comment by MCUdude** [comment]
> One last thing: It looks like your recent update [6749c36](https://github.com/avrdudes/avrdude/pull/1286/commits/6749c36862276bccefbd86b5329ddfdc4bb10b6c) of the docs has undone @mcuee's PR https://github.com/avrdudes/avrdude/pull/1276; please reinstate.

Whoa, I didn't realize that! I've rebased and fixed the issue.

> Add -xhelp functionality 😉 I realise it's a bit tricky as the available options depend on extra_features

Maybe we should leave this outside this PR and handle it separately once we've discussed #1287 a little more?

Anyways, I think this PR is ready for some extensive testing!

**Comment by mcuee** [comment]
@MCUdude 

Just wondering how you reconcile this new feature of Xplained Mini/Nano vs exsiting similar feature of original Atmel STK500v1 and STK500v2. They do have the `Vtarg` command.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude -c avrisp2 -p m328p -qq -t
avrdude> help
Valid commands:
  dump    : dump <memory> [<addr> <len> | <addr> ... | <addr> | ...]
  read    : alias for dump
  write   : write <memory> <addr> <data>[,] {<data>[,]}
          : write <memory> <addr> <len> <data>[,] {<data>[,]} ...
  flush   : synchronise flash & EEPROM writes with the device
  abort   : abort flash & EEPROM writes (reset the r/w cache)
  erase   : perform a chip erase
  pgerase : pgerase <memory> <addr>
  sig     : display device signature bytes
  part    : display the current part information
  send    : send a raw command: send <b1> <b2> <b3> <b4>
  parms   : display adjustable parameters
  vtarg   : set <V[target]>
  varef   : set <V[aref]>
  fosc    : set <oscillator frequency>
  sck     : set <SCK period>
  verbose : change verbosity
  quell   : set quell level for progress bars
  help    : show help message
  ?       : same as help
  quit    : quit after writing out cache for flash & EEPROM
  q       : abbreviation for quit

Note that not all programmer derivatives support all commands. Flash and
EEPROM type memories are normally read and written using a cache via paged
read and write access; the cache is synchronised on quit or flush commands.
The part command displays valid memory types for use with dump and write.

```

**Comment by MCUdude** [comment]
> Just wondering how you reconcile this new feature of Xplained Mini/Nano vs existing similar feature of original Atmel STK500v1 and STK500v2.

It _could_ be added to stk500 and stk500v2 in avrdude.conf as well, but I doubt it would be very useful as it only trying to solve a non-existing problem.

The `stk500v1` and `stk500v2` isn't tied to a programmer like the `xplainedmini` programming option is. `stk500v1` and `stk500v2` _may_ be used with an actual STK500 board, but can also be used with UART-based programmers that implements a v1 or a v2 protocol.

**Comment by mcuee** [comment]
I mis-placed my ATmega328PB Xplained Mini board somewhere. I will need to dig it out for the testing.

**Comment by mcuee** [comment]
Here is the test with ATtiny416 Xplained Nano. It seems to me that `-xvtarg_switch` does not seem to do anything. The ATtiny416 is still blinking the LED even it says "target power is switched off".

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286.conf -c xplainedmini_updi
 -p t416 -xsuffer

                Vtarget         : 5.00 V

SUFFER register value read as 0xff
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9221 (probably t416)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286.conf -c xplainedmini_updi
 -p t416 -xvtarg_switch

                Vtarget         : 5.00 V

Vtarg switch setting read as 0: target power is switched off
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9221 (probably t416)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286.conf -c xplainedmini_updi
 -p t416 -xvtarg_switch=1

                Vtarget         : 5.00 V

Vtarg switch setting changed from 0 to 1
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9221 (probably t416)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286.conf -c xplainedmini_updi
 -p t416 -xvtarg_switch

                Vtarget         : 5.00 V

Vtarg switch setting read as 0: target power is switched off
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9221 (probably t416)

avrdude_pr1286 done.  Thank you.
```

**Comment by mcuee** [comment]
@MCUdude 

One more question, `-c xplainedmini_tpi` does not support the two extended feature, right?

Even if I manually added the following line to the configuration file, it does not work.
```
extra_features         = HAS_SUFFER | HAS_VTARG_SWITCH;
```

**Comment by mcuee** [comment]
I am having problems with the ATmega328PB Xplained Mini under Windows. It seems to me switching off vtarget will have side effect and I need to switch on the target power and then erase the chip to recover.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp
 -patmega328pb -xsuffer

                SUFFER register value read as 0xff
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp
 -patmega328pb -xsuffer=0xfe

                SUFFER register value changed from 0xff to 0xfe
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch

                Vtarg switch setting read as 1: target power is switched on
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp
 -patmega328pb -xvtarg_switch=0

                Vtarg switch setting changed from 1 to 0
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 error: unable to return from debugWIRE to ISP
avrdude_pr1286 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 125kHz
               - use -F to override this check


avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=1

                Vtarg switch setting changed from 0 to 1
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp
 -patmega328pb -e

avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)
avrdude_pr1286: erasing chip

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=1

                Vtarg switch setting changed from 1 to 1
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp
 -patmega328pb -xvtarg_switch

                Vtarg switch setting read as 1: target power is switched on
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=0

                Vtarg switch setting changed from 1 to 0
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 error: unable to return from debugWIRE to ISP
avrdude_pr1286 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 125kHz
               - use -F to override this check


avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp
 -patmega328pb -xsuffer=0xff

                SUFFER register value changed from 0xfe to 0xff
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 error: unable to return from debugWIRE to ISP
avrdude_pr1286 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 125kHz
               - use -F to override this check


avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=1

                Vtarg switch setting changed from 0 to 1
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -e

avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)
avrdude_pr1286: erasing chip

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=1

                Vtarg switch setting changed from 1 to 1
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=0

                Vtarg switch setting changed from 1 to 0
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 error: unable to return from debugWIRE to ISP
avrdude_pr1286 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 125kHz
               - use -F to override this check


avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=1

                Vtarg switch setting changed from 0 to 1
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -e

avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)
avrdude_pr1286: erasing chip

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch

                Vtarg switch setting read as 1: target power is switched on
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

```

**Comment by mcuee** [comment]
> It seems to me switching off vtarget will have side effect and I need to switch on the target power and then erase the chip to recover.

I think "switching off the vtarget" does work but the error messages may be wrong.

1) I program the board with the blining LED sketch.

2) With the following command, I can see the LED stops blinking, even with all the error messages.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=0

                Vtarg switch setting changed from 1 to 0
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 error: unable to return from debugWIRE to ISP
avrdude_pr1286 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 125kHz
               - use -F to override this check


avrdude_pr1286 done.  Thank you.

3) Switching on the vtarget will work (no need to erase the chip) even though there is a warning message the first time.

````
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch=1

                Vtarg switch setting changed from 0 to 1
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1286 -C .\avrdude_pr1286_mod.conf -cxplainedmini_isp -patmega328pb -xvtarg_switch

                Vtarg switch setting read as 1: target power is switched on
avrdude_pr1286: AVR device initialized and ready to accept instructions
avrdude_pr1286: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1286 done.  Thank you.

```

**Comment by MCUdude** [comment]
> I think "switching off the vtarget" does work but the error messages may be wrong.
I program the board with the blinking LED sketch.
With the following command, I can see the LED stops blinking, even with all the error messages.

The error messages are to be expected. The programmer turns off the power before it's trying to communicate with the target. No wonder there are error messages!

> Switching on the vtarget will work (no need to erase the chip) even though there is a warning message the first time.

I think this is to be expected as well.

**Comment by MCUdude** [comment]
> Here is the test with ATtiny416 Xplained Nano. It seems to me that -xvtarg_switch does not seem to do anything. The ATtiny416 is still blinking the LED even it says "target power is switched off".

Only *Xplained Mini* boards have a target power switch. The Xplained Nano doesn't have this.

> One more question, -c xplainedmini_tpi does not support the two extended feature, right?

Correct. There's no SUFFER register, and there's no target power switch on the Xplained Nano TPI

**Comment by mcuee** [comment]
> The error messages are to be expected. The programmer turns off the power before it's trying to communicate with the target. No wonder there are error messages!

@MCUdude 

Just wondering if it is possible to improve the error message to ask the user to check whether the power is turned off or not.

The current error message is not so helpful.
```
avrdude_pr1286 error: command failed
avrdude_pr1286 error: device is locked; chip erase required to unlock
avrdude_pr1286 warning: target prepared for ISP, signed off
               now retrying without power-cycling the target
```

**Comment by MCUdude** [comment]
@mcuee how about returning -1 in the initialization function if the target power switch is turned off? There's still an error message present, but not as verbose:

```diff
diff --git a/src/stk500v2.c b/src/stk500v2.c
index f8d6680..ebc25f1 100644
--- a/src/stk500v2.c
+++ b/src/stk500v2.c
@@ -1342,6 +1342,10 @@ static int stk500v2_jtag3_initialize(const PROGRAMMER *pgm, const AVRPART *p) {
       if (jtag3_setparm(pgmcp, SCOPE_EDBG, EDBG_CTXT_CONTROL, EDBG_CONTROL_TARGET_POWER, PDATA(pgm)->vtarg_switch_data+1, 1) < 0)
         return -1;
       imsg_info("Vtarg switch setting changed from %u to %u\n", PDATA(pgm)->vtarg_switch_data[0], PDATA(pgm)->vtarg_switch_data[1]);
+
+      if (PDATA(pgm)->vtarg_switch_data[1] == 0) {
+        return -1;
+      }
     }
   }
```

```
$ ./avrdude -cxplainedmini -patmega328pb -xvtarg_switch=0

         Vtarg switch setting changed from 0 to 0
avrdude error: initialization failed, rc=-1
        - double check the connections and try again
        - use -B to set lower ISP clock frequency, e.g. -B 125kHz
        - use -F to override this check


avrdude done.  Thank you.
```

**Comment by mcuee** [comment]
@MCUdude 

Somehow I feel the error message is still confusing. Why not inform the user something llike the following.
`Vtarg is off, please turn on Vtarg in order to carry out relevant avrude operation`.

**Comment by MCUdude** [comment]
@mcuee I've just pushed a commit where I've added an improved info message if the target power switch is set to zero:

```
$ ./avrdude -cxplainedmini -patmega328pb -xvtarg_switch=0

         Vtarg switch setting changed from 1 to 0
         Turn on the Vtarg switch to establish connection with the target

avrdude error: initialization failed, rc=-1
        - double check the connections and try again
        - use -B to set lower ISP clock frequency, e.g. -B 125kHz
        - use -F to override this check


avrdude done.  Thank you.
```

**Comment by mcuee** [comment]
@MCUdude 

Thanks for the updates. Now I am fine with this PR.

**Review by mcuee — APPROVED** [review]
Tested to be good.

**Comment by stefanrueger** [comment]
OK, as an advance warning, will merge this PR in the coming days.

**Pull request merged**
