### PR TITLE
Add serial_drain() to updi_physical_send_double_break().

### PR DESCRIPTION
**Pull request by dl8dtl**
This is needed here on FreeBSD.

### CODE REVIEW

**Comment by dbuchwald** [comment]
Do you realize that this is the final fix for SerialUPDI I completed today? Hahahaha :)

**Comment by dl8dtl** [comment]
So, you say, I can just drop this PR, and use your one instead?

Will give that a try tonight.

**Comment by dbuchwald** [comment]
Yeah, I think you can use my PR instead, it has two more changes which are required for PL2303HX operation (increased timeout and replacement of "double break" by single fast break at the beginning).

You have to tell me one day how did you come up with the idea of missing `serial_drain` there - it was actually pretty nasty bug!

**Comment by dl8dtl** [comment]
> You have to tell me one day how did you come up with the idea of missing `serial_drain` there - it was actually pretty nasty bug!

I can't remember anymore. Probably trial & error.

**Pull request closed without merging**
