### PR TITLE
Handle invalid -U file format specifiers for input

### PR DESCRIPTION
**Pull request by dl8dtl**
The file format specifiers 'h', 'd', 'o', and 'b' are only valid for
outputting data. Reject them with a proper error message when
attempting to use them for input.

Supposed to fix issue #1041

### CODE REVIEW

**Comment by stefanrueger** [comment]
Does that not need to be considered for device verify as well (also file read)?

Can I suggest changing fileio.c instead of update.c. I think the misleading error message comes from 
https://github.com/avrdudes/avrdude/blob/affe4cb50a42c34a873be9bde8b5e650032cdcb5/src/fileio.c#L1278-L1285
Changing the error message to the effect of file read with formats `:d`, `:h`, `:o`, `:b` not supported would do the trick. Also, if someone were to implement the file read for these formats they'd do it here and needn't worry about update.c

**Comment by dl8dtl** [comment]
> Does that not need to be considered for device verify as well (also file read)?
> 

Prpbably, yes.

> Can I suggest changing fileio.c instead of update.c.

The corresponding message for write attempts to 'm' was already there, so I did about the same.

But we could also move everything to fileio.c.

**Comment by dl8dtl** [comment]
OK, I moved all checks to `fileio.c`.

**Review by stefanrueger — APPROVED** [review]
Perfect - good to go.

**Review by stefanrueger — CHANGES_REQUESTED** [review]
I just realised that the check for `FMT_IMM` actually better be kept in `update.c`:
  - Write immediate is *impossible* (same reason why there is no `sti` assembler command)
  -  Check in `update.c` is earliest possible and prevents the memories from being read (and then not being able to write which was known before)

It is definitely good to *also* check for `FMT_IMM` in `fileio.c` considering the desired future library nature of the code (which might be called independent of update code).

It is good that the :h, :d, ... format checks happen in `fileio.c` and not in`update.c` as it is the *current* implementation in fileio.c that does not allow reading these formats (there is nothing in principle that prevents this from happening, and update should be oblivious of this).

The single suggested change to the current PR is to keep `src/update.c` as it was.

**Review by stefanrueger — APPROVED** [review]

**Pull request merged**
