### PR TITLE
README Rework

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
combined

---

Before I get to the README I'd like to suggest:

To change the repository description 
to something more readable like:

```
Up- / Downloads and Manipulates ROMs and EEPROMs of AVR Microcontrollers.
```

Which nicely fits into `2` lines instead of `4` while 
still  maintaining the same amount of information.

The projects name is *'missing'* but considering that 
any preview with this description will have **AVRDUDE**
plastered above it, should make this a non-issue.

---

Second I would like to suggest the addition of project
tags, such as `programmer`, `avr`, `utility`, ..

---

To the README, I did the usual formatting:

- Separation of content & links
- Dedicated files for topics ( `Installation`, `Usage` )

  *Could later be integrated into the wiki if desired*

- Formatting / Refactoring
- More links

### CODE REVIEW

**Comment by mariusgreuel** [comment]
> change the repository description to something more readable like

Not sure whether you suggestion is more readable. The description is still the original headline, which I agree is something verbose.

If something shorter is required, how about the Savannah description: "AVRDUDE is software for programming Microchip (former Atmel) AVR microcontrollers". We could potentially shorten it to "AVRDUDE is software for programming Microchip AVR microcontrollers" or just "AVRDUDE is software for programming AVR microcontrollers"

@dl8dtl, @bd34n  : Any preference?

> Second I would like to suggest the addition of project

Added.

> To the README, I did the usual formatting

I think I'd rather keep the readme in one piece because it is easier to maintain.

Also, we are planning on reworking the documentation, I created a separate issue for that: #840

**Comment by mariusgreuel** [comment]
I like the old README better.

**Comment by ElectronicsArchiver** [comment]
I was hoping for a more objective critique,
not flat out denial based on personal preference.

*I added a preview of the changes to the*
*original comment to visualize the changes.*

Are there any other maintainers willing to voice 
their hopefully more constructive thoughts?

**Comment by dl8dtl** [comment]
> I was hoping for a more objective critique, not flat out denial based on personal preference.
> 
> _I added a preview of the changes to_ _the original comment to visualize them._
> 
> Are there any other maintainers willing to voice their hopefully more constructive thoughts?

Opinions are always personal things.

Frankly, looking at your comparison, I'm not happy with both of them. ;-)

Adding a list of features in the "front page" makes sense. It's better than just throwing in installation instructions there. However, I think there's quite a bit more to tell about it. As I've been around straight from the beginning, I could work on that one though.

Telling about history at such a prominent place seems like "Grandpa's telling about war" though. I feel the installation instructions are more important then. After all, to the reader, once he likes the features he's been presented, next he doesn't want to know what happened 20 years ago, but very much, he'd like to know how to get it then. Besides, AVRDUDE's history dates back to August 2000, according to the old ChangeLog files. (It wasn't opensourced yet at that point though, that happened a bit later.)

@mariusgreuel I agree with using a simple headline like the one from Savannah, I'm neutral about which of the three forms. Maybe it's best to omit the company name, so we are ready for the future in case someone buys Microchip next. :-)

**Comment by mariusgreuel** [comment]
> I was hoping for a more objective critique, not flat out denial based on personal preference.

Since the PR is mostly about style, and not about contents, I think it is appropriate to voice a preference. I put the current and your proposal side by side and compared them visually, and I just like the current style better.

Let me give you some feedback on some technical issues:

- The look and feel of the repository README pages (and the overall site) has been defined by GitHub. I prefer not to change the style and visuals by adding extra HTML code, UI elements such as **⸢ link ⸥**, or even extra spacing or newlines. If visual changes are required, the proper way to do this would be centrally via a style sheet, and not by adding extra code to the individual pages (here README).
- The extra line breaks \<br/><br/> literally break responsive web sites such as GitHub. For instance, check out how poorly the README is rendered on a smartphone.
- ***I*** prefer to **not** use *emphasis* unless it aids the **`visual representation`**. IMHO, excessive use of formatting distracts from the contents and thus should use sparsely for technical documentation.
- The documentation is easier to maintain if we keep the current format. It is intentionally kept simple so that people do not have a high learning curve when editing the README.
- For a consistent look and feel across GitHub we should not deviate from the default style as defined by GitHub.

I appreciate your work, but at this time I am not planning on changing the style of the README. You are welcome to send PRs if you want to contribute to the contents, even for little things such as spelling mistakes.

iPhone SE

**Comment by mariusgreuel** [comment]
> I agree with using a simple headline like the one from Savannah

So I changed

`AVRDUDE is a utility to download/upload/manipulate the ROM and EEPROM contents of AVR microcontrollers`

to 

`AVRDUDE is a utility to program AVR microcontrollers`

How does that look like?

**Comment by bd34n** [comment]
On the current readme, it seems fine - again, as several have mentioned, style is personal preference. The current readme pretty concisely says:

1. What it is - with a tiny bit of detail on some features
2. A one-liner on authors and contributors
3. Where to get the latest version
4. (very) Quick starts for various platforms
5. A couple of quick usage examples
6. Link to more detail docs

Seems pretty short, concise, and to the point - without much fluff to me. It's what I would want to see if I came across it with little or no prior knowledge of it.

**Comment by dl8dtl** [comment]
> How does that look like?

Fine with me.

**Comment by ElectronicsArchiver** [comment]
Thank you Mr. Wunsch for the refreshing perspective.

---

To the mobile comparability, I can't say I agree.
Considering the wide range of mobile devices,
styling with markdown will never result in a 
proper design in the first place.

The only thing people do is just go with inline
and have their text be spun upon dozens of lines.

In the first place I wouldn't think of mobile users
as a relevant demographic to consider in the case
of development work.

Limiting your toolbox dramatically to correct
for a small subset of the userbase doesn't
seem sensible to me.

---

Thanks for the update on the repo description.

---

> the proper way to do this would be centrally via a style sheet

I would like to hear how you would accomplish
that, considering that those are only available
to **Github Pages** and I don't think there is
a way to replace the default README.md with
a html page, at least not for the `.com` page,
which would mean you'd still need a markdown
file that isn't synced to the stylesheet. 

---

> You are welcome to send PRs if you want to contribute to the contents, even for little things such as spelling mistakes.

Sure, how about some formatting for the `AUTHORS` & `NEWS` files?

**Pull request closed without merging**
