### PR TITLE
Support UPDI EEPROM write

### LINKED ISSUE #1128: jtag2updi and serialupdi EEPROM write issue
Ref: https://github.com/avrdudes/avrdude/pull/1121#issuecomment-1278056109

From @MCUdude 

<html>
<body>

JTAG2UPDI | ATmega4808 | AVR128DA32
-- | -- | --
Read from EEPROM (-U) | ✅ | ✅
Write to EEPROM (-U) | ❗️Writes content but erasesthe EEPROM page first, resulting in data loss | ❌
Read from EEPROM (-t) | ✅ | ✅
Write to EEPROM (-t) | ✅ | ✅

</body>
</html>

<html>
<body>

SerialUPDI | ATmega4808 | AVR128DA32
-- | -- | --
Read from EEPROM (-U) | ✅ | ✅
Write to EEPROM (-U) | ❗️Writes content but erasesthe EEPROM page first, resulting in data loss | ✅
Read from EEPROM (-t) | ✅ | ✅
Write to EEPROM (-t) | ✅ | ✅

</body>
</html>

### PR DESCRIPTION
**Pull request by stefanrueger**
Supposed to fix #1128 

@llinjupt @mcuee Could you give this a try?

### CODE REVIEW

**Comment by mcuee** [comment]
Yes I will try this over the weekend.

**Comment by mcuee** [comment]
@MCUdude 
You may want to give it a try as well.

**Comment by mcuee** [comment]
The following simple test shows this PR is good.

```
MINGW64 /c/work/avr/avrdude_test/avrdude_sr/build_mingw64_nt-10.0-22621/src
$ git branch --show-current
updi-eeprom

$ echo "Hello World" | ./avrdude -cjtag2updi -PCOM12 -pavr128db48 -Ueeprom:w:-:r

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e970c (probably avr128db48)
avrdude: reading input file <stdin> for eeprom
         with 12 bytes in 1 section within [0, 11]
avrdude: writing 12 bytes eeprom ...

Writing | ################################################## | 100% 0.14 s

avrdude: 12 bytes of eeprom written
avrdude: verifying eeprom memory against <stdin>

Reading | ################################################## | 100% 0.34 s

avrdude: 12 bytes of eeprom verified

avrdude done.  Thank you.

$ echo "dump eeprom 0 0x40" | ./avrdude -cjtag2updi -PCOM12 -pavr128db48 -qqt
avrdude> dump eeprom 0 0x40
0000  48 65 6c 6c 6f 20 57 6f  72 6c 64 0a 6d 70 6c 65  |Hello World mple|
0010  74 74 20 76 65 72 77 61  68 72 6c 6f 73 74 65 6e  |tt verwahrlosten|
0020  20 54 61 78 69 20 71 75  65 72 20 64 75 72 63 68  | Taxi quer durch|
0030  20 42 61 79 65 72 6e 0a  5a 20 6a 61 67 74 20 69  | Bayern Z jagt i|

avrdude>

```

**Comment by stefanrueger** [comment]
> following simple test shows this PR is good

Thanks @mcuee! Amazing that such a simple change has now made jtag2updi work for EEPROM write. Thanks @llinjupt for finding that. Could you and/or @MCUdude do independent checks? I'll earmark this for the next mergefest.

**Comment by llinjupt** [comment]
> Thanks @mcuee! Amazing that such a simple change has now made jtag2updi work for EEPROM write. Thanks @llinjupt for 
> finding that. Could you and/or @MCUdude do independent checks? I'll earmark this for the next mergefest.

@stefanrueger , the patch's good to me.

**Comment by stefanrueger** [comment]
> set page_size = 2/4/8/16 for Dx series

avrdude.conf tends to describe a part as in the data sheet

>  to speed up EEPROM writing

Is that a thing? How big is EEPROM and how big is the time saving? If there is a case for speeding up EEPROM write, perhaps best to change the code base and issue a PR?

**Comment by llinjupt** [comment]
> Is that a thing? How big is EEPROM and how big is the time saving? If there is a case for speeding up EEPROM write, perhaps best to change the code base and issue a PR?

It's not in the spec/datasheet, but it does work, I mention it for others to save time.

**Comment by stefanrueger** [comment]
| to save time

Do you have numbers? Would be interesting to see if the effect is substantial and/or worthwhile

**Comment by llinjupt** [comment]
> Do you have numbers? Would be interesting to see if the effect is substantial and/or worthwhile

@stefanrueger 

Default:

```
$ ./avrdude.exe -c jtag2updi -P COM177 -p avr128da48 -U eeprom:w:eeprom.bin:r

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9708 (probably avr128da48)
avrdude: reading input file eeprom.bin for eeprom
         with 512 bytes in 1 section within [0, 0x1ff]
avrdude: writing 512 bytes eeprom ...

Writing | ################################################## | 100% 8.17s

avrdude: 512 bytes of eeprom written
avrdude: verifying eeprom memory against eeprom.bin

Reading | ################################################## | 100% 1.66s

avrdude: 512 bytes of eeprom verified

avrdude done.  Thank you.
```

With page_size=16:

```
Red@DESKTOP-GI4UT7C MINGW64 /f/avrdude.git.main/build_mingw64_nt-10.0-17134/src
$ ./avrdude.exe -c jtag2updi -P COM177 -p avr128da48 -U eeprom:w:eeprom.bin:r

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9708 (probably avr128da48)
avrdude: reading input file eeprom.bin for eeprom
         with 512 bytes in 1 section within [0, 0x1ff]
         using 32 pages and 0 pad bytes
avrdude: writing 512 bytes eeprom ...

Writing | ################################################## | 100% 5.42s

avrdude: 512 bytes of eeprom written
avrdude: verifying eeprom memory against eeprom.bin

Reading | ################################################## | 100% 0.48s

avrdude: 512 bytes of eeprom verified

avrdude done.  Thank you.

```

**Comment by stefanrueger** [comment]
@llinjupt OK, if you want to pursue this here is what needed doing. Test *all* updi programmers whether they cope with paged EEPROM read/write for DX-parts:
``` bash
$ avrdude -c*/At | grep prog_modes.PM_UPDI
.prog	serialupdi	prog_modes	PM_UPDI
.prog	jtag3updi	prog_modes	PM_UPDI
.prog	xplainedpro_updi	prog_modes	PM_UPDI
.prog	xplainedmini_updi	prog_modes	PM_UPDI
.prog	atmelice_updi	prog_modes	PM_UPDI
.prog	powerdebugger_updi	prog_modes	PM_UPDI
.prog	pickit4_updi	prog_modes	PM_UPDI
.prog	snap_updi	prog_modes	PM_UPDI
.prog	pkobn_updi	prog_modes	PM_UPDI
.prog	jtag2updi	prog_modes	PM_UPDI
```
If so, *then* identify *all* the places in the code base where the decision for calling paged vs byte access is made and modify the `page_size > 1` test to `part_is_dx() || page_size > 1` or something to that effect.

I have no doubt that setting page_size for DX-part EEPROM memories works in your case but we need to guard against unwanted side effects for other programmers.

**Comment by mcuee** [comment]
@stefanrueger 
I think this PR is good to go.

Further improvements for EEPROM can be dealt with another PR.

**Pull request merged**
