### PR TITLE
WIP: Add EP guesswork heuristics for jtagmkII and stk500v2 devices

### LINKED ISSUE #321: [bug #40831] LUFA AVRISP-MKII fails with avrdude 6.0.1
Larry Viesse <None>
Sat 07 Dec 2013 03:10:06 AM UTC

The problem was found in usbdev_open in file usb_libusb.c.

The if statement:

```
if (fd->usb.rep) == 0)
{

```
prevents Dean's LUFA masqueraded endpoint from being discovered.

See full details at: [http://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&t=138424&start=0&postdays=0&postorder=asc&highlight](https://savannah.nongnu.orghttp://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&t=138424&start=0&postdays=0&postorder=asc&highlight)=

specifically in this post: [http://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&p=1119592#1119592](https://savannah.nongnu.orghttp://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&p=1119592#1119592)

Thanks for providing us with this awesome software.

[file #32171: endpointdetect_pass1.patch](https://savannah.nongnu.org/bugs/download.php?file_id=32171)

This issue was migrated from https://savannah.nongnu.org/bugs/?40831

### PR DESCRIPTION
**Pull request by yegorich**
The read and write endpoints need to be guessed for the LUFA firmware.
As the EPs are already pre-filled for the known tools, this patch clears
these entries and lets the `usb_libusb.c` making the guess work and assigning
the proper EPs.

Fixes #321

### CODE REVIEW

**Comment by mariusgreuel** [comment]
Can you please wait merging this PR? I would like to run some tests on Windows, I have a hunch that this patch won't work with WinUSB.

**Comment by dl8dtl** [comment]
> Can you please wait merging this PR? I would like to run some tests on Windows, I have a hunch that this patch won't work with WinUSB.

I marked it WIP and added you as reviewer.

**Comment by mariusgreuel** [comment]
I have not read up on all the postings, but I do have a question:

The heuristic just seems to loop over the endpoints in the config descriptor and grabs the first IN and OUT endpoint. Is that what Atmel is doing? The fact that the LUFA firmware claims to support Atmel Studio seems to support that. But obviously that scheme is a little shaky (perhaps we should look for bulk EPs), and may break other firmware that have an additional endpoint before the configured endpoint.

I can see Deans dilemma that the mkII has a bi-directional endpoint at address 2 ?!

**Comment by yegorich** [comment]
I'm quite new to the whole libusb subject. My goal was to renew the issue discussion and find an appropriate solution. So far, I have made the test only under Linux. I have two [AVR-ISP-MK2](https://www.olimex.com/Products/AVR/Programmers/AVR-ISP-MK2/open-source-hardware) devices, each with different FW inside. Let me know if you need any debug outputs.

**Comment by yegorich** [comment]
@mariusgreuel let's close it. I'll test the new LUFA firmware.

**Pull request closed without merging**
