### PR TITLE
Add a fixed delay for AVR Dragon and Arduino Nano Every on port close

### LINKED ISSUE #1632: Some programmers need a delay between successive AVRDUDE calls
The new brilliant [test script](https://github.com/MCUdude/avrdude-test-script) has uncovered that some programmers [need a delay between avrdude calls](https://github.com/avrdudes/avrdude/discussions/1473#discussioncomment-8061916). We should identify a list of these programmers, determine the appropriate delay and add a `sleep(...);` into the *programmer*_close()` routine.

Please @mcuee, @MCUdude identify these instances by using `avrdude_test_script.sh -d0 ...` (no delay in the test suite), determine the needed delay and issue suitable PRs.

### PR DESCRIPTION
**Pull request by MCUdude**
Closes #1632

### CODE REVIEW

**Comment by MCUdude** [comment]
Works well with the Dragon, which was the one that required the longest delay:

```
Prepare "-c dragon_isp -patmega165" and press 'enter' or 'space' to continue. Press any other key to skip
✅   3.304 s: clear, set and read eesave fuse bit
✅   3.084 s: set eesave fusebit to factory default: delete EEPROM on chip erase
✅  12.160 s: holes_rjmp_loops_16384B.hex flash -U write/verify
✅   7.419 s: holes_rjmp_loops_16384B.hex flash -T write/verify
✅   9.946 s: holes_pack_my_box_512B.hex eeprom -U write/verify
✅  13.639 s: holes_the_five_boxing_wizards_512B.hex eeprom -T write/verify
✅   7.753 s: chip erase and spot check flash is erased
✅   6.816 s: ... and spot check eeprom is erased
```

The Nano Every fails a test, but this isn't because of this PR. It is because the eesave bit is opposite on the ATmega4809
```
Prepare "-c nanoevery -patmega4809 -r -P /dev/cu.usbmodem14101" and press 'enter' or 'space' to continue. Press any other key to skip
✅   3.434 s: clear, set and read eesave fuse bit
✅   3.412 s: set eesave fusebit to factory default: delete EEPROM on chip erase
✅  13.780 s: holes_rjmp_loops_49152B.hex flash -U write/verify
✅   4.714 s: holes_rjmp_loops_49152B.hex flash -T write/verify
✅   3.536 s: holes_pack_my_box_256B.hex eeprom -U write/verify
✅   3.525 s: holes_the_five_boxing_wizards_256B.hex eeprom -T write/verify
✅   4.883 s: chip erase and spot check flash is erased
❌   3.403 s: ... and spot check eeprom is erased (failed command below)
$ avrdude -qq -c nanoevery -patmega4809 -r -P /dev/cu.usbmodem14101 -l /tmp/test-avrdude.log.lKketa -Ueeprom:v:test_files/holes_0xff_256B.hex
✅   3.556 s: random_data_64B.bin usersig -T/-U write/read

$ avrdude -c dryrun -patmega4809 -T 'c'
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9651 (probably m4809)

avrdude: processing -T c
config wdtperiod=t_off # 0
config wdtwindow=t_off # 0
config bodsleep=bod_disabled # 0
config bodactive=bod_disabled # 0
config bodsampfreq=bod_1khz # 0
config bodlevel=bod_1v8 # 0
config freqsel=fcpu_20mhz # 2
config osclock=olock_disabled # 0
config eesave=eex_erased # 0
config rstpincfg=gpio # 0
config crcsrc=nocrc # 3
config sut=sut_64ms # 7
config append=0 # 0
config bootend=0 # 0
config lb=nolock # 197

avrdude done.  Thank you.

$ avrdude -c dryrun -patmega165 -T 'c'
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9407 (probably m165)

avrdude: processing -T c
config sut_cksel=intrcosc_6ck_65ms # 34
config ckout=co_disabled # 1
config ckdiv8=by_8 # 0
config bootrst=application # 1
config bootsz=bs_1024w # 0
config eesave=ee_erased # 1
config wdton=wdt_programmable # 1
config spien=isp_enabled # 0
config jtagen=jtag_enabled # 0
config ocden=ocd_disabled # 1
config rstdisbl=external_reset # 1
config bodlevel=bod_disabled # 7
config lb=no_lock # 3
config blb0=no_lock_in_app # 3
config blb1=no_lock_in_boot # 3

avrdude done.  Thank you.

```

**Comment by mcuee** [comment]
> The Nano Every fails a test, but this isn't because of this PR. It is because the eesave bit is opposite on the ATmega4809

@stefanrueger and @MCUdude 
Can we fix the script for similar parts?

**Comment by mcuee** [comment]
@MCUdude 

I will carry out the tests as well usng my Nano Every and AVR Dragon later today or tomorrow.

**Comment by stefanrueger** [comment]
Thanks! Looks good. 

> The Nano Every fails a test, but this isn't because of this PR. It is because the eesave bit is opposite on the ATmega4809

Hmm. I had put in a command to ensure the eesave bit is set to erase EEPROM on CE regardless the

**Comment by stefanrueger** [comment]
(Opps ... closed PR by accidentally coming near the touchpad.)

... regardless the part. Makes me wonder whether my (perhaps too convoluted) attempt to do so is working. I have simplified that now in git avrdude main. Can you please re-run with the tools/test-avrdude from the avrdude repo?

**Comment by stefanrueger** [comment]
@MCUdude OK, seeing that with this PR avrdude sleeps at he _close() function and that test-avrdude is part of the AVRDUDE repo, would it make sense to change the default delay from 4 s to 0 s in this PR? You may need to catch up the recent commits in git main before doing so. Changing that line
https://github.com/avrdudes/avrdude/blob/742cb9dd77d83b51e877bb72736d97ccef843792/tools/test-avrdude#L11
should do the trick.

Speaking of sleeps, I wonder whether the following is needed
https://github.com/avrdudes/avrdude/blob/742cb9dd77d83b51e877bb72736d97ccef843792/tools/test-avrdude#L158

The following bash dryrun/dryboot test
```
#/bin/bash

for p in $(avrdude -p\*/d | grep PM_SPM | cut -d"'" -f2); do
  echo | tools/test-avrdude -d0 -p"-cdryboot -p$p"
done

for p in $(avrdude -p\*/d |  grep -v PM_aWire | cut -d"'" -f2); do
  echo | tools/test-avrdude -d0 -p"-cdryrun -p$p"
done
```

works on my linux machine and carries out 677 test-avrdude invocations with 5878 avrdude calls; it lasts 14 mins on my (old) laptop. Could be 11 mins and a bit if the sleep 0.25 was removed.

**Comment by MCUdude** [comment]
> I have simplified that now in git avrdude main. Can you please re-run with the tools/test-avrdude from the avrdude repo?

Sure! I'll do it when I'm back home.

> Speaking of sleeps, I wonder whether the following is needed [sleep 0.25]?

Not really, it was just a very crude "debounce" if the programmer wasn't detected and the next command was executed before I had the chance to release the key. I'm sure it can be removed or at least reduced.

> would it make sense to change the default delay from 4 s to 0 s in this PR?

Yes, but we should test the following bootloaders first, to ensure that these have the appropriate delay if needed.

* Catarina, `avr109` (Arduino Leonardo/Micro/Pro Micro)
* Xboot, `avr109`
* Optiboot, `stk500v1`
* Urboot, `urclock`
* Wiring, `stk500v2`

I have limited time today, but maybe @mcuee can help?

**Comment by mcuee** [comment]
> Yes, but we should test the following bootloaders first, to ensure that these have the appropriate delay if needed.
> 
> * Catarina, `avr109` (Arduino Leonardo/Micro/Pro Micro)
> * Xboot, `avr109`
> * Optiboot, `stk500v1`
> * Urboot, `urclock`
> * Wiring, `stk500v2`
> 
> I have limited time today, but maybe @mcuee can help?

I will carry out the test except `Xboot`, either today or tomorrow.

**Comment by stefanrueger** [comment]
> Optiboot, stk500v1

Optiboot with `-c arduino` adds an extra 200 ms *before* anything happens by using 250 ms delay as opposed to 50 ms in open() ; I suspect that was originally to facilitate successive avrdude calls and therefore won't need an extra delay.

**Comment by mcuee** [comment]
@MCUdude 

Yes this PR works with Arduino Nano Every. I can use `-d 0` now. Take note I am using the updated script from git main.

The last error is a known script issue under MSYS2 Windows with regard to `/dev/shm`, not an issue with this PR.

```
MINGW64 /c/work/avr/avrdude_test/avrdude_main/tools
$ ./test-avrdude -e "./avrdude_pr1647.exe" -c "-C ./avrdude_pr1647.conf" -d 0 -p "-c nanoevery -p m4809 -P COM5 -r"
Testing ./avrdude_pr1647.exe version 7.2-20240129 (f3ca6958)
Prepare "-c nanoevery -p m4809 -P COM5 -r" and press 'enter' or 'space' to continue. Press any other key to skip
✅   3.976 s: fuse access: clear, set and read eesave fuse bit
✅   3.972 s: fuse access: set eesave fusebit to delete EEPROM on chip erase
✅   4.104 s: chip erase
✅  11.788 s: flash -U write/verify holes_rjmp_loops_49152B.hex
✅   5.492 s: flash -T write/verify holes_rjmp_loops_49152B.hex
✅   4.119 s: eeprom check whether programmer can flip 0s to 1s
✅   4.139 s: eeprom -U write/verify holes_pack_my_box_256B.hex
✅   4.253 s: eeprom -T write/verify holes_{the_five_boxing_wizards,pack_my_box}_256B.hex
✅   5.657 s: chip erase and spot check flash is actually erased
✅   3.988 s: spot check eeprom is erased, too
❌   3.991 s: usersig -T/-U write/read random_data_64B.bin (failed command below)
$ ./avrdude_pr1647.exe -C ./avrdude_pr1647.conf -qq -c nanoevery -p m4809 -P COM5 -r -l /dev/shm/test-avrdude.log.Ic8FW8 -T "erase usersig; write usersig ./test_files/random_data_64B.bin" -T flush -U usersig:r:/dev/shm/usersig_dump2237_64B.bin:r -U usersig:v:/dev/shm/usersig_dump2237_64B.bin:r -T "erase usersig" -T flush -U usersig:v:./test_files/0xff_64B.hex:i

One or more AVRDUDE "-c nanoevery -p m4809 -P COM5 -r" tests failed. Do you want to retry this particular test? (y/n): n

$ ./avrdude_pr1647.exe -C ./avrdude_pr1647.conf -c nanoevery -p m4809 -P COM5 -r -l /dev/shm/test-avrdude.log.Ic8FW8 -T "erase usersig; write usersig ./test_files/random_data_64B.bin" -T flush -U usersig:r:/tmp/usersig_dump2237_64B.bin:r -U usersig:v:/tmp/usersig_dump2237_64B.bin:r -T "erase usersig" -T flush -U usersig:v:./test_files/0xff_64B.hex:i

$ cat /dev/shm/test-avrdude.log.Ic8FW8
avrdude_pr1647: touching serial port COM5 at 1200 baud
avrdude_pr1647: waiting for new port... using same port COM5
avrdude_pr1647: AVR device initialized and ready to accept instructions
avrdude_pr1647: device signature = 0x1e9651 (probably m4809)

avrdude_pr1647: processing -T erase usersig; write usersig ./test_files/random_data_64B.bin
Caching | ################################################## | 100% 0.02s
Caching | ################################################## | 100% 0.00s

avrdude_pr1647: processing -T flush

avrdude_pr1647: processing -U usersig:r:/tmp/usersig_dump2237_64B.bin:r
avrdude_pr1647: reading userrow/usersig memory ...
Reading | ################################################## | 100% 0.02s
avrdude_pr1647: writing output file /tmp/usersig_dump2237_64B.bin

avrdude_pr1647: processing -U usersig:v:/tmp/usersig_dump2237_64B.bin:r
avrdude_pr1647: verifying userrow/usersig memory against /tmp/usersig_dump2237_64B.bin
Reading | ################################################## | 100% 0.02s
avrdude_pr1647: 64 bytes of userrow/usersig verified

avrdude_pr1647: processing -T erase usersig
Caching | ################################################## | 100% 0.00s

avrdude_pr1647: processing -T flush
avrdude_pr1647: synching cache to device ... done

avrdude_pr1647: processing -U usersig:v:./test_files/0xff_64B.hex:i
avrdude_pr1647: verifying userrow/usersig memory against ./test_files/0xff_64B.hex
Reading | ################################################## | 100% 0.02s
avrdude_pr1647: 64 bytes of userrow/usersig verified

avrdude_pr1647 done.  Thank you.
```

**Comment by mcuee** [comment]
@stefanrueger and @MCUdude

> I believe this PR is okay even though I have not tested with AVR Dragon yet. I will try to test it tomorrow.

git main is fine with `-d 0` using AVR Dragon.

```
$ ./test-avrdude -e "./avrdude.exe" -d 0 -t . -p "-c dragon_isp -p m328p"
Testing ./avrdude.exe version 7.2-20240131 (5684b85f)
Prepare "-c dragon_isp -p m328p" and press 'enter' or 'space' to continue. Press any other key to skip
✅   2.698 s: fuse access: clear, set and read eesave fuse bit
✅   2.508 s: fuse access: set eesave fusebit to delete EEPROM on chip erase
✅   2.462 s: chip erase
✅  12.312 s: flash -U write/verify holes_rjmp_loops_32768B.hex
✅   7.200 s: flash -T write/verify holes_rjmp_loops_32768B.hex
✅   3.040 s: eeprom check whether programmer can flip 0s to 1s
✅  15.461 s: eeprom -U write/verify holes_pack_my_box_1024B.hex
✅  34.442 s: eeprom -T write/verify holes_{the_five_boxing_wizards,pack_my_box}_1024B.hex
✅   7.252 s: chip erase and spot check flash is actually erased
✅   8.819 s: spot check eeprom is erased, too
```

**Pull request merged**
