### PR TITLE
Added missing RTS/DTR management feature to serialupdi programmer

### PR DESCRIPTION
**Pull request by dbuchwald**
Hello, this PR contains all the additional changes to SerialUPDI programmer, enabling forcing DTR/RTS lines low/high during UPDI programming session. This could be used by dedicated hardware to indicate UPDI operation.
Documentation about extra parameters has also been updated.

### CODE REVIEW

**Comment by mariusgreuel** [comment]
Don't mind the failed msvc builds. Chocolatey seems to have issues (again!)...

**Comment by MCUdude** [comment]
@dbuchwald there are some tabs in serialupdi.c that probably should be replaced by spaces. Other than this, I've tested it and it's working perfectly. Thank you!

https://github.com/avrdudes/avrdude/pull/811/files#diff-79a97a0f99f34b4d18cc664ce2536146c0821315fdbe772add729526f1087c7bR948-R958

**Comment by dbuchwald** [comment]
Done. Sorry for the delay, got infected with COVID-19 and spent last couple of days on the edge of reality. Seems like I might be coming back though.

**Comment by MCUdude** [comment]
> Done. Sorry for the delay, got infected with COVID-19 and spent last couple of days on the edge of reality. Seems like I might be coming back though.

No worries! I hope you recover quickly and don't have any long-term effects. I've somehow managed to not be infected yet, but the statistics tell me there's just a matter of time before it happens.

@dl8dtl do you have a comment, or is it all good and can be merged? I'm going to use this on a programmer I've recently designed that will automatically switch between UPDI and UART mode based on this signal.

image

**Comment by dl8dtl** [comment]
> do you have a comment, or is it all good and can be merged?

Only reason for not already merging it last night was that I wanted to copy&paste Dawid's documentation about the extended parameter handling over to `avrdude.1` as well. I just did that, so I'm going to merge it.

**Comment by MCUdude** [comment]
Great, thanks!

**Pull request merged**
