### PR TITLE
MSYS2 MinGW GNU Readline support (Do Not Merge)

### LINKED ISSUE #1155: Readline support for mingw
I created PR #1148 to add readline for mingw32/64 github action build. Unfortunately it caused problem and had to be reverted.
* #1148 

Looking at the failed build log (https://github.com/avrdudes/avrdude/actions/runs/3308684165/jobs/5461248027), the issue is still the MSYS2 readline/termcap packaging issues mentioned here.
* https://github.com/msys2/MINGW-packages/issues/8105

On my local machine I can fix the issue by rebuilding termcap as per the tips from MSYS2 github issue. 
* https://github.com/msys2/MINGW-packages/issues/8105#issuecomment-1229270428

I'll see what I can do to correct this issue using github action. I am not good at github action scripts. Hopefully someone more experienced in github action can help as well.

### PR DESCRIPTION
**Pull request by mcuee**
This PR adds the support of GNU Readline for MSYS2 MinGW build.
Close #1155.

### CODE REVIEW

**Comment by mcuee** [comment]
But this does not need to be included in 7.1 release.

**Comment by mcuee** [comment]
There is an issue -- libtermcap is dynamically linked, that is why github action does not fail. So this PR is not ready anyway.

```
$ ldd ./avrdude.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff8ba60000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff89e40000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff89110000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff898e0000)
        SETUPAPI.dll => /c/WINDOWS/System32/SETUPAPI.dll (0x7fff89f00000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fff8a7c0000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fff896d0000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fff8b7e0000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fff89700000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fff89630000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff89510000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fff89d70000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff8b810000)
        HID.DLL => /c/WINDOWS/SYSTEM32/HID.DLL (0x7fff878a0000)
        libtermcap-0.dll => /mingw64/bin/libtermcap-0.dll (0x6ac40000)


```

**Comment by mariusgreuel** [comment]
@mcuee Your changes look good, however, the question to me is whether MinGWs readline is any good.

> CTRL/SHIFT/ALT and CAPSLOCK will cause time out. This seems to be one of the main issue.

This suggest that the MinGW readline code has similar deficiencies as [GNU Readline for Windows](https://gnuwin32.sourceforge.net/packages/readline.htm), if not being based the same code.

I tried your MinGW CI build, and at least the x64 build does not crash on Ctrl-R, so they seems to have fixed some x64 related bugs.

Looking at GNU Readline for Windows, I must say its in bad shape. Having worked with it, I think we are better off not using it. Perhaps its easiest to use #1264 for MinGW as well.

**Comment by mcuee** [comment]
> Looking at GNU Readline for Windows, I must say its in bad shape. Having worked with it, I think we are better off not using it. Perhaps its easiest to use https://github.com/avrdudes/avrdude/pull/1264 for MinGW as well.

I agree. I will close thie PR and #1155. Then I will create a new issue to adopt #1264 for MinGW.

**Comment by mcuee** [comment]
I have created #1271.
* #1271

**Pull request closed without merging**
