### PR TITLE
fix M1 homebrew path

### PR DESCRIPTION
**Pull request by hallard**

### CODE REVIEW

**Comment by dl8dtl** [comment]
Thanks, this was exactly the patch I've been asking for. ;-)

Just to make double sure: if `/opt/homebrew` does exist, then everything has to be searched for in `/usr/homebrew` (opt vs. usr), is that correct?

**Comment by mcuee** [comment]
Looks like a typo. `/usr/homebrew` should be changed to `/opt/homebrew`.

**Comment by hallard** [comment]
my bad, fixed, sorry about this one

**Comment by dl8dtl** [comment]
Great, sounds more logical to me that way. ;-)

**Comment by hallard** [comment]
path is correct on the issue and was not able just to copy/paste the code in the PR, may be it was too late in the night for me :-)

**Comment by mcuee** [comment]
This has a problem that the install prefix path is still `/usr/local` and `make install` will install to '/usr/local'.

An extra option is needed `-D CMAKE_INSTALL_PREFIX:PATH=/opt/homebrew/Cellar/avrdude/7.0` for the release version and a bit different directory is needed for HEAD.

**Comment by mcuee** [comment]
BTW, I think the wiki instruction is not that correct for macOS Homebrew. We should not point to `Cellar`.

```
cmake -D CMAKE_C_FLAGS=-I/opt/homebrew/include -D CMAKE_EXE_LINKER_FLAGS=-L/opt/homebrew/lib -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_INSTALL_PREFIX:PATH=/opt/homebrew/Cellar/avrdude/7.0 -B build_macos

cmake --build build_macos

cmake --install build_macos
```

Detailed log:
```

mcuee@mcuees-Mac-mini avrdude-7.0 % cmake -D CMAKE_C_FLAGS=-I/opt/homebrew/include -D CMAKE_EXE_LINKER_FLAGS=-L/opt/homebrew/lib -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_INSTALL_PREFIX:PATH=/opt/homebrew/Cellar/avrdude/7.0 -B build_macos
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /opt/homebrew/bin/git (found version "2.36.1") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/bin/bison (found version "2.3")
-- Looking for libelf.h
-- Looking for libelf.h - not found
-- Looking for libelf/libelf.h
-- Looking for libelf/libelf.h - found
-- Looking for usb.h
-- Looking for usb.h - found
-- Looking for lusb0_usb.h
-- Looking for lusb0_usb.h - not found
-- Looking for libusb.h
-- Looking for libusb.h - not found
-- Looking for libusb-1.0/libusb.h
-- Looking for libusb-1.0/libusb.h - found
-- Looking for hidapi/hidapi.h
-- Looking for hidapi/hidapi.h - found
-- Looking for ftdi_tcioflush
-- Looking for ftdi_tcioflush - found
-- Configuration summary:
-- ----------------------
-- DO HAVE    libelf
-- DO HAVE    libusb
-- DO HAVE    libusb_1_0
-- DO HAVE    libhidapi
-- DON'T HAVE libftdi
-- DO HAVE    libftdi1
-- DISABLED   doc
-- DISABLED   parport
-- DISABLED   linuxgpio
-- DISABLED   linuxspi
-- ----------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mcuee/build/avr/cmake7build/avrdude-7.0/build_macos


mcuee@mcuees-Mac-mini avrdude-7.0 % cmake --build build_macos        
[  1%] [FLEX][Parser] Building scanner with flex 2.6.4
[  3%] [BISON][Parser] Building parser with bison 2.3
[  4%] Building C object src/CMakeFiles/libavrdude.dir/arduino.c.o
[  6%] Building C object src/CMakeFiles/libavrdude.dir/avr.c.o
[  8%] Building C object src/CMakeFiles/libavrdude.dir/avr910.c.o
[  9%] Building C object src/CMakeFiles/libavrdude.dir/avrftdi.c.o
[ 11%] Building C object src/CMakeFiles/libavrdude.dir/avrftdi_tpi.c.o
[ 13%] Building C object src/CMakeFiles/libavrdude.dir/avrpart.c.o
[ 14%] Building C object src/CMakeFiles/libavrdude.dir/bitbang.c.o
[ 16%] Building C object src/CMakeFiles/libavrdude.dir/buspirate.c.o
[ 18%] Building C object src/CMakeFiles/libavrdude.dir/butterfly.c.o
[ 19%] Building C object src/CMakeFiles/libavrdude.dir/config.c.o
[ 21%] Building C object src/CMakeFiles/libavrdude.dir/confwin.c.o
[ 22%] Building C object src/CMakeFiles/libavrdude.dir/crc16.c.o
[ 24%] Building C object src/CMakeFiles/libavrdude.dir/dfu.c.o
[ 26%] Building C object src/CMakeFiles/libavrdude.dir/fileio.c.o
[ 27%] Building C object src/CMakeFiles/libavrdude.dir/flip1.c.o
[ 29%] Building C object src/CMakeFiles/libavrdude.dir/flip2.c.o
[ 31%] Building C object src/CMakeFiles/libavrdude.dir/ft245r.c.o
[ 32%] Building C object src/CMakeFiles/libavrdude.dir/jtagmkI.c.o
[ 34%] Building C object src/CMakeFiles/libavrdude.dir/jtagmkII.c.o
/Users/mcuee/build/avr/cmake7build/avrdude-7.0/src/jtagmkII.c:491:18: warning: variable 'checksum' set but not used [-Wunused-but-set-variable]
  unsigned short checksum = 0;
                 ^
1 warning generated.
[ 36%] Building C object src/CMakeFiles/libavrdude.dir/jtag3.c.o
[ 37%] Building C object src/CMakeFiles/libavrdude.dir/linuxgpio.c.o
[ 39%] Building C object src/CMakeFiles/libavrdude.dir/linuxspi.c.o
[ 40%] Building C object src/CMakeFiles/libavrdude.dir/lists.c.o
[ 42%] Building C object src/CMakeFiles/libavrdude.dir/micronucleus.c.o
[ 44%] Building C object src/CMakeFiles/libavrdude.dir/par.c.o
[ 45%] Building C object src/CMakeFiles/libavrdude.dir/pgm.c.o
[ 47%] Building C object src/CMakeFiles/libavrdude.dir/pgm_type.c.o
[ 49%] Building C object src/CMakeFiles/libavrdude.dir/pickit2.c.o
[ 50%] Building C object src/CMakeFiles/libavrdude.dir/pindefs.c.o
[ 52%] Building C object src/CMakeFiles/libavrdude.dir/ppi.c.o
[ 54%] Building C object src/CMakeFiles/libavrdude.dir/ppiwin.c.o
[ 55%] Building C object src/CMakeFiles/libavrdude.dir/serbb_posix.c.o
[ 57%] Building C object src/CMakeFiles/libavrdude.dir/serbb_win32.c.o
[ 59%] Building C object src/CMakeFiles/libavrdude.dir/ser_avrdoper.c.o
[ 60%] Building C object src/CMakeFiles/libavrdude.dir/ser_posix.c.o
[ 62%] Building C object src/CMakeFiles/libavrdude.dir/ser_win32.c.o
[ 63%] Building C object src/CMakeFiles/libavrdude.dir/serialupdi.c.o
[ 65%] Building C object src/CMakeFiles/libavrdude.dir/stk500.c.o
[ 67%] Building C object src/CMakeFiles/libavrdude.dir/stk500v2.c.o
[ 68%] Building C object src/CMakeFiles/libavrdude.dir/stk500generic.c.o
[ 70%] Building C object src/CMakeFiles/libavrdude.dir/teensy.c.o
[ 72%] Building C object src/CMakeFiles/libavrdude.dir/updi_link.c.o
[ 73%] Building C object src/CMakeFiles/libavrdude.dir/updi_nvm.c.o
[ 75%] Building C object src/CMakeFiles/libavrdude.dir/updi_readwrite.c.o
[ 77%] Building C object src/CMakeFiles/libavrdude.dir/updi_state.c.o
[ 78%] Building C object src/CMakeFiles/libavrdude.dir/usbasp.c.o
[ 80%] Building C object src/CMakeFiles/libavrdude.dir/usb_hidapi.c.o
[ 81%] Building C object src/CMakeFiles/libavrdude.dir/usb_libusb.c.o
[ 83%] Building C object src/CMakeFiles/libavrdude.dir/usbtiny.c.o
[ 85%] Building C object src/CMakeFiles/libavrdude.dir/update.c.o
[ 86%] Building C object src/CMakeFiles/libavrdude.dir/wiring.c.o
[ 88%] Building C object src/CMakeFiles/libavrdude.dir/xbee.c.o
[ 90%] Building C object src/CMakeFiles/libavrdude.dir/__/lexer.c.o
[ 91%] Building C object src/CMakeFiles/libavrdude.dir/__/config_gram.c.o
[ 93%] Linking C static library libavrdude.a
[ 93%] Built target libavrdude
[ 95%] Building C object src/CMakeFiles/avrdude.dir/main.c.o
[ 96%] Building C object src/CMakeFiles/avrdude.dir/term.c.o
[ 98%] Building C object src/CMakeFiles/avrdude.dir/whereami.c.o
[100%] Linking C executable avrdude
[100%] Built target avrdude

mcuee@mcuees-Mac-mini avrdude-7.0 % cmake --install build_macos
-- Install configuration: "RelWithDebInfo"
-- Installing: /opt/homebrew/Cellar/avrdude/7.0/bin/avrdude
-- Installing: /opt/homebrew/Cellar/avrdude/7.0/lib/libavrdude.a
-- Up-to-date: /opt/homebrew/Cellar/avrdude/7.0/include/libavrdude.h
-- Installing: /opt/homebrew/Cellar/avrdude/7.0/etc/avrdude.conf
-- Up-to-date: /opt/homebrew/Cellar/avrdude/7.0/share/man/avrdude.1

mcuee@mcuees-Mac-mini avrdude-7.0 % brew link avrdude  
Linking /opt/homebrew/Cellar/avrdude/7.0... 5 symlinks created.


mcuee@mcuees-Mac-mini avrdude-7.0 % avrdude
Usage: avrdude [options]
Options:
  -p <partno>                Required. Specify AVR device.
  -b <baudrate>              Override RS-232 baud rate.
  -B <bitclock>              Specify JTAG/STK500v2 bit clock period (us).
  -C <config-file>           Specify location of configuration file.
  -c <programmer>            Specify programmer type.
  -D                         Disable auto erase for flash memory
  -i <delay>                 ISP Clock Delay [in microseconds]
  -P <port>                  Specify connection port.
  -F                         Override invalid signature check.
  -e                         Perform a chip erase.
  -O                         Perform RC oscillator calibration (see AVR053). 
  -U <memtype>:r|w|v:<filename>[:format]
                             Memory operation specification.
                             Multiple -U options are allowed, each request
                             is performed in the order specified.
  -n                         Do not write anything to the device.
  -V                         Do not verify.
  -t                         Enter terminal mode.
  -E <exitspec>[,<exitspec>] List programmer exit specifications.
  -x <extended_param>        Pass <extended_param> to programmer.
  -v                         Verbose output. -v -v for more.
  -q                         Quell progress output. -q -q for less.
  -l logfile                 Use logfile rather than stderr for diagnostics.
  -?                         Display this usage.

avrdude version 7.0, URL: <https://github.com/avrdudes/avrdude>
```

**Comment by dl8dtl** [comment]
> This has a problem that the install prefix path is still `/usr/local` and `make install` will install to '/usr/local'.

I'd say this is OK.
IMHO, a user-built binary is fine under `/usr/local`. `/opt/homebrew` ought to remain the domain of the Homebrew maintainers, wouldn't it?
FreeBSD doesn't divide between both, their ports system installs everything under `/usr/local`. I occasionally find that a little irritating, as by just looking at something there, you cannot say whether it has been installed from the ports system, or manually by an admin.

**Comment by mcuee** [comment]
> > This has a problem that the install prefix path is still `/usr/local` and `make install` will install to '/usr/local'.
> 
> I'd say this is OK. IMHO, a user-built binary is fine under `/usr/local`. `/opt/homebrew` ought to remain the domain of the Homebrew maintainers, wouldn't it?

I agree you that this is the domain of Homebrew avrdude formula maintainer. 
The formula is now broken for "--HEAD" option as it does not point to github. Hopefully they will fix it soon.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/avrdude.rb

**Comment by mcuee** [comment]
> > This has a problem that the install prefix path is still `/usr/local` and `make install` will install to '/usr/local'.
> 
> I'd say this is OK. IMHO, a user-built binary is fine under `/usr/local`. `/opt/homebrew` ought to remain the domain of the Homebrew maintainers, wouldn't it? 

However it is not really okay to install to /usr/local for Homebrew users who use both ARM64 and x86_64 version of homebrew.

The ARM64 version will be at /opt/homebrew and the x86_64 version will be at /usr/local.

**Comment by mcuee** [comment]
in any case, the wiki and this patch need to be fixed so as not to point to `-L/opt/homebrew/lib`for ARM64 and `-L/usr/local/lib` for x86_64.

```
            # Apple M1 (may be new version of homebrew also)
            if [ -d /opt/homebrew ]  
            then
                build_flags="${build_flags} -D CMAKE_C_FLAGS=-I/opt/homebrew/include -D CMAKE_EXE_LINKER_FLAGS=-L/opt/homebrew/lib"
            else
                build_flags="${build_flags} -D CMAKE_C_FLAGS=-I/usr/local/include -D CMAKE_EXE_LINKER_FLAGS=-L/usr/local/lib"
            fi
```

**Comment by mcuee** [comment]
> FreeBSD doesn't divide between both, their ports system installs everything under /usr/local. I occasionally find that a little irritating, as by just looking at something there, you cannot say whether it has been installed from the ports system, or manually by an admin.

Indeed. But on the other hand, they are supposedly to be of the same architecture and not causing problems, unlike macOS M1 machines where you can have both ARM64 and x86_64 version of homebrew.

**Comment by dl8dtl** [comment]
> However it is not really okay to install to /usr/local for Homebrew users who use both ARM64 and x86_64 version of homebrew.

Is the relocation to `/opt/homebrew` really only for the new architecture, or was that rather a trigger only to move it there generally?
For an architecture distinction, it looks a little too generic to me then.

Also, if one is compiling something theirselves (which is what Hombrew is about, after all), why would they want to locally install amd64 binaries in the first place? I wouldn't want to do that. Using Rosetta for compiled 3rd-party software makes sense to me (to ease the transition), but I'd prefer to have self-compiled stuff native always.

**Comment by mcuee** [comment]
> Is the relocation to `/opt/homebrew` really only for the new architecture, or was that rather a trigger only to move it there generally? For an architecture distinction, it looks a little too generic to me then.

You can see from Homebrew homepage.
https://docs.brew.sh/Installation
> This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon and /home/linuxbrew/.linuxbrew for Linux) so that [you don’t need sudo](https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad) when you brew install. It is a careful script; it can be run even if you have stuff installed in the preferred prefix already. It tells you exactly what it will do before it does it too. You have to confirm everything it will do before it starts.

**Comment by hallard** [comment]
Good catch, reading this article is confusing https://mac.install.guide/homebrew/index.html

> If you have an older Intel Mac, Homebrew installs files into the `/usr/local/` folder, which is already configured for access by the shell with the macOS default $PATH environment variable. Mac Intel installation is easier because there's no need to configure your shell environment. Homebrew packages are found automatically. However, the Homebrew team was criticized for using the `/usr/local/` folder because other programs might install software into the folder, overwriting Homebrew packages. With the release of version 3.0.0 for Apple silicon, the Homebrew team responded and changed the default folder, adding an installation step that requires a change to the shell environment

So what ?

> With the release of version 3.0.0 for Apple silicon, the Homebrew team responded and changed the default folder

Does this mean it's only for M1 or related to V3.0.0 of homebrew?  I assumed since V.3.0.0 hombrew was now installed into `/opt/homebrew/` Only way to know is to check after a fresh install (not an old one already in `/usr/local`of homebrew on x86 that I fon't have anymore.

**Comment by mcuee** [comment]
> Does this mean it's only for M1 or related to V3.0.0 of homebrew? I assumed since V.3.0.0 hombrew was now installed into `/opt/homebrew/` Only way to know is to check after a fresh install (not an old one already in `/usr/local`of homebrew) on x86 that I don't have anymore.

You can look at the Homebrew installation script.
https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

The installation path is hard-coded. Changing the installation path is possible but not supported by Homebrew project.

```
# Required installation paths. To install elsewhere (which is unsupported)
# you can untar https://github.com/Homebrew/brew/tarball/master
# anywhere you like.
if [[ -z "${HOMEBREW_ON_LINUX-}" ]]
then
  UNAME_MACHINE="$(/usr/bin/uname -m)"

  if [[ "${UNAME_MACHINE}" == "arm64" ]]
  then
    # On ARM macOS, this script installs to /opt/homebrew only
    HOMEBREW_PREFIX="/opt/homebrew"
    HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
  else
    # On Intel macOS, this script installs to /usr/local only
    HOMEBREW_PREFIX="/usr/local"
    HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew"
  fi```

**Comment by mcuee** [comment]
@dl8dtl Any updates on merging this pull request?

**Comment by dl8dtl** [comment]
> @dl8dtl Any updates on merging this pull request?

I still think  it's wrong.
Installing by default into `/usr/local` is IMHO the correct thing, as it is the common default for basically everything you can compile yourself. It's unfortunate that Homebrew/x86 does also install it there, same for FreeBSD ports. However, no other software around changes its default installation target depending on a CPU architecture. Likewise, on MacOS/Macports, we would not default the installation target to `/opt/local`, as this is in the domain of Macports, as well as `/opt/homebrew` is in Homebrew's domain. So the Homebrew maintainer of the software collection would set this as a target.

**Pull request merged**
