### PR TITLE
Print meaningful error when a too slow ISP clock is detected

### PR DESCRIPTION
**Pull request by MCUdude**
Some JTAG3 compatible programmers can actually detect if the connected target is too slow for the (a) default ISP clock or (b) user-specified ISP clock using -B.

This includes the PICkit4, Atmel ICE and Power Debugger. I don't think the SNAP has this capability. At least I've not been able to get it to detect it.

The thing is that the programmer returns a 0xCC if the target is too slow to communicate. This will only work when the target _has_ a clock. If no clock is preset, we'll get the usual 0xC0 error.

Here's an example where the ATmega16 is running at 1 MHz
```
$ ./avrdude -catmelice_isp -patmega16 -B2

avrdude error: target clock speed error
avrdude error: initialization failed, rc=-2
        The programmer ISP clock is too fast for the target
        - use -B to set lower ISP clock frequency, e.g. -B 125kHz
        - use -F to override this check


avrdude done.  Thank you.

$ ./avrdude -catmelice_isp -patmega16 -B4

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9403 (probably m16)

avrdude done.  Thank you.
```

### CODE REVIEW

**Comment by mcuee** [comment]
@MCUdude 

Strange I can not get this to work with PICKit 4 and ATmega8A running at 1MHz.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_git -c pickit4_isp -p m8a -qt

avrdude_git: AVR device initialized and ready to accept instructions
avrdude_git: device signature = 0x1e9307 (probably m8a)
avrdude> dump lfuse
0000  a1                                                |.               |

avrdude> dump hfuse
0000  c4                                                |.               |

avrdude> quit
avrdude>
avrdude_git done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_git -c pickit4_isp -p m8a -B1

avrdude_git error: command failed
avrdude_git error: initialization failed, rc=-1
            - double check the connections and try again
            - use -B to set lower ISP clock frequency, e.g. -B 200kHz
            - use -F to override this check


avrdude_git done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1216 -C .\avrdude_pr1216.conf -c pickit4_isp -p m8a -B1

avrdude_pr1216 error: command failed
avrdude_pr1216 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 125kHz
               - use -F to override this check


avrdude_pr1216 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1216 -C .\avrdude_pr1216.conf -c pickit4_isp -p m8a -B4

avrdude_pr1216: AVR device initialized and ready to accept instructions
avrdude_pr1216: device signature = 0x1e9307 (probably m8a)

avrdude_pr1216 done.  Thank you.

```

**Comment by MCUdude** [comment]
@mcuee are you using the latest firmware for your PICkit4?

And what happens if you try -B2?

**Comment by MCUdude** [comment]
Strange. I'd like to know which firmware version Avrdude reports. Try running Avrdude with -v or -vv

**Comment by mcuee** [comment]
@MCUdude 

I see. Thanks for the explanations.

**Comment by mcuee** [comment]
@MCUdude 
 
In that case, I think this PR is good to go as well.

**Review by stefanrueger — COMMENTED** [review]
Looks great! Super-tiny comment: In the line
```
imsg_error("The programmer ISP clock is too fast for the target\n");
```
the error message could start with lower-case the (in line with other error messages)

**Comment by MCUdude** [comment]
@stefanrueger thanks, I've changed the error message

**Pull request merged**
