### PR TITLE
Macos nonstandard baudrates

### PR DESCRIPTION
**Pull request by dl8dtl**
Supposed to fix issue #771

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks for the PR, I can confirm that it works properly on my machine too (macOS 10.14)
However, maybe it's time to not make the custom baud rate "warning" a little nicer? A non-standard baud rate won't really be a problem on any platform anymore.

This is how it currently looks like:
```
$ ./avrdude  -C avrdude.conf -p atmega1284p -c arduino -b 500000 -P /dev/cu.usbserial-1410 -v

avrdude: Version 6.99-20211218
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is "avrdude.conf"
         User configuration file is "/Users/hans/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbserial-1410
         Using Programmer              : arduino
         Overriding Baud Rate          : 500000
avrdude: serial_baud_lookup(): Using non-standard baud rate: 500000
         AVR Part                      : ATmega1284P
         Chip Erase delay              : 55000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

```

It would be nice if it perhaps looked something like this instead:
```
$ ./avrdude  -C avrdude.conf -p atmega1284p -c arduino -b 500000 -P /dev/cu.usbserial-1410 -v

avrdude: Version 6.99-20211218
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is "avrdude.conf"
         User configuration file is "/Users/hans/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbserial-1410
         Using Programmer              : arduino
         Overriding Baud Rate          : 500000 (non-standard)
         AVR Part                      : ATmega1284P
         Chip Erase delay              : 55000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

```

**Comment by MCUdude** [comment]
Should this be applied to serbb_posix.c as well?

**Comment by MCUdude** [comment]
> Should this be applied to serbb_posix.c as well?

@dl8dtl would be great if you could clarify. I've never used a serial bit-banging programmer myself, so I don't really know.

**Comment by dl8dtl** [comment]
As serbb* performs bit-banging, I don't think arbitrary baudrates are of concern there.

**Pull request merged**
