### PR TITLE
Enable prodsig read for jtagmkII programmers

### PR DESCRIPTION
**Pull request by stefanrueger**
@MCUdude @mcuee Please test. There is existing code to write(!) signature and calibration bytes. Can jtagmkII?

### CODE REVIEW

**Comment by MCUdude** [comment]
Work with the ATmega324PB. With and without the OCDEN fuse set:

```
$ ./avrdude -cdragon_jtag -patmega324pb -Uprodsig:r:-:h
avrdude warning: OCDEN fuse not programmed, single-byte EEPROM updates not possible
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9517 (probably m324pb)

avrdude: processing -U prodsig:r:-:h
avrdude: reading prodsig/sigrow memory ...
avrdude: writing output file <stdout>
0x1e,0x83,0x95,0x1e,0x17,0x1,0xa5,0xa5,0xff,0x82,0xff,0xff,0xff,0xff,0x53,0x42,0x32,0x31,0x38,0x36,0x9,0x8,0x19,0x2c
avrdude error: bad response to leave progmode command: RSP_FAILED

avrdude done.  Thank you.



$ ./avrdude -cdragon_jtag -patmega324pb -T 'c ocden=0' -Uprodsig:r:-:h
avrdude warning: OCDEN fuse not programmed, single-byte EEPROM updates not possible
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9517 (probably m324pb)

avrdude: processing -T c ocden=0

avrdude: processing -U prodsig:r:-:h
avrdude: reading prodsig/sigrow memory ...
avrdude: writing output file <stdout>
0x1e,0x83,0x95,0x1e,0x17,0x1,0xa5,0xa5,0xff,0x82,0xff,0xff,0xff,0xff,0x53,0x42,0x32,0x31,0x38,0x36,0x9,0x8,0x19,0x2c

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
OK, great! What is the significance of the error
```
avrdude error: bad response to leave progmode command: RSP_FAILED
```

And what about the (existing) code for writing `signature` and `calibration` memories? Is that just hogwash and should be deleted?

**Comment by MCUdude** [comment]
> `avrdude error: bad response to leave progmode command: RSP_FAILED`

This error has "always been there" and shows up when the target is not in OCD mode (I think. I'm not getting the warning when in OCD mode).

**Comment by mcuee** [comment]
Just one more data point to say this PR is good to go, with the trick mentioned by @stefanrueger [here] (https://github.com/avrdudes/avrdude/pull/1520#issue-1943993419) for an unsupported part.

```
PS>./avrdude_pr1525 -C ./avrdude_pr1525_mod.conf -c dragon_jtag -p m128a -qq -Uprodsig:r:-:h
0x1e,0xb3,0x97,0xb1,0x2,0xad,0xff,0xad,0xe7,0xff,0xff,0xff,0xff,0xff,0x36,0x48,0x36,0x4a,0x33,0x38,0xff,0x15,0x18,0x4,0x17,0x1,0x12,0x42,0x13,0x42,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
```

**Comment by mcuee** [comment]
So this PR should be good to go.

**Comment by stefanrueger** [comment]
@mcuee @MCUdude Thanks for sterling testing

**Pull request merged**
