### PR TITLE
Fix micronucleus bootloader to check for unresponsive USB devices

### LINKED ISSUE #944: Micronucleus read error
When trying to upload a program to an ATtiny85 running the Micronucleus bootloader, I'm getting the following error:

```
$ ./avrdude -C avrdude.conf -c micronucleus -p attiny85 -Uflash:w:/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_489940/Blink.ino.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e930b (probably t85)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_489940/Blink.ino.hex"
avrdude: writing flash (542 bytes):

Writing | ################################################## | 100% 0.14s

avrdude: 542 bytes of flash written
avrdude: verifying flash memory against /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_489940/Blink.ino.hex:

Reading | ######                                             | 11% 0.00savrdude: Unsupported memory type: flash
avr_read(): error reading address 0x0000
    read operation not supported for memory "flash"
avrdude: failed to read all of flash memory, rc=-2

avrdude done.  Thank you.
```

Since the Micronucleus bootloader doesn't support flash reading at all, why is Avrdude trying to read the flash by default? Wouldn't it be better if Avrdude simply skipped reading the flash by default when using the micronucleus programmer option instead of "manually" adding the -V flag every time?

### PR DESCRIPTION
**Pull request by mariusgreuel**
Fixes #944, pending approval of @MCUdude.

### CODE REVIEW

**Comment by MCUdude** [comment]
Works perfectly here! One tiny detail. Can we make it three dots instead of four? 

`avrdude: WARNING: Unresponsive Micronucleus device detected, please reconnect....`

Output:

```
$ ./avrdude -v -C avrdude.conf -c micronucleus -p attiny85 -x wait

avrdude: Version 6.99-20211218
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is "avrdude.conf"
         User configuration file is "/Users/hans/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : usb
         Using Programmer              : micronucleus
avrdude: WARNING: Unresponsive Micronucleus device detected, please reconnect....
avrdude: No device found, waiting for device to be plugged in...
avrdude: Press CTRL-C to terminate.
avrdude: Found device with Micronucleus V2.5, bus:device: 020:021
         AVR Part                      : ATtiny85
         Chip Erase delay              : 4500 us
         RESET disposition             : possible i/o
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom                 65     6     4    0 no        512    4      0  4000  4500 0xff 0xff
           flash                  65     6    32    0 yes      8192   64    128  4500  4500 0xff 0xff
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
           lock                    0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
           lfuse                   0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
           hfuse                   0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
           efuse                   0     0     0    0 no          1    1      0  9000  9000 0x00 0x00
           calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00

         Programmer Type : Micronucleus V2.0
         Description     : Micronucleus Bootloader

avrdude: Bootloader version: 2.5
avrdude: Available flash size: 6586
avrdude: Page size: 64
avrdude: Bootloader start: 0x19C0
avrdude: Write sleep: 7ms
avrdude: Erase sleep: 721ms
avrdude: Signature1: 0x93
avrdude: Signature2: 0x0B
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e930b (probably t85)

avrdude done.  Thank you.
```

**Comment by mariusgreuel** [comment]
@dl8dtl Is it OK to merge this PR before the v7.0 release?

**Review by MCUdude — APPROVED** [review]

**Comment by MCUdude** [comment]
I think this one is safe to merge. It works perfectly when starting Avrdude and _then_ plugging in the board too. And since 7.0 will be the first Avrdude release that supports the Micronucleus bootloader, there isn't any legacy implementation we can break by adding this anyways.

**Comment by mcuee** [comment]
This helps under Windows as well.

```
/c/work/avr/avrdude-fork/build/src
$ ./avrdude.exe -v -c micronucleus -p attiny88 -x wait -vv -U Blink_ino_t88.hex
executable_abspath = C:/work/avr/avrdude-fork/build/src/avrdude.exe
executable_abspath_len = 46
executable_dirpath = C:/work/avr/avrdude-fork/build/src
executable_dirpath_len = 34
sys_config = C:/work/avr/avrdude-fork/build/src/avrdude.conf
sys_config_found = true


avrdude.exe: Version 6.99-20220505 (01a9e42)
             Copyright (c) Brian Dean, http://www.bdmicro.com/
             Copyright (c) Joerg Wunsch

             System wide configuration file is "C:/work/avr/avrdude-fork/build/src/avrdude.conf"

avrdude.exe: micronucleus_setup()
avrdude.exe: micronucleus_parseextparams()
avrdude.exe: defaulting memtype in -U w:Blink_ino_t88.hex option to "flash"
avrdude.exe: defaulting memtype in -U v:Blink_ino_t88.hex option to "flash"
             Using Port                    : usb
             Using Programmer              : micronucleus
avrdude.exe: micronucleus_open("usb")
avrdude.exe: WARNING: Unresponsive Micronucleus device detected, please reconnect...
avrdude.exe: No device found, waiting for device to be plugged in...
avrdude.exe: Press CTRL-C to terminate.
avrdude.exe: Found device with Micronucleus V2.6, bus:device: 003:025
             AVR Part                      : ATtiny88
             Chip Erase delay              : 9000 us
             PAGEL                         : PD7
             BS2                           : PC2
             RESET disposition             : dedicated
             RETRY pulse                   : SCK
             Serial program mode           : yes
             Parallel program mode         : yes
             Timeout                       : 200
             StabDelay                     : 100
             CmdexeDelay                   : 25
             SyncLoops                     : 32
             PollIndex                     : 3
             PollValue                     : 0x53
             Memory Detail                 :

                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               eeprom                 65    20     4    0 no         64    4      0  3600  3600 0xff 0xff
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               flash                  65     6    64    0 yes      8192   64    128  4500  4500 0xff 0xff
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               lfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               hfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               efuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               lock                    0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00
                                               Block Poll               Page                       Polled
               Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00

             Programmer Type : Micronucleus V2.0
             Description     : Micronucleus Bootloader
avrdude.exe: micronucleus_display()

avrdude.exe: micronucleus_enable()
avrdude.exe: micronucleus_initialize()
avrdude.exe: Bootloader version: 2.6
avrdude.exe: Available flash size: 6716
avrdude.exe: Page size: 64
avrdude.exe: Bootloader start: 0x1A40
avrdude.exe: Write sleep: 7ms
avrdude.exe: Erase sleep: 735ms
avrdude.exe: Signature1: 0x93
avrdude.exe: Signature2: 0x11
avrdude.exe: AVR device initialized and ready to accept instructions

Reading |                                                    | 0% 0.00savrdude.exe: micronucleus_read_sig_bytes()
Reading | ################################################## | 100% 0.01s

avrdude.exe: Device signature = 0x1e9311 (probably t88)
avrdude.exe: NOTE: "flash" memory has been specified, an erase cycle will be performed
             To disable this feature, specify the -D option.
avrdude.exe: erasing chip
avrdude.exe: micronucleus_chip_erase()
avrdude.exe: micronucleus_erase_device()
avrdude.exe: reading input file "Blink_ino_t88.hex"
avrdude.exe: input file Blink_ino_t88.hex auto detected as Intel Hex
avrdude.exe: writing flash (468 bytes):

Writing |                                                    | 0% 0.00savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x0, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x0000, size=64)
Writing | ######                                             | 12% 0.03savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x40, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x0040, size=64)
Writing | #############                                      | 25% 0.07savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x80, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x0080, size=64)
Writing | ###################                                | 37% 0.10savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0xC0, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x00C0, size=64)
Writing | #########################                          | 50% 0.13savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x100, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x0100, size=64)
Writing | ###############################                    | 62% 0.16savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x140, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x0140, size=64)
Writing | ######################################             | 75% 0.19savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x180, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x0180, size=64)
Writing | ############################################       | 87% 0.23savrdude.exe: micronucleus_paged_write(page_size=0x40, addr=0x1C0, n_bytes=0x40)
avrdude.exe: micronucleus_write_page(address=0x01C0, size=64)
Writing | ################################################## | 100% 0.26s

avrdude.exe: 468 bytes of flash written
avrdude.exe: verifying flash memory against Blink_ino_t88.hex:
avrdude.exe: load data flash data from input file Blink_ino_t88.hex:
avrdude.exe: input file Blink_ino_t88.hex auto detected as Intel Hex
avrdude.exe: input file Blink_ino_t88.hex contains 468 bytes
avrdude.exe: reading on-chip flash data:

Reading |                                                    | 0% 0.00savrdude.exe: micronucleus_paged_load(page_size=0x40, addr=0x0, n_bytes=0x40)
Reading | ######                                             | 12% 0.01savrdude.exe: micronucleus_read_byte(desc=flash, addr=0x0)
avrdude.exe: Unsupported memory type: flash
avr_read(): error reading address 0x0000
    read operation not supported for memory "flash"
avrdude.exe: failed to read all of flash memory, rc=-2
avrdude.exe: micronucleus_powerdown()
avrdude.exe: micronucleus_write_page(address=0x1A00, size=64)
avrdude.exe: micronucleus_start()
avrdude.exe: micronucleus_disable()
avrdude.exe: micronucleus_close()

avrdude.exe done.  Thank you.

avrdude.exe: micronucleus_teardown()

```

**Pull request merged**
