### PR TITLE
Fix tempsense size, AVR-EB memory offsets and avrdude.conf memory order

### PR DESCRIPTION
**Pull request by stefanrueger**
- `tempsense` size is 4, not 2, for AVR-Dx and AVR-Ex parts
 - AVR-EB memory offsets for `signature`, `sernum`, `tempsense` and `userrow` were wrong
 - Memory order in parts is now `prodsig` (= `sigrow`), `signature`, `tempsense`, `sernum` (a more logical account)

### CODE REVIEW

**Comment by mcuee** [comment]
Looks good to me. This should be good to be merged.

**Comment by MCUdude** [comment]
Great! I've just ordered some free AVR-EB samples from Microchip, but I'm not sure when they will arrive. We can probably merge this PR anyway, but I want to make sure Avrdude works with the EB parts before we release 7.3.

**Comment by MCUdude** [comment]
I'm expecting an AVR16EB32 Curiosity Nano (And an AVR-EA Curiosity Nano as well!) to soon show up in the mail. I should probably make sure that the JTAG3/EDBG, jtag2updi, and the SerialUPDI programmer can read all memories, and write to the ones that allow it.

**Comment by MCUdude** [comment]
It looks like the AVR16EB32 works without any issues! I've currently only tested it using the on-board Curiosity Nano programmer, but it looks promising! Anything you want me to double-check @stefanrueger?

```
$ ./avrdude -cpkobn_updi -pavr16eb32 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e943e (probably avr16eb32)

avrdude: processing -t interactive terminal
avrdude> part
AVR Part                      : AVR16EB32
RESET disposition             : dedicated
RETRY pulse                   : SCK
Serial program mode           : yes
Parallel program mode         : yes
Memory Detail                 :

                                  Block Poll               Page                       Polled
  Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
  ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
  fuse0       wdtcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuse1       bodcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuse2       osccfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuse5       syscfg0     0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuse6       syscfg1     0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuse7       codesize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuse8       bootsize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
  fuses                   0     0     0    0 no         16   16      0     0     0 0x00 0x00
  lock                    0     0     0    0 no          4    1      0     0     0 0x00 0x00
  prodsig     sigrow      0     0     0    0 no        128  128      0     0     0 0x00 0x00
  signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
  tempsense               0     0     0    0 no          4    1      0     0     0 0x00 0x00
  sernum                  0     0     0    0 no         16    1      0     0     0 0x00 0x00
  userrow     usersig     0     0     0    0 no         64   64      0     0     0 0x00 0x00
  data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
  io                      0     0     0    0 no       4160    1      0     0     0 0x00 0x00
  sib                     0     0     0    0 no         32    1      0     0     0 0x00 0x00
  eeprom                  0     0     0    0 no        512    8      0     0     0 0x00 0x00
  flash                   0     0     0    0 no      16384   64      0     0     0 0x00 0x00
  fusea       pdicfg      0     0     0    0 no          2    1      0     0     0 0x00 0x00
  bootrow                 0     0     0    0 no         64   64      0     0     0 0x00 0x00

avrdude> erase
erasing chip ...

avrdude> write flash 0 "Hello AVR16EB32!"
Caching | ################################################## | 100% 0.00 s 

avrdude> write eeprom 0 "Hello AVR-EB!"
Caching | ################################################## | 100% 0.01 s 

avrdude> flush
avrdude: synching cache to device ... 
Writing | ################################################## | 100% 0.09 s 

avrdude> read flash 0 0x20
Reading | ################################################## | 100% 0.00 s 
0000  48 65 6c 6c 6f 20 41 56  52 31 36 45 42 33 32 21  |Hello AVR16EB32!|
0010  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> read eeprom 0 0x20
Reading | ################################################## | 100% 0.01 s 
0000  48 65 6c 6c 6f 20 41 56  52 2d 45 42 21 00 ff ff  |Hello AVR-EB!...|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> read signature
Reading | ################################################## | 100% 0.01 s 
0000  1e 94 3e                                          |..>             |

avrdude> read tempsense
Reading | ################################################## | 100% 0.02 s 
0000  cf fd 85 ec                                       |....            |

avrdude> read sernum
Reading | ################################################## | 100% 0.06 s 
0000  62 32 40 63 1f ff 0e 07  f0 18 f0 60 ff ff ff ff  |b2@c.......`....|

avrdude> read userrow
Reading | ################################################## | 100% 0.01 s 
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> write userrow 0 "Hello World!"
Caching | ################################################## | 100% 0.00 s 

avrdude> flush
avrdude: synching cache to device ... 
Writing | ################################################## | 100% 0.05 s 

avrdude> read userrow
Reading | ################################################## | 100% 0.00 s 
0000  48 65 6c 6c 6f 20 57 6f  72 6c 64 21 00 ff ff ff  |Hello World!....|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> read sib
Reading | ################################################## | 100% 0.00 s 
0000  41 56 52 20 20 20 20 20  50 3a 35 44 3a 31 2d 33  |AVR     P:5D:1-3|
0010  4d 32 20 28 41 30 2e 35  39 42 31 44 2e 30 29 00  |M2 (A0.59B1D.0).|

avrdude> read fusea
Reading | ################################################## | 100% 0.01 s 
0000  03 00                                             |..              |
```

**Comment by MCUdude** [comment]
It seems like there is an issue with writing the `fusea`/`pdicfg` fuse:

```
$ ./avrdude -cpkobn_updi -pavr16eb32 -qq -t
avrdude> read fusea
0000  03 00                                             |..              |

avrdude> write fusea 0 0x02 0x00
avrdude error: (write) verification error writing 0x02 at 0x00000 cell=0x03 using bit mask 0xf3

avrdude> read fusea
0000  03 00                                             |..              |

avrdude> q

```

**Comment by mcuee** [comment]
@MCUdude 

Great testing.

Issue #1546 created to capture the issue found.

**Pull request merged**
