### PR TITLE
build.sh: For compatibility with old CMake versions, use old syntax to generate build system

### PR DESCRIPTION
**Pull request by mariusgreuel**
Fixes #1300

### CODE REVIEW

**Comment by jclxx** [comment]
Tested on Ubuntu 18.04 with CMake 3.10.2 from standard repositories.

jcl@black:/tmp/avrdude-fork$ git log -1
commit 488da2642a9d6321a5d6bd016885acfccb0b1638 (HEAD -> main, origin/pr-build_sh-cmake-fix)
Author: Marius Greuel <greuelm@mgtek.com>
Date:   Sat Feb 4 17:54:18 2023 +0100

    build.sh: For compatibility with old CMake versions, use old syntax to generate build system
jcl@black:/tmp/avrdude-fork$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
jcl@black:/tmp/avrdude-fork$ uname -a
Linux black 4.20.17-042017-generic #201903190933 SMP Tue Mar 19 13:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
jcl@black:/tmp/avrdude-fork$ ./build.sh 
CMake Error at CMakeLists.txt:23 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.10.2


-- Configuring incomplete, errors occurred!
CMake failed.

**Comment by mcuee** [comment]
@dl8dtl @MCUdude and @stefanrueger 

Just wondering what is your opinion of this PR vs PR #1300.

To be honest, I am thinking that we do not need either PR with the Wiki updates. But I am okay with either one in the end.

Reference:
* #1298 
* #1300 
* #1301

**Comment by stefanrueger** [comment]
@jclxx Thanks for making us aware of the Ubuntu 18.04 problem that you bumped into and for suggesting a PR. 

Having followed the discussion in Issue #1298, in PR #1300 and this PR #1301, and having looked at both PRs, I lean towards merging this PR (#1301) and closing PR #1300. The overriding reason for this is that PR #1301 uses known valid older syntax for the CMake file whilst PR #1300 relies on particular occurrence of a string in the CMakeLists.txt file, which seems a less portable way of doing things. I have no doubt that both PRs will work, though.

Many thanks to @jclxx for getting in touch and suggesting a solution, and to @mariusgreuel and @mcuee for progessing the discussion.

**Comment by jclxx** [comment]
Thanks @stefanrueger for your opinion.  I (very nearly) agree with you:  #1301 is fine, but with a comment saying we're using old CMake syntax on purpose in the code.  It's a shame that CMake had an incompatible old version with undocumented flags, but that's a matter for them.

**Pull request merged**
