### PR TITLE
Implementation of SerialUPDI page erase operation

### PR DESCRIPTION
**Pull request by dbuchwald**
As you can see in the difflist, implementation turned out to be fairly trivial, but to be perfectly honest, I feel that something is pretty off about this whole cached write operation. Since it has nothing to do with SerialUPDI as such, I still want to file this PR.

First, let's go through the invocation to confirm that the page erase operation is running. I was testing against ATmega4809, which uses NVM v0, where PAGE ERASE command is 0x02:

```
./avrdude -c serialupdi -P /dev/cu.usbserial-1420 -p atmega4809 -t -vvv
...
avrdude> write flash 0 255
>>> write flash 0 255 
Info: writing 2 bytes starting from address 0x00

Caching | ################################################## | 100% 0.00s
...
avrdude> flush
>>> flush 
avrdude: synching cache to device ... avrdude: LD from 0x001002
avrdude: sending 4 bytes [0x55, 0x04, 0x02, 0x10]
avrdude: received 1 bytes [0x00]
avrdude: clear page buffer
...
avrdude: erase flash page at address 0x004000
avrdude: LD from 0x001002
avrdude: sending 4 bytes [0x55, 0x04, 0x02, 0x10]
avrdude: received 1 bytes [0x00]
avrdude: ST to 0x004000
avrdude: sending 4 bytes [0x55, 0x44, 0x00, 0x40]
avrdude: received 1 bytes [0x40]
avrdude: sending 1 bytes [0xff]
avrdude: received 1 bytes [0x40]
avrdude: NVMCMD 2 executing
avrdude: ST to 0x001000
avrdude: sending 4 bytes [0x55, 0x44, 0x00, 0x10]
avrdude: received 1 bytes [0x40]
avrdude: sending 1 bytes [0x02]
avrdude: received 1 bytes [0x40]
avrdude: LD from 0x001002
avrdude: sending 4 bytes [0x55, 0x04, 0x02, 0x10]
avrdude: received 1 bytes [0x00]
avrdude: LD from 0x001002
avrdude: sending 4 bytes [0x55, 0x04, 0x02, 0x10]
avrdude: received 1 bytes [0x00]
```

As expected, NVM command 0x02 is executed, so the actual page erase happens.

That being said, I don't understand if this is expected:

```
❯ ./avrdude -c serialupdi -P /dev/cu.usbserial-1420 -p atmega4809 -t -v

avrdude: Version 7.0-20220508
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch
...
         Programmer Type : serialupdi
         Description     : SerialUPDI

avrdude: NVM type 0: 16-bit, page oriented write
avrdude: entering NVM programming mode
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: device signature = 0x1e9651 (probably m4809)
avrdude> erase
>>> erase 
avrdude: erasing chip
avrdude> write flash 0 0
>>> write flash 0 0 
Info: writing 1 bytes starting from address 0x00

Caching | ################################################## | 100% 0.00s

avrdude> flush
>>> flush 
avrdude: synching cache to device ... 
Writing | ################################################## | 100% 0.07s
avrdude> write flash 0 255
>>> write flash 0 255 
Info: writing 2 bytes starting from address 0x00

Caching | ################################################## | 100% 0.00s

avrdude> flush
>>> flush 
avrdude: synching cache to device ... done
avrdude> read flash
>>> read flash 

Reading | ################################################## | 100% 0.00s

0000  ff 00 ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude>
``` 

It seems like the first write operation writes single byte, but the next one writes two, somehow copying the old 0x00 value from flash address 0x0000 to address 0x0001. I don't know. It all looks pretty weird.

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks for the PR @dbuchwald! And great job finding this potential caching bug. @stefanrueger will probably look at this very soon.

**Comment by MCUdude** [comment]
I can reproduce the same issue. Maybe it is caused by a parsing problem? I can only reproduce the issue if I'm writing numbers in base 10, not in base 16...

<details>
<summary> Issue when writing base 10 number to EEPROM </summary>

```
$ ./avrdude -cserialupdi -patmega4808 -t

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: device signature = 0x1e9650 (probably m4808)
avrdude> read eeprom
>>> read eeprom 

Reading | ################################################## | 100% 0.07s

0000  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0010  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0020  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0030  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0040  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0050  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0060  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0070  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0080  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0090  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00a0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00b0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00c0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00d0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00e0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00f0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|

avrdude> write eeprom 0 0
>>> write eeprom 0 0 

Caching | ################################################## | 100% 0.00s

avrdude> flush
>>> flush 
avrdude: synching cache to device ... 
Writing | ################################################## | 100% 0.28s
avrdude> write eeprom 0 255
>>> write eeprom 0 255 

Caching | ################################################## | 100% 0.00s

avrdude> flush
>>> flush 
avrdude: synching cache to device ... done
avrdude> read eeprom
>>> read eeprom 

Reading | ################################################## | 100% 0.00s

0000  ff 00 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |..UUUUUUUUUUUUUU|
0010  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0020  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0030  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0040  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0050  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0060  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0070  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0080  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0090  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00a0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00b0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00c0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00d0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00e0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00f0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
```

</details>

<details>
<summary>No issues when writing base 16 number to EEPROM</summary>

```
$ ./avrdude -cserialupdi -patmega4808 -t

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: device signature = 0x1e9650 (probably m4808)
avrdude> read eeprom
>>> read eeprom 

Reading | ################################################## | 100% 0.07s

0000  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0010  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0020  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0030  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0040  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0050  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0060  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0070  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0080  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0090  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00a0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00b0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00c0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00d0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00e0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00f0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|

avrdude> write eeprom 0 0x00
>>> write eeprom 0 0x00 

Caching | ################################################## | 100% 0.00s

avrdude> flush
>>> flush 
avrdude: synching cache to device ... 
Writing | ################################################## | 100% 0.28s
avrdude> write eeprom 0 0xff
>>> write eeprom 0 0xff 

Caching | ################################################## | 100% 0.00s

avrdude> flush
>>> flush 
avrdude: synching cache to device ... done
avrdude> read eeprom
>>> read eeprom 

Reading | ################################################## | 100% 0.00s

0000  ff 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |.UUUUUUUUUUUUUUU|
0010  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0020  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0030  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0040  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0050  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0060  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0070  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0080  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
0090  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00a0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00b0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00c0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00d0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00e0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
00f0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
```

</details>

**Comment by stefanrueger** [comment]
Thanks for the PR, @dbuchwald This is brilliant!

As to the  terminal write, this has nothing to do with the cache, but is b/c 255 is interpreted as a *signed* integer, which does not fit into a signed byte with [-128, 127] range. It has to be treated as a 2-byte integer! The full rule for he size of an integer in the terminal is documented as 
  - Ordinary 0x hex integers with n hex digits (counting leading zeros) use the smallest size of 1, 2, 4 and 8 bytes that can accommodate any n-digit hex integer. If an integer suffix specifies a size explicitly the corresponding number of least significant bytes are written. Otherwise, signed and unsigned integers alike occupy the smallest of 1, 2, 4, or 8 bytes needed to accommodate them in their respective representation.

**Comment by stefanrueger** [comment]
Maybe the documentation could add: For example, 0x001 uses 2 bytes, 0x000000FF uses 4 bytes, 0xff uses one byte (unsigned), 255u uses one byte (unsigned), 255 uses *two* bytes (as a signed number it is outside the [-128, 127] interval).

**Comment by dbuchwald** [comment]
Thank you for clarification, I will test the code again with this in mind and let you know if I come across any other issues.

Best regards,
Dawid
________________________________
Od: Stefan Rueger ***@***.***>
Wysłane: niedziela, 23 października 2022 22:29
Do: avrdudes/avrdude ***@***.***>
DW: Dawid Buchwald ***@***.***>; Mention ***@***.***>
Temat: Re: [avrdudes/avrdude] Implementation of SerialUPDI page erase operation (PR #1151)


Maybe the documentation could add: For example, 0x001 uses 2 bytes, 0x000000FF uses 4 bytes, 0xff uses one byte (unsigned), 255u uses one byte (unsigned), 255 uses two bytes (as a signed number it is outside the [-128, 127] interval).

**Comment by dbuchwald** [comment]
OK, so here's final update: I have tested it against other chips as well (NVM v0 and NVM v2) and they all seem to work just fine, so I think this PR is ready for merge.

**Comment by stefanrueger** [comment]
Fantastic! Will merge with the next batch of PRs.

**Comment by mcuee** [comment]
Finally I got serialupdi working with an FTDI FT232RL adapter (with 6pin AVR ISP connector) with an 1k Ohm resistor for my ATmega4808 Nano 4808 board (I have to short the 1k ohm on-board resistor on the UPDI line).

I can confirm this PR is working.

git main shows that `page erase not implemented yet`.
```
C:\work\avr\avrdude_test\avrdude_bin> ./avrdude_git -c serialupdi -P COM16 -p m4808 -qq -t
avrdude> write flash 0 0x55
>>> write flash 0 0x55
avrdude> flush
>>> flush
avrdude> dump flash 0 0x10
>>> dump flash 0 0x10
0000  55 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |U...............|

avrdude> write flash 0 0xaa
>>> write flash 0 0xaa
avrdude> flush
>>> flush
avrdude_git: synching cache to device ... 
avrdude_git serialupdi_page_erase() [serialupdi.c:884] error: page erase not implemented yet
reading/chip erase/writing cycle needed ... done
avrdude> quit
>>> quit
avrdude> avrdude_git: leaving NVM programming mode

avrdude_git done.  Thank you.
```

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1151 -c serialupdi -P COM16 -p m4808 -qq -t
avrdude> dump flash 0 0x10
>>> dump flash 0 0x10
0000  aa ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> write flash 0 0x55
>>> write flash 0 0x55
avrdude> flush
>>> flush
avrdude> dump flash 0 0x10
>>> dump flash 0 0x10
0000  55 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |U...............|

avrdude> quit
>>> quit
avrdude>
```

Verbose log (I tried to set the verbosity level in the terminal mode but it does not work -- new issue created).

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1151 -c serialupdi -P COM16 -p m4808 -vvv -t
executable_abspath = C:/work/avr/avrdude_test/avrdude_bin/avrdude_pr1151.exe
executable_abspath_len = 55
executable_dirpath = C:/work/avr/avrdude_test/avrdude_bin
executable_dirpath_len = 36
sys_config = C:/work/avr/avrdude_test/avrdude_bin/avrdude.conf
sys_config_found = true
...
>>> write flash 0 0xaa
avrdude_pr1151: (write) writing 1 bytes starting from address 0x00

Caching |                                                    | 0% 0.00 s avrdude_pr1151: reading 128 bytes from 0x004000
avrdude_pr1151: ST_PTR to 0x004000
avrdude_pr1151: sending 4 bytes [0x55, 0x69, 0x00, 0x40]
avrdude_pr1151: received 1 bytes [0x40]
avrdude_pr1151: repeat 128
avrdude_pr1151: sending 3 bytes [0x55, 0xa0, 0x7f]
avrdude_pr1151: LD8 from ptr++
avrdude_pr1151: sending 2 bytes [0x55, 0x24]
avrdude_pr1151: received 128 bytes [0x55, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff]
Caching | ################################################## | 100% 0.09 s

avrdude> flush
>>> flush
avrdude_pr1151: synching cache to device ... avrdude_pr1151: LD from 0x001002
avrdude_pr1151: sending 4 bytes [0x55, 0x04, 0x02, 0x10]
avrdude_pr1151: received 1 bytes [0x00]
avrdude_pr1151: clear page buffer
avrdude_pr1151: NVMCMD 4 executing
avrdude_pr1151: ST to 0x001000
...
avrdude_pr1151: erase flash page at address 0x004000
avrdude_pr1151: LD from 0x001002
avrdude_pr1151: sending 4 bytes [0x55, 0x04, 0x02, 0x10]
avrdude_pr1151: received 1 bytes [0x00]
avrdude_pr1151: ST to 0x004000
avrdude_pr1151: sending 4 bytes [0x55, 0x44, 0x00, 0x40]
avrdude_pr1151: received 1 bytes [0x40]
avrdude_pr1151: sending 1 bytes [0xff]
avrdude_pr1151: received 1 bytes [0x40]
avrdude_pr1151: NVMCMD 2 executing
avrdude_pr1151: ST to 0x001000
avrdude_pr1151: sending 4 bytes [0x55, 0x44, 0x00, 0x10]
avrdude_pr1151: received 1 bytes [0x40]
avrdude_pr1151: sending 1 bytes [0x02]
avrdude_pr1151: received 1 bytes [0x40]
```
avrdude_pr1151: received 128 bytes [0xaa, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff]
done
avrdude> quit
>>> quit
avrdude> avrdude_pr1151: leaving NVM programming mode
avrdude_pr1151: sending reset request
avrdude_pr1151: STCS 0x59 to address 0x08
avrdude_pr1151: sending 3 bytes [0x55, 0xc8, 0x59]
avrdude_pr1151: sending release reset request
avrdude_pr1151: STCS 0x00 to address 0x08
avrdude_pr1151: sending 3 bytes [0x55, 0xc8, 0x00]
avrdude_pr1151: STCS 0x0C to address 0x03
avrdude_pr1151: sending 3 bytes [0x55, 0xc3, 0x0c]

avrdude_pr1151 done.  Thank you.
```

**Pull request merged**
