### PR TITLE
avrftdi: don't use the deprecated ftdi_usb_purge_buffers routine

### PR DESCRIPTION
**Pull request by yegorich**
Since commit ed46f09c1ccd1351e003a200ba50e3e4778ac478 (Implement
tc[io]flush methods & deprecate broken purge_buffers methods.)
`ftdi_usb_purge_buffers()` routine is deprecated. Use `HAVE_FTDI_TCIOFLUSH`
macro to invoke the newly introduced `ftdi_tcioflush()` routine.

### CODE REVIEW

**Comment by yegorich** [comment]
The first `libftdi1` version implementing `ftdi_tcioflush()` is 1.5.0. According to the GitHub actions, only MacOS provides this version.

This PR is compile-tested only.

**Comment by mariusgreuel** [comment]
Your patch does not seem to work for MinGW:
https://github.com/avrdudes/avrdude/runs/4685849550?check_suite_focus=true

To be honest, I would favor a `#define _FTDI_DISABLE_DEPRECATED 1` in avrftdi.c.

P.S.: I am not really a Un*x guy, but I am pretty sure the T in TCIOFLUSH stands for terminal. Not sure why they picked such a name.

**Comment by dl8dtl** [comment]
> I am pretty sure the T in TCIOFLUSH stands for terminal.

Correct.

> Not sure why they picked such a name.

TC = "terminal control"

This is the historic name passed as a constant to an `ioctl()` syscall.

(As these ioctls have never been agreed on between differen Unix flavours, Posix instead standardized a set of library functions, so the respective function is `tcflush()`.)

**Comment by yegorich** [comment]
According to https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html, it is better to use `CheckSymbolExists`. I'll resend the new version and we will see whether it works for mingw.

**Comment by yegorich** [comment]
`CheckSymbolExists` doesn't help. @mariusgreuel can you look at the `CMakeError.log`? Why does it have problems with detecting the routine?

**Comment by dl8dtl** [comment]
Btw., so far, the idea is that we maintain both, CMake and autoconf/automake in parallel.
Right now, the PR only handles CMake though.

**Comment by yegorich** [comment]
So, mingw issue is fixed. As we use static libs, I had to also add `libusb` dependencies.

@dl8dtl now I can try to also integrate this check into `configure.ac`.

**Comment by dl8dtl** [comment]
Btw., I can test that stuff once it's ready.

**Comment by yegorich** [comment]
@dl8dtl autoconf seems to work. Can you look at it? Thanks

**Comment by dl8dtl** [comment]
> @dl8dtl autoconf seems to work. Can you look at it? Thanks

For reasons I don't quite understand yet, it fails here (on FreeBSD). I get link errors since several libraries are no longer being linked.

Code from your repository, main branch links like:
```
libtool: link: gcc -Wall -Wno-pointer-sign -g -O2 -o avrdude avrdude-main.o avrdude-whereami.o avrdude-term.o  ./libavrdude.a -lusb -lftdi1 -lelf -lpthread -lm -lhidapi -lreadline -lncurses -ltermcap
```

Code from your repository, ftdi-fix-deprecated-call branch links like:
```
libtool: link: gcc -Wall -Wno-pointer-sign -g -O2 -o avrdude avrdude-main.o avrdude-term.o  ./libavrdude.a -lusb -lelf -lpthread -lm -lftdi1
```

As you can see, a lot of libraries are missing.

Will look into that tonight.

**Comment by dl8dtl** [comment]
> Will look into that tonight.

Found it. You clobbered LIBS, rather than extending it.

**Comment by yegorich** [comment]
Yes, now I see it too.

**Comment by yegorich** [comment]
It's a pity that GitHub doesn't support FreeBSD in the Actions. Whether this [project](https://github.com/marketplace/actions/freebsd-vm) could  help?

**Comment by dl8dtl** [comment]
> It's a pity that GitHub doesn't support FreeBSD in the Actions. Whether this [project](https://github.com/marketplace/actions/freebsd-vm) could help?

I'll let @mariusgreuel answer that, he's more knowledgable than me about the Github infrastructure.

**Comment by dl8dtl** [comment]
Just as a confirmation, seems to work fine here.

**Comment by mariusgreuel** [comment]
> > It's a pity that GitHub doesn't support FreeBSD in the Actions. Whether this [project](https://github.com/marketplace/actions/freebsd-vm) could help?
> 
> I'll let @mariusgreuel answer that, he's more knowledgable than me about the Github infrastructure.

I tried the FreeBSD action, with mixed success: As it runs in a VM, it is terribly slow, which is annoying when tinkering around. It also got stuck multiple times (which may be caused by GitHub actions which are also not perfect). For now, I have it running in my personal repo as a separate workflow, so that it does not mess up my status badge. I will monitor it to see how it performs over time.

**Comment by dl8dtl** [comment]
Well, as I use FreeBSD as my primary development platform, I think that gives it enough testing coverage.

**Pull request merged**
