### PR TITLE
Consider classic part usersig memory offset for jtag3

### PR DESCRIPTION
**Pull request by stefanrueger**
Fixes Issue #379

### CODE REVIEW

**Comment by MCUdude** [comment]
Output from the Xplained Pro ATmega256RFR2 I got in the mail this morning. I think it works!

```
$./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig
Reading | ################################################## | 100% 0.01 s 
0000  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0010  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0020  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0030  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0040  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> write usersig 0x80 "Avrdude PR #1466"
Caching | ################################################## | 100% 0.00 s 
avrdude> flush
avrdude: synching cache to device ... 
Writing | ################################################## | 100% 0.02 s 
avrdude> quit

avrdude done.  Thank you.

src $./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig 0 -1
Reading | ################################################## | 100% 0.02 s 
0000  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0010  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0020  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0030  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0040  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  41 76 72 64 75 64 65 20  50 52 20 23 31 34 36 36  |Avrdude PR #1466|
0090  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0100  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0110  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0120  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0130  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0140  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0150  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0160  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0170  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0180  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0190  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0200  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0210  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0220  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0230  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0240  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0250  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0260  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0270  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0280  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0290  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> quit

avrdude done.  Thank you.
```

**Comment by MCUdude** [comment]
Without this PR:

```
$ git rev-parse --abbrev-ref HEAD # print current branch
main

$./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig 0 -1
Reading | ################################################## | 100% 0.02 s 
0000  1e a9 a8 ff 02 ff ff ff  ed ff ff f7 ff ff 54 32  |..............T2|
0010  36 34 30 37 15 0d 0a 1c  17 06 12 08 13 08 ff ff  |6407.  .........|
0020  86 25 86 27 86 25 86 27  ff ff ff ff 00 29 00 79  |.%.'.%.'.....).y|
0030  ff ff ff ff 00 29 00 59  ff ff ff ff 86 25 86 27  |.....).Y.....%.'|
0040  86 24 86 27 00 40 00 90  ff ff ff ff 00 90 00 50  |.$.'.@.........P|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0100  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0110  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0120  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0130  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0140  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0150  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0160  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0170  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0180  41 76 72 64 75 64 65 20  50 52 20 23 31 34 36 36  |Avrdude PR #1466|
0190  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
01f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0200  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0210  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0220  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0230  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0240  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0250  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0260  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0270  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0280  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0290  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
02f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> quit

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
Brill! Thanks for testing @MCUdude. 

There is one niggling question: Are you able to *overwrite* previous programming? Usersig is not erased with a chip erase and it isn't clear to me whether it needs a page erase (which the code tells me will not work) before writing new contents.

This should be tested with jtag2 and jtag3.

**Comment by MCUdude** [comment]
> Are you able to overwrite previous programming?

 It seems like I'm only able to write zeros to usersig. The hardware I have doesn't make it very easy to test with other JTAG programmers, so @dl8dtl would have to test this with a JTAG2 compatible programmmer

```
$ ./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig
Reading | ################################################## | 100% 0.01 s 
0000  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0010  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0020  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0030  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0040  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  41 76 72 64 75 64 65 20  50 52 20 23 31 34 36 36  |Avrdude PR #1466|
0090  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> write usersig 0x80 "Hello"
Caching | ################################################## | 100% 0.00 s 
avrdude> flush
avrdude: synching cache to device ... 
Writing | -------------------------------------------------- | 0% 0.03 s 
avrdude error: verification mismatch at usersig page addr 0x0000
avrdude> quit
avrdude: synching cache to device ... 
Writing | -------------------------------------------------- | 0% 0.01 s 
avrdude error: verification mismatch at usersig page addr 0x0000
avrdude: synching cache to device ... 
Writing | -------------------------------------------------- | 0% 0.02 s 
avrdude error: verification mismatch at usersig page addr 0x0000

avrdude done.  Thank you.

$ ./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig
Reading | ################################################## | 100% 0.01 s 
0000  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0010  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0020  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0030  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0040  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  40 64 60 64 65 00 65 20  50 52 20 23 31 34 36 36  |@d`de.e PR #1466|
0090  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> quit

avrdude done.  Thank you.
```

**Comment by dl8dtl** [comment]
> It seems like I'm only able to write zeros to usersig.

That's basically what I would have expected. It's typical NOR flash behaviour.
To return the signature data to 0xFF, it needs a page erase. At least for the JTAGICEmkII, I'm pretty sure its firmware has never implemented user signature page erase though (JTAGICEmkII development was already finished by the time the megaRF project was done). Perhaps the Atmel-ICE could really do it, it has a much more modern firmware.

**Comment by stefanrueger** [comment]
I've just used the XMEGA code for usersig page erase in the jtagmkII.c and jtag3.c code. Could someone try, please?

**Comment by MCUdude** [comment]
I can confirm that I'm able to write 1's with your latest commit @stefanrueger:

```
$ ./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig
Reading | ################################################## | 100% 0.01 s 
0000  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0010  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0020  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0030  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0040  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  40 64 60 64 65 00 65 20  50 52 20 23 31 34 36 36  |@d`de.e PR #1466|
0090  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> write usersig 0x80 "The quick brown fox jumped over the lazy fox"
Caching | ################################################## | 100% 0.00 s 
avrdude> flush
avrdude: synching cache to device ... done
avrdude> quit

avrdude done.  Thank you.

$ ./avrdude -cxplainedpro -patmega256rfr2 -t
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -t interactive terminal
avrdude> read usersig
Reading | ################################################## | 100% 0.01 s 
0000  02 13 87 08 f6 a0 1c 25  04 00 41 54 4d 45 47 41  |.......%..ATMEGA|
0010  32 35 36 52 46 52 32 20  58 70 6c 61 69 6e 65 64  |256RFR2 Xplained|
0020  20 50 72 6f 00 00 00 00  30 32 30 30 30 30 37 36  | Pro....02000076|
0030  35 37 41 30 39 2d 31 37  38 34 03 00 e1 00 00 00  |57A09-1784......|
0040  00 00 00 00 00 00 00 00  00 00 2d 49 ff ff ff ff  |..........-I....|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0090  66 6f 78 20 6a 75 6d 70  65 64 20 6f 76 65 72 20  |fox jumped over |
00a0  74 68 65 20 6c 61 7a 79  20 66 6f 78 00 ff ff ff  |the lazy fox....|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> quit

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
Excellent! Then I suspect this will also work with jtagmkII programmers (at least I hope!). @dl8dtl?

Glad this works with `-T` and `-t`. I suspect programming with `-U` will be problematic b/c erasing sth like the classic part usersig memory was never modelled by AVRDUDE. `-U` will only be able to write 0s never 1s. There are workarounds, though, using sth like `-T "erase usersig"` before using `-U usersig:w:file`

**Comment by stefanrueger** [comment]
Added documentation in the anticipation that final r/w tests by @dl8dtl with jtag2/jtag3 will be successful.

Planning to merge this and other PRs tomorrow for final sanity tests, if any, before v7.2 release.

**Comment by mcuee** [comment]
I think the documentation updates are good. Hopefully the test from @dl8dtl is positive. Then this PR is good to go.

**Comment by stefanrueger** [comment]
@MCUdude @dl8dtl In addition to the interactive terminal, I'd suggest the following tests
```
avrdude -c ... -p ATmega256RFR2 -U usersig:r:/tmp/backup.hex:I
avrdude -c ... -p ATmega256RFR2 -T "erase usersig" -U usersig:r:-:I
avrdude -c ... -p ATmega256RFR2 -U usersig:w:/tmp/backup.hex:I
avrdude -c ... -p ATmega256RFR2 -T '"write usersig 0x81 "This is a test" 3.14159265358979D'
avrdude -c ... -p ATmega256RFR2 -T "erase usersig" -U usersig:w:/tmp/backup.hex:I
rm /tmp/backup.hex
```

**Comment by MCUdude** [comment]
@stefanrueger sure!

```
$ ./avrdude -c xplainedpro -p ATmega256RFR2 -U usersig:r:/tmp/backup.hex:I
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -U usersig:r:/tmp/backup.hex:I
avrdude: reading usersig memory ...
Reading | ################################################## | 100% 0.02 s 
avrdude: writing output file /tmp/backup.hex

avrdude done.  Thank you.

$ ./avrdude -c xplainedpro -p ATmega256RFR2 -T "erase usersig" -U usersig:r:-:I
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -T erase usersig
Caching | ################################################## | 100% 0.02 s 
avrdude: synching cache to device ... done

avrdude: processing -U usersig:r:-:I
avrdude: reading usersig memory ...
Reading | ################################################## | 100% 0.02 s 
avrdude: writing output file <stdout>
:20000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00 // 00000> ................................
:20002000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0 // 00020> ................................
:20004000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0 // 00040> ................................
:20006000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA0 // 00060> ................................
:20008000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80 // 00080> ................................
:2000A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60 // 000a0> ................................
:2000C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40 // 000c0> ................................
:2000E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF20 // 000e0> ................................
:20010000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF // 00100> ................................
:20012000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF // 00120> ................................
:20014000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBF // 00140> ................................
:20016000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F // 00160> ................................
:20018000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F // 00180> ................................
:2001A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F // 001a0> ................................
:2001C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3F // 001c0> ................................
:2001E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1F // 001e0> ................................
:20020000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE // 00200> ................................
:20022000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDE // 00220> ................................
:20024000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBE // 00240> ................................
:20026000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9E // 00260> ................................
:20028000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7E // 00280> ................................
:2002A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5E // 002a0> ................................
:2002C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3E // 002c0> ................................
:2002E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1E // 002e0> ................................
:00000001FF

avrdude done.  Thank you.

$ ./avrdude -c xplainedpro -p ATmega256RFR2 -U usersig:w:/tmp/backup.hex:I
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -U usersig:w:/tmp/backup.hex:I
avrdude: reading input file /tmp/backup.hex for usersig
         with 768 bytes in 1 section within [0, 0x2ff]
         using 3 pages and 0 pad bytes
avrdude: writing 768 bytes usersig ...
Writing | ################################################## | 100% 0.03 s 
avrdude: 768 bytes of usersig written
avrdude: verifying usersig memory against /tmp/backup.hex
Reading | ################################################## | 100% 0.02 s 
avrdude: 768 bytes of usersig verified

avrdude done.  Thank you.

$ ./avrdude -c xplainedpro -p ATmega256RFR2 -T 'write usersig 0x81 "This is a test" 3.14159265358979D'
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -T write usersig 0x81 "This is a test" 3.14159265358979D
Caching | ################################################## | 100% 0.01 s 
avrdude: synching cache to device ... done

avrdude done.  Thank you.

$ ./avrdude -c xplainedpro -p ATmega256RFR2 -T "erase usersig" -U usersig:w:/tmp/backup.hex:I
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1ea802 (probably m256rfr2)

avrdude: processing -T erase usersig
Caching | ################################################## | 100% 0.02 s 
avrdude: synching cache to device ... done

avrdude: processing -U usersig:w:/tmp/backup.hex:I
avrdude: reading input file /tmp/backup.hex for usersig
         with 768 bytes in 1 section within [0, 0x2ff]
         using 3 pages and 0 pad bytes
avrdude: writing 768 bytes usersig ...
Writing | ################################################## | 100% 0.03 s 
avrdude: 768 bytes of usersig written
avrdude: verifying usersig memory against /tmp/backup.hex
Reading | ################################################## | 100% 0.02 s 
avrdude: 768 bytes of usersig verified

avrdude done.  Thank you.

$ rm /tmp/backup.hex
```

**Comment by dl8dtl** [comment]
Sigh. Somehow, none of my setups work today. Maybe it's too hot for me, and I just don't see what I'm doing wrong.

I keep trying …

**Comment by dl8dtl** [comment]
Finally found a setup that is working.
Stefan's suggested sequence yielded the expected results on an ATmega256RFR2, both using a JTAGICEmkII, as well as an AtmelICE.
I had a hard time finding a usable board with an ATmega128RFA1. Eventually was lucky with my old demo setup "Tic-Tac-Toe reloaded" ¹). Using the JTAGICEmkII, "usersig" displays me the prodsig area, and only the prodsig area (repeated at offset 0x100). I cannot erase or reprogram it.
```
avrdude> d usersig
Reading | ################################################## | 100% 0.05 s 
0000  1e b3 a7 ff 01 ff ff ff  ed ff ff f7 ff ff 50 39  |..............P9|
0010  33 30 34 32 15 14 0f 22  17 05 12 04 13 04 ff ff  |3042..."........|
0020  86 24 86 27 ff ff ff ff  ff ff ff ff 00 70 00 99  |.$.'.........p..|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0040  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0050  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0060  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0070  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0090  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00d0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00e0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
```
I just checked the datasheet: it seems the ATmega128RFA1 just doesn't have the usersig feature at all. It's not announced anywhere, and the table with the JTAG programming instructions lacks 9d and 9e.

¹) https://www.gnu.org/savannah-checkouts/non-gnu/uracoli/clt2012/

**Comment by stefanrueger** [comment]
@dl8dtl Many thanks for detailed testing. Great find! I am going to remove the usersig memory description from the ATmega128RFA1.

This should finalise this PR.

**Pull request merged**
