### PR TITLE
Update configure.ac to reflect HAVE_READLINE statue

### PR DESCRIPTION
**Pull request by mcuee**

### CODE REVIEW

**Comment by mcuee** [comment]
Test results:
* https://github.com/avrdudes/avrdude/issues/957#issuecomment-1381284388

**Comment by mcuee** [comment]
I would not update NEWS as this auto-tools build is no longer supported.

**Comment by mcuee** [comment]
There is a github Linux x86_64 build error after merging. That seems to be a temp issue from github side.

**Comment by dl8dtl** [comment]
> There is a github Linux x86_64 build error after merging. That seems to be a temp issue from github side.

I restarted the job.

**Comment by dl8dtl** [comment]
`Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]`

Nothing we are responsible for.

**Comment by mcuee** [comment]
I have also generated the source tarball to be used with a `configure` script here, it seems to work fine under Ubuntu Linux 20.04 and MSYS2 mingw.

https://github.com/mcuee/avrdude/releases/tag/v7.1
https://github.com/mcuee/avrdude/releases/download/v7.1/avrdude-7.1-20230108.tar.gz

**Comment by mcuee** [comment]
> `Unable to connect to azure.archive.ubuntu.com:http: [IP: 20.106.104.242 80]`
> 
> Nothing we are responsible for.

Now the github issue has been resolved.

**Comment by mcuee** [comment]
@MCUdude 

Maybe you can also give the git main a try to use auto-tools.

**Comment by ndim** [comment]
This comment is just to remind me to look into this later.

**Comment by mcuee** [comment]
> This comment is just to remind me to look into this later (post 7.3).

I have created a new issue to track this. 
* https://github.com/avrdudes/avrdude/issues/1664

**Comment by ndim** [comment]
I think I have solved this in https://github.com/avrdudes/avrdude/pull/1681 https://github.com/avrdudes/avrdude/pull/1681/commits/367c7cf6098f5774802a0cc5ae31a0da2b19ab81

**Pull request merged**
