### PR TITLE
Add missing tinyAVR-2, AVR DD and AVR EA targets

### PR DESCRIPTION
**Pull request by MCUdude**
This PR adds the following targets:

* ATtiny3224, ATtiny3226 and ATtiny3227. 
    - These are considered "safe", because I borrowed these from [megaTinyCore](https://github.com/SpenceKonde/megaTinyCore), and they have been tested on actual hardware.
* AVR16DD14/20/28/32, AVR32DD14/20/28/32 and AVR64DD14/20/28/32
* AVR8EA28/32, AVR16EA28/32/48, AVR32EA28/32/48 and AVR64EA28/32/64

For the AVR DD and EA series, I've used the source files from the [`pymcuprog`](https://github.com/microchip-pic-avr-tools/pymcuprog) project to get the necessary details. Please review closely. I've made sure the signature, memory sizes, and page sizes are correct, but please do the same to verify that it is correct. I don't own any DD or EA hardware, and due to the silicon crisis, neither of us won't for a long time I think.

https://github.com/microchip-pic-avr-tools/pymcuprog/tree/main/pymcuprog/deviceinfo/devices

### CODE REVIEW

**Comment by MCUdude** [comment]
Hold on, I'll run the `atdf-to-avrdude.xslt` script to verify that the data I've gathered is correct.

**Comment by MCUdude** [comment]
One thing I don't get; why isn't all memory readsizes set to 1? AFAIK a single byte can be read from all memories

**Comment by dl8dtl** [comment]
> One thing I don't get; why isn't all memory readsizes set to 1? AFAIK a single byte can be read from all memories

To be honest, I can't tell you, not without studying what the code is doing with that parameter.

**Comment by MCUdude** [comment]
I found the following code in the pymcuprog sources:

```py
    # Read size is always 1 byte except for flash that can only read complete words
    readsize = 1
    if name in ['progmem']:
        readsize = 2
```

https://github.com/microchip-pic-avr-tools/pymcuprog/blob/a9411a8e4a5db8b54517c51da0bae96bf8385a65/pymcuprog/deviceinfo/harvest.py#L100-L103

In jtag3.c, this is the only real use I can find:
https://github.com/avrdudes/avrdude/blob/e5edecf95ea3a8dafc45309914ebb1a2127047f5/src/jtag3.c#L1157-L1160

This is the usage in @dbuchwald's SerualUPDI implementation:
https://github.com/avrdudes/avrdude/blob/e5edecf95ea3a8dafc45309914ebb1a2127047f5/src/serialupdi.c#L726-L751

**Comment by dl8dtl** [comment]
> In jtag3.c, this is the only real use I can find:

stk500v2.c and jtagmkI.c/jtagmkII.c always use it instead of the pagesize.

**Pull request merged**
