### PR TITLE
Fix #1168 adding the m328p spmcr address and bl section.

### LINKED ISSUE #1168: debugWire using dragon_dw and jtag2dw
As per the documentation both should work.

But it seems to me I can not get dragon_dw to work properly once I enable debugWire on the Uno clone with ATmega328P using an AVRISP mkii and avrdudess GUI. I am not sure what I did wrong but now it is bricked.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude -c dragon_dw -p m328p -v

avrdude: Version 7.0-20221101 (4c92030)
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude.conf

         Using Port                    : usb
         Using Programmer              : dragon_dw
avrdude: usbdev_open(): found AVRDRAGON, serno: 00A20000xxxx
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        255
  firmware version:              7.39
  hardware version:              1
S_MCU:
  boot-loader FW version:        255
  firmware version:              7.39
  hardware version:              2
Serial number:                   00:a2:00:00:xx:xx
Device ID:                       AVRDRAGON
avrdude jtagmkII_setparm() error: bad response to set parameter command: RSP_DEBUGWIRE_SYNC_FAILED
avrdude main() error: unable to open programmer dragon_dw on port usb

avrdude done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude -c dragon_isp -p m328p
avrdude error: bad response to set parameter command: RSP_FAILED
avrdude warning: ISP activation failed, trying debugWire
avrdude error: bad response to set parameter command: RSP_DEBUGWIRE_SYNC_FAILED
avrdude error: unable to sync with the AVR Dragon in ISP mode
avrdude error: unable to open programmer dragon_isp on port usb

avrdude done.  Thank you.
```

### PR DESCRIPTION
**Pull request by cdealti**
The JTAGICE mkII (as jtag2dw) fails to wite the flash of Arduino UNO R.3 at any address. The minimum fixes are:
* Add spmcr to avrdude.conf
* Add uiStartSmallestBootLoaderSection[] to jtagmkII_set_devdescr()
FIXME: uiStartSmallestBootLoaderSection[] is hardcoded for the m328p.

A proper fix requires changes to the definition of _AVRPART_.

### CODE REVIEW

**Comment by mcuee** [comment]
Hmm, the change to `jtagmkII.c` may be a problem as it is pretty specific to ATmega328P. I am not so sure if there are any side effects to other parts.

**Comment by cdealti** [comment]
The PR is still a draft and not meant to be merged as is.
First, it would be nice if someone could reproduce the bug with the JTAGICE mkII and Arduino UNO, and confirm if this fix helps.
If confirmed, a proper fixe would require more work to support setting uiStartSmallestBootLoaderSection[] from the definitions in _avrdude.conf_.

**Comment by stefanrueger** [comment]
`avrdude.conf` does not know about bootloader sections, but avrintel.c does. We could create new components for `avrdude.conf.in` such as `n_boot_sections` (0, 1, or 4) and `boot_size` (size of smallest boot section). Would need to be convinced first that this actually used by a programmer. @cdealti Please point to documentation for the programmer in question and scope: which parts are affected (classic? xmega? AVR_8X? ...) and which programmer types.

Could you also please carefully read Issue #1071 and double check whether the registers (eg, spmcr) need to be specified as I/O address (no offset for in/out) or memory address (with 0x20 offset, for lds and sts).

It would be great if that could be solved. Documentation and testing with the real device are key.

**Comment by cdealti** [comment]
> @cdealti Please point to documentation for the programmer in question and scope: which parts are affected (classic? xmega? AVR_8X? ...) and which programmer types.

I've described my setup in https://github.com/avrdudes/avrdude/issues/1168#issuecomment-1312466264.

The available documentation for the JTAGICE mkII is the application note AVR069.

As described in the comment, I've used the values in:

https://github.com/avrdudes/avarice/blob/5a125cdd403cf8b7d758a363f75e4e492d15e5ee/src/devdescr.cc#L4119

https://github.com/avrdudes/avarice/blob/5a125cdd403cf8b7d758a363f75e4e492d15e5ee/src/devdescr.cc#L4136

I need to set both.

I don't have access to other programmers or MCUs supporting the debugWire interface.

**Comment by stefanrueger** [comment]
Thanks, this needs more work (by me) so we can deal with all parts that offer DEBUGWire interface. Bear with me.

**Comment by cdealti** [comment]
FYI, flash programming through the debugWire OCD is not supported by Microchip Studio for the JTAGICE mkII and ATmega328P; only ISP is supported.
Same for Arduino IDE, I believe.
Finding the issue was fun. Fixing it probably not the highest priority of AVRDUDE.

**Comment by dl8dtl** [comment]
> FYI, flash programming through the debugWire OCD is not supported by Microchip Studio

Yes, I know. Never really understood why they don't offer it. Adding it when dealing with debugWIRE appeared to be quite logical to me.

**Pull request closed without merging**
