### PR TITLE
Make avrintel.h an internal header file for libavrdude

### PR DESCRIPTION
**Pull request by stefanrueger**
See Issue #1683

### CODE REVIEW

**Comment by stefanrueger** [comment]
It is unclear to me why the CI fails here. I suspect the last CI change has introduced some problems?

**Comment by mcuee** [comment]
@stefanrueger 

I think I know the reason now. MSYS2 started to drop 32bit packages. I will create a new PR to drop MSYS2 mingw32 and clang32 build.

1. News:
https://www.msys2.org/news/
2023-12-13 - Starting to drop some 32-bit Packages

2. Example Dropped package: you can see that no more 32bit packages for libusb.
https://packages.msys2.org/base/mingw-w64-libusb

Binary Packages:
mingw-w64-clang-x86_64-libusb
mingw-w64-clang-aarch64-libusb
mingw-w64-x86_64-libusb
mingw-w64-ucrt-x86_64-libusb

3. Same for the following packages.
https://packages.msys2.org/base/mingw-w64-libusb-compat-git
https://packages.msys2.org/base/mingw-w64-libftdi

**Comment by mcuee** [comment]
@stefanrueger 

CMake change seems to be missing so that additional internal include file is not installed.
* https://github.com/avrdudes/avrdude/issues/1683#issuecomment-1937583210

```
MINGW64 /c/work/avr/avrdude_test/avrdude_sr
# cmake --build build_mingw64_nt-10.0-19045 --target install
[0/1] Install the project...-- Install configuration: "RelWithDebInfo"
-- Installing: C:/Program Files (x86)/avrdude/bin/avrdude.exe
-- Installing: C:/Program Files (x86)/avrdude/lib/libavrdude.a
-- Installing: C:/Program Files (x86)/avrdude/include/libavrdude.h
-- Installing: C:/Program Files (x86)/avrdude/etc/avrdude.conf
-- Installing: C:/Program Files (x86)/avrdude/share/man/man1/avrdude.1
```

**Comment by mcuee** [comment]
@Youw 

Just wondering if you think the original suggested fix is still valid or not now that `libavrdude-avrintel.h` is not exactly public header file but still needed. Thanks.

*  https://github.com/avrdudes/avrdude/issues/1683#issuecomment-1937583210

```
PUBLIC_HEADER "libavrdude.h;libavrdude-avrintel.h"
```

**Comment by stefanrueger** [comment]
> `libavrdude-avrintel.h` is not exactly public header file but still needed

As I understand it, technically it is a public header, but @ndim's [suggestion](https://github.com/avrdudes/avrdude/issues/1683#issuecomment-1937889577), which I have been following in this PR, forces the API to only `#include <libavrdude.h>`.

**Comment by stefanrueger** [comment]
> CMake change seems to be missing so that additional internal include file

Correct. I am hoping that @ndim [would do the suggested change](https://github.com/avrdudes/avrdude/issues/1683#issuecomment-1943062954) in his [overhaul of the Make/build system](https://github.com/avrdudes/avrdude/pull/1681).

So the plan is to merge this PR first and rest is done later in PR #1681

**Comment by mcuee** [comment]
> > CMake change seems to be missing so that additional internal include file
> 
> Correct. I am hoping that @ndim [would do the suggested change](https://github.com/avrdudes/avrdude/issues/1683#issuecomment-1943062954) in his [overhaul of the Make/build system](https://github.com/avrdudes/avrdude/pull/1681).
> 
> So the plan is to merge this PR first and rest is done later in PR #1681

I see. I am okay with this plan.

**Comment by Youw** [comment]
@mcuee yes it is valid and required as per current implementation.

**Comment by ndim** [comment]
I have taken a look at this branch and at libavrdude.h and libavrdude-avrintel.h and ended up with a few more changes at https://github.com/ndim/avrdude/tree/avrintel.h (rebased onto main with the 32bit msys2 builds removed so that CI succeeds again).

Any comments on that? Do you want to cherry-pick from that, or should I file a separate PR superseding this PR, or...?

**Comment by ndim** [comment]
JFTR, I have put my changes into PR #1688.

**Pull request merged**
