### PR TITLE
Provide terminal save command

### PR DESCRIPTION
**Pull request by stefanrueger**
Examples with filename `-` below; will create documentation separately.
```
$ avrdude -qqt -p m328p
avrdude> save -?
Syntax: save <mem> {<addr> <len>} <file>[:<format>]
Function: save memory segments to file (default format :r raw binary)

avrdude> save eeprom -:I
:2000000054686973206973206120746573740048656C6C6F2C20776F726C64210A0054689C // 00000> This_is_a_test.Hello,_world!..Th
:200020006520717569636B2062726F776E20666F78206A756D7073206F76657220746865DD // 00020> e_quick_brown_fox_jumps_over_the
:20004000206C617A7920646F6700FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7C // 00040> _lazy_dog.......................
:20006000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7FEE7FEE7FEE7FEE7FE1D // 00060> ......................g~g~g~g~g~
:20008000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80 // 00080> ................................
:2000A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60 // 000a0> ................................
:2000C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40 // 000c0> ................................
:2000E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF20 // 000e0> ................................
:20010000280992D30B0000F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF62 // 00100> (..S...t........................
:20012000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF // 00120> ................................
:20014000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBF // 00140> ................................
:20016000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F // 00160> ................................
:20018000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F // 00180> ................................
:2001A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F // 001a0> ................................
:2001C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3F // 001c0> ................................
:2001E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1F // 001e0> ................................
:20020000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE // 00200> ................................
:20022000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDE // 00220> ................................
:20024000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBE // 00240> ................................
:20026000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9E // 00260> ................................
:20028000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7E // 00280> ................................
:2002A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5E // 002a0> ................................
:2002C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3E // 002c0> ................................
:2002E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1E // 002e0> ................................
:20030000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD // 00300> ................................
:20032000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDD // 00320> ................................
:20034000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBD // 00340> ................................
:20036000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9D // 00360> ................................
:20038000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7D // 00380> ................................
:2003A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D // 003a0> ................................
:2003C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D // 003c0> ................................
:2003E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1D // 003e0> ................................
:00000001FF

avrdude> save eeprom 15 5 22 5 -:I
:05000F0048656C6C6FF8                                                       // 0000f> Hello
:020000040000FA
:05001600776F726C64BD                                                       // 00016> world
:00000001FF

avrdude> save eeprom 15 5 22 5 -:h
0x48,0x65,0x6c,0x6c,0x6f
0x77,0x6f,0x72,0x6c,0x64
```

### CODE REVIEW

**Comment by MCUdude** [comment]
I'm about to test this PR, and I'd mention that I'm getting the following warning when building:

```
fileio.c:1443:33: warning: use of logical '||' with constant operand [-Wconstant-logical-operand]
  if(size < 0 || op == FIO_READ || FIO_READ_FOR_VERIFY)
                                ^  ~~~~~~~~~~~~~~~~~~~
fileio.c:1443:33: note: use '|' for a bitwise operation
  if(size < 0 || op == FIO_READ || FIO_READ_FOR_VERIFY)
                                ^~
                                |
1 warning generated.

```

**Comment by MCUdude** [comment]
I tried to save various memories with different start addresses and lengths, and everything works perfectly fine!
Excellent work @stefanrueger!

Are there special parts or programmers you'd like me to test? I've only tested with USBasp and an ATmega328P.

**Comment by stefanrueger** [comment]
> special parts or programmers you'd like me to test

No, the terminal is pretty well abstracted through the cache. So, if dump works then save should as well (just that you can choose format and filename)

**Comment by MCUdude** [comment]
Great! Let's wait for @mcuee to test this as well.
Two thumbs up from me 👍 👍

**Comment by mcuee** [comment]
The result seems to be good but I think maybe it is good to add a return after 16 characters, like the normal dump command.

```
C:\work\avr\avrdude_test\avrdude_bin>  .\avrdude_pr1396 -C .\avrdude_pr1396.conf -c usbasp -p m328p -t
avrdude_pr1396: AVR device initialized and ready to accept instructions
avrdude_pr1396: device signature = 0x1e950f (probably m328p)
avrdude> dump eeprom 0 0x20
Reading | ################################################## | 100% 0.12 s
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
avrdude> save eeprom 0 0x20 -:I
Reading | ################################################## | 100% 0.11 s
:2000000054686520717569636B2062726F776E20666F78206A756D7073206F76657220740E // 00000> The_quick_brown_fox_jumps_over_t
:00000001FF
avrdude> save eeprom 0 0x20 -:h
Reading | ################################################## | 100% 0.11 s
0x54,0x68,0x65,0x20,0x71,0x75,0x69,0x63,0x6b,0x20,0x62,0x72,0x6f,0x77,0x6e,0x20,0x66,0x6f,0x78,0x20,0x6a,0x75,0x6d,0x70,0x73,0x20,0x6f,0x76,0x65,0x72,0x20,0x74
avrdude> quit

avrdude_pr1396 done.  Thank you.
```

**Comment by mcuee** [comment]
For the `r` format, I think there is a missing new line.
```
C:\work\avr\avrdude_test\avrdude_bin>  .\avrdude_pr1396 -C .\avrdude_pr1396.conf -c usbasp -p m328p -t
avrdude_pr1396: AVR device initialized and ready to accept instructions
avrdude_pr1396: device signature = 0x1e950f (probably m328p)
avrdude> dump eeprom 0 0x24
Reading | ################################################## | 100% 0.15 s
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c                                       |he l            |
avrdude> save eeprom 0 0x24 -:I
Reading | ################################################## | 100% 0.12 s
:2000000054686520717569636B2062726F776E20666F78206A756D7073206F76657220740E // 00000> The_quick_brown_fox_jumps_over_t
:040020006865206C83                                                         // 00020> he_l
:00000001FF
avrdude> save eeprom 0 0x24 -:H
avrdude_pr1396 error: (save) invalid file format :H; known formats are
  :a auto-detect
  :b 0b-binary byte list
  :d decimal byte list
  :e ELF
  :h 0x-hexadecimal byte list
  :i Intel Hex
  :I Intel Hex with comments
  :m in-place immediate
  :o octal byte list
  :r raw binary
  :R R byte list
  :s Motorola S-Record
avrdude> save eeprom 0 0x24 -:h
Reading | ################################################## | 100% 0.12 s
0x54,0x68,0x65,0x20,0x71,0x75,0x69,0x63,0x6b,0x20,0x62,0x72,0x6f,0x77,0x6e,0x20,0x66,0x6f,0x78,0x20,0x6a,0x75,0x6d,0x70,0x73,0x20,0x6f,0x76,0x65,0x72,0x20,0x74,0x68,0x65,0x20,0x6c
avrdude> save eeprom 0 0x24 -:r
Reading | ################################################## | 100% 0.13 s
The quick brown fox jumps over the lavrdude>

```

**Comment by stefanrueger** [comment]
> add a return after 16 bytes

These file formats are meant to have no returns in between data for ease of machine-readability, so you can, eg, postprocess with shell tools:
```
$ avrdude -qq -U eeprom:r:-:h | cut -f257-262 -d,
0x28,0x9,0x92,0xd3,0xb,0x0

$ avrdude -qq -T 'save eeprom -:h' | cut -f257-262 -d,
0x28,0x9,0x92,0xd3,0xb,0x0

$ avrdude -qq -T 'save eeprom 256 6 -:h'
0x28,0x9,0x92,0xd3,0xb,0x0
```

This PR makes an exception for memory segments, though, where by design each one is put one a single line:
```
avrdude -qq -T 'save eeprom 0 6 256 6 512 6 -:h'
0x54,0x68,0x69,0x73,0x20,0x69
0x28,0x9,0x92,0xd3,0xb,0x0
0xff,0xff,0xff,0xff,0xff,0xff
```

>  r format [misses] new line

Again, no. It's a raw binary format where the output *must not* have extra newlines, (which would be interpreted by additional data when read back from the created file.

**Comment by mcuee** [comment]
> > r format [misses] new line
> 
> Again, no. It's a raw binary format where the output _must not_ have extra newlines, which would be interpreted by additional data when read back from the created file.

Sorry I did not mention this clearly. I think it is missing a new line after displaying the `-r` format file. So you can see that `>avrdude` is immediately after `ju` in the last line of the following run log.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1396 -C .\avrdude_pr1396.conf -c avrispmkii -p m2560 -qqt
avrdude> dump eeprom 0 0x20
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> write eeprom 0 entest.hex
avrdude> flush
avrdude> dump eeprom 0 0x20
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
avrdude> save eeprom 0 0x16 -:r
The quick brown fox juavrdude>                    (>avrdude prompt should be in the next line).
```

**Comment by mcuee** [comment]
> > add a return after 16 bytes
> 
> These file formats are meant to have no returns in between data for ease of machine-readability, so you can, eg, postprocess with shell tools:

The problem is probably that shell tool may be quite different under Windows Command Prompt and PowerShell. 

But I think I can accept this one.

**Comment by mcuee** [comment]
> > `>avrdude` is immediately after `ju` in the last line of the following run log
> 
> Yes, I realise but that's supposed to be like that! Raw mode really is raw. I don't see good applications for `-:r` except when piping into another program or for testing (as you did). When stdout is the terminal then `-:r` will normally result in many funny characters of the type you see when you cat a binary executable (not a great view)

I see. I am okay with this PR now.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1396 -C .\avrdude_pr1396.conf -c avrispmkii -p m2560 -qqt
avrdude> dump eeprom 0x200 0x20
0200  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0210  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> save eeprom 0x200 0x16 -:r
                      avrdude> save eeprom 0x200 0x16 test2.raw:r
avrdude> quit
PS C:\work\avr\avrdude_test\avrdude_bin> cat test2.raw
����������������������

(under MSYS2)
$ hexdump test2.raw
0000000 ffff ffff ffff ffff ffff ffff ffff ffff
0000010 ffff ffff ffff
0000016
```

**Comment by stefanrueger** [comment]
Merging so I can develop new terminal functionality w/o risking merge conflicts. @mcuee @MCUdude Please continue testing against regression (`-U`) and otherwise to smoke out edge cases, in particular, seeing that v7.2 is round the corner.

**Pull request merged**
