### PR TITLE
Move static usbsn into serdev structure, remove serno access function

### PR DESCRIPTION
**Pull request by stefanrueger**
See [here](https://github.com/avrdudes/avrdude/issues/1254#issuecomment-1369091620) for details.

### CODE REVIEW

**Comment by stefanrueger** [comment]
@mcuee and @MCUdude Would you be so kind to test whether printing the serial number still works; both libraries, please, hidapi and libusb.

**Comment by dl8dtl** [comment]
I checked:
* AVRISPmkII
* JTAGICEmkII (in ISP mode)
* AtmelICE (in ISP mode)
Works :-)

**Comment by MCUdude** [comment]
I tested the AVRISPmkII (libusb) and Powerdebugger (hidapi), and both serial numbers is printed correctly!

**Comment by stefanrueger** [comment]
OK to merge right now? It's tested and code changes are modest  and easy to follow.

**Comment by MCUdude** [comment]
Doesn't crash when used with stk500v2 programmers without a serial number either! PR looks ready to be merged.

**Comment by dl8dtl** [comment]
danke!

**Pull request merged**
