### PR TITLE
Add jtag2updi support

### LINKED ISSUE #517: [bug #61626] jtagmkii_pdi improvements for jtag2updi use
MCUdude <None>
Mon 06 Dec 2021 02:39:57 PM UTC
Programmer hardware: jtagmkii_pdi

Hi!

Since there is some activity here, I might as well share my thoughts on this topic.

The only FOSS alternative for a UPDI programmer supported by Avrdude at the moment is the jtag2updi, which uses jtagmkii_pdi as its protocol.

[https://github.com/ElTangas/jtag2updi](https://savannah.nongnu.orghttps://github.com/ElTangas/jtag2updi)

It implements its own custom programmer option in avrdude.conf:

programmer
id    = "jtag2updi";
desc  = "JTAGv2 to UPDI bridge";
type  = "jtagmkii_pdi";
connection_type = serial;
baudrate = 115200;
;

However, there are at least two annoying issues that make the jtag2updi programmer a little "weak".

First, the maximum supported baud rate is 115200 baud. This ends up being rather slow on the UPDI side, so uploading takes a long time for larger programs. Is this something that's possible to fix?

The other one is the same as mentioned in #61624, making it possible to make use of the DTR/RTS lines to indicate that we're currently in jtag2updi mode. The official Arduino Nano Every solves this by using an ARM microcontroller with native USB and using a "1200bps touch" to force it into UPDI mode. Otherwise, it's in USB to serial mode. This is obviously not possible on AVRs with no native USB. Would it be possible to optionally pull the DTR/RTS line(s) low when Avrdude is communicating with the jtag2updi host? This would make it possible to create a programmer that has some external logic to switch the serial pins between the jtag2updi host and the microcontroller:

V_prog          V_target
+-+              +-+
|                |
+----------+                +---------------------+ |                | +--------------------+
| PC       |                | jtag2updi           +-+                +-+  Target            |
| avrdude  |                | programmer          |    +----------+    |                    |
|       TX +--------+       |                 PD6 +----+    1k    +----+ UPDI               |
|          |        |       |                     |    +----------+    |                    |
|       RX +------+ |       |                     |               +----+ RX                 |
|          |      | |       |                     |               |    |                    |
|          |      | |       |                     |               | +--+ TX                 |
|      DTR +----+ | |       |                     |               | |  |                    |
|          |    | | |       |      RX  TX         |               | |  +--------------------+
+----------+    | | |       +------+---+----------+               | |
| | |              |   |                          | |
| | |       +------+---+----------+               | |
| | |       |      RX1 TX1        |               | |
| | +-------+ RX              RX2 +---------------+ |
| |         |                     |                 |
| +---------+ TX   DTR/RTS    TX2 +-----------------+
|           |      Switch         |
+-----------+ DTR                 |
|                     |
+---------------------+

This issue was migrated from https://savannah.nongnu.org/bugs/?61626

### PR DESCRIPTION
**Pull request by MCUdude**
This PR adds support for the @ElTangas' jtag2updi programmer and brings some improvements too:

* Baudrates higher than 115200 are now supported
* jtagmkii.c has been patched to accept devices with `has_updi=true`. This "hack" was borrowed from Arduino's implementation. They have a board, the Arduino Nano Every, that uses the jtag2updi as its programmer.

~There exist other non-critical "problems" too, like the `avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description` error you're always getting when programming a target (see https://github.com/ElTangas/jtag2updi/issues/54), but I haven't been able to find an elegant solution to this.~
Also been solved

Closes #517

### CODE REVIEW

**Comment by MCUdude** [comment]
Is there any particular reason why this PR fails to build on mingw? I don't see any reason why this PR would cause any issues regarding building a binary.

**Comment by dl8dtl** [comment]
> Is there any particular reason why this PR fails to build on mingw? I don't see any reason why this PR would cause any issues regarding building a binary.

If you look at the build log, you'll notice the entire MinGW build did have an issue by that time. Marius meanwhile fixed that, but the CI for this PR did not run again after the fix.

However, see my other question … I think UPDI should only be enabled as a protocol if a jtag2updi device has been successfully recognized.

Suggestion: use a module-internal variable (ideally, in `PDATA`) that gets initialized to `AVRPART_HAS_PDI` by default, and extended to `AVRPART_HAS_PDI | AVRPART_HAS_UPDI` if jtag2updi was found. Then, use that one for all those bitmask operations.

**Comment by MCUdude** [comment]
> However, see my other question … I think UPDI should only be enabled as a protocol if a jtag2updi device has been successfully recognized.

Sorry, even though I've been *using* Avrdude for years, I'm very new to the source code and its structure. So how does Avrdude it is talking to a jtag2updi programmer and not a jtagmkii in PDI mode?

```
./avrdude -C avrdude.conf -v -patmega4808 -cjtag2updi -b115200 -P /dev/cu.usb* 

avrdude: Version 6.99-20211218
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is "avrdude.conf"
         User configuration file is "/Users/hans/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem14101
         Using Programmer              : jtag2updi
         Overriding Baud Rate          : 115200
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
S_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
Serial number:                   00:00:00:00:00:00
Device ID:                       JTAGICE mkII
         AVR Part                      : ATmega4808
         Chip Erase delay              : 0 us
         PAGEL                         : P00
         BS2                           : P00
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 0
         StabDelay                     : 0
         CmdexeDelay                   : 0
         SyncLoops                     : 0
         ByteDelay                     : 0
         PollIndex                     : 0
         PollValue                     : 0x00
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           signature      0     0     0    0 no          3    1      0     0     0 0x00 0x00
           prodsig        0     0     0    0 no         61   61      0     0     0 0x00 0x00
           fuses          0     0     0    0 no          9   10      0     0     0 0x00 0x00
           fuse0          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse1          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse2          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse4          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse5          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse6          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse7          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse8          0     0     0    0 no          1    1      0     0     0 0x00 0x00
           lock           0     0     0    0 no          1    1      0     0     0 0x00 0x00
           data           0     0     0    0 no          0    1      0     0     0 0x00 0x00
           usersig        0     0     0    0 no         64   64      0     0     0 0x00 0x00
           flash          0     0     0    0 no      49152  128      0     0     0 0x00 0x00
           eeprom         0     0     0    0 no        256   64      0     0     0 0x00 0x00

         Programmer Type : JTAGMKII_PDI
         Description     : JTAGv2 to UPDI bridge
         M_MCU hardware version: 1
         M_MCU firmware version: 6.00
         S_MCU hardware version: 1
         S_MCU firmware version: 6.00
         Serial number:          00:00:00:00:00:00
         Vtarget         : 5.0 V

avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.09s

avrdude: Device signature = 0x1e9650 (probably m4808)

avrdude: safemode: Fuses OK (E:FF, H:FF, L:FF)

avrdude done.  Thank you.

```

**Comment by dl8dtl** [comment]
> So how does Avrdude it is talking to a jtag2updi programmer and not a jtagmkii in PDI mode?

In order to know exactly which programmer you are currently talking to, you can use the `pgm->id` flag. For not so obvious reasons, this one is actually an internal list, but you can find examples how to handle that, e.g. in `jtag3.c` around line 1650:

```
  /* XplainedMini boards do not need this, and early revisions had a
   * firmware bug where they complained about it. */
  if ((pgm->flag & PGM_FL_IS_EDBG) &&
      !matches(ldata(lfirst(pgm->id)), "xplainedmini")) {
      jtag3_edbg_signoff(pgm);
  }
```

`pgm->id` is set by the config file parser (`config_gram.y`).

**Comment by MCUdude** [comment]
Ah, I get it! We only check if `-c jtag2updi` is being used, not what's actually connected to the computer. I'll see what I can do...

**Comment by MCUdude** [comment]
@dl8dtl regaring the added baudrates, @ElTangas had some ideas. Is it OK to you to add even more baud rates? If yes, can rebase one of the commits to not "pollute" the commit history.

From https://github.com/ElTangas/jtag2updi/pull/55

> I was going to do something similar, glad you beat me to it and saved me the effort. Now, extending the jtagice Mk2 protocol is a serious step and we should think hard about it.

> So actually, I was thinking about adding a larger variety of speeds (from the work I was doing on avrdude):
```c
static struct {
long baud;
unsigned char val;
} baudtab[] = {
{ 2400L, PAR_BAUD_2400 },
{ 4800L, PAR_BAUD_4800 },
{ 9600L, PAR_BAUD_9600 },
{ 19200L, PAR_BAUD_19200 },
{ 38400L, PAR_BAUD_38400 },
{ 57600L, PAR_BAUD_57600 },
{ 115200L, PAR_BAUD_115200 },
{ 14400L, PAR_BAUD_14400 },
/* Extension to jtagmkII protocol: extra baud rates, standard series. /
{ 153600L, PAR_BAUD_153600 },
{ 230400L, PAR_BAUD_230400 },
{ 460800L, PAR_BAUD_460800 },
{ 921600L, PAR_BAUD_921600 },
/ Extension to jtagmkII protocol: extra baud rates, binary series. /
{ 128000L, PAR_BAUD_128000 },
{ 256000L, PAR_BAUD_256000 },
{ 512000L, PAR_BAUD_512000 },
{ 1024000L, PAR_BAUD_1024000 },
/ Extension to jtagmkII protocol: extra baud rates, decimal series. */
{ 150000L, PAR_BAUD_150000 },
{ 200000L, PAR_BAUD_200000 },
{ 250000L, PAR_BAUD_250000 },
{ 300000L, PAR_BAUD_300000 },
{ 400000L, PAR_BAUD_400000 },
{ 500000L, PAR_BAUD_500000 },
{ 600000L, PAR_BAUD_600000 },
{ 666666L, PAR_BAUD_666666 },
{ 1000000L, PAR_BAUD_1000000 },
{ 1500000L, PAR_BAUD_1500000 },
{ 2000000L, PAR_BAUD_2000000 },
{ 3000000L, PAR_BAUD_3000000 },
};
```
> Do you think you could add these speeds (even though the fastest ones will most likely not work well) ?
I think all the speeds you propose are included, and some extras to give more choice/room for experimentation to users.

**Comment by dl8dtl** [comment]
> Ah, I get it! We only check if `-c jtag2updi` is being used, not what's actually connected to the computer. I'll see what I can do...

Upon thinking a bit more about it, it makes sense to use your `AVRPART_HAS_PDI | AVRPART_HAS_UPDI` construct, but in the `jtagmkII_initialize()` function, if the device has UPDI and the programmer is not jtag2updi, fail with an appropriate message.

Yes, it's fine to modify your commit for more speed codes.

**Comment by MCUdude** [comment]
Thanks for the feedback!

I've now added more baud rates, and I've also added an error check to make sure the programmer actually supports the target. I'll update my PR on the jtag2updi project to reflect the baud rate changes.

PDI programmer with a UPDI target:
```
avrdude: Version 6.99-20211218
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is "avrdude.conf"
         User configuration file is "/Users/hans/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem14101
         Using Programmer              : jtagmkii
         Overriding Baud Rate          : 115200


.........


         Programmer Type : JTAGMKII
         Description     : Atmel JTAG ICE mkII
         M_MCU hardware version: 1
         M_MCU firmware version: 6.00
         S_MCU hardware version: 1
         S_MCU firmware version: 6.00
         Serial number:          00:00:00:00:00:00
         Vtarget         : 5.0 V
avrdude: jtagmkII_getparm(): bad response to get parameter command: RSP_ILLEGAL_PARAMETER

Error: programmer jtagmkII does not support target ATmega4808

avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you.
```

UPDI programmer with a PDI target:
```
avrdude: Version 6.99-20211218
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is "avrdude.conf"
         User configuration file is "/Users/hans/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem14101
         Using Programmer              : jtag2updi
         Overriding Baud Rate          : 115200


............


         Programmer Type : JTAGMKII_PDI
         Description     : JTAGv2 to UPDI bridge
         M_MCU hardware version: 1
         M_MCU firmware version: 6.00
         S_MCU hardware version: 1
         S_MCU firmware version: 6.00
         Serial number:          00:00:00:00:00:00
         Vtarget         : 5.0 V

Error: programmer jtag2updi does not support target ATxmega128A3U

avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you.
```

**Comment by MCUdude** [comment]
A comment on the last PR where the `Cannot locate "flash" and "boot" memories in description` warning is omitted if the jtag2updi programmer is used.

I after some fiddling I ended up with this code, that works:

```c
if (bootmem == NULL || flashmem == NULL) {
      if (strncmp(ldata(lfirst(pgm->id)), "jtagmkII", strlen("jtagmkII")) == 0) {
        avrdude_message(MSG_INFO, "%s: jtagmkII_initialize(): Cannot locate \"flash\" and \"boot\" memories in description\n",
          progname);
      }
```

My original plan was to add everything to the first if query, but I'm just getting a segment error when doing so. No idea why...

```c
// Doesn't work
if ((bootmem == NULL || flashmem == NULL) && strncmp(ldata(lfirst(pgm->id)), "jtagmkII", strlen("jtagmkII")) == 0) {
      avrdude_message(MSG_INFO, "%s: jtagmkII_initialize(): Cannot locate \"flash\" and \"boot\" memories in description\n",
        progname);

```

The following code results in:
```
avrdude: jtagmkII_setparm(): bad response to set parameter command: RSP_ILLEGAL_PARAMETER
Segmentation fault: 11
```

**Comment by MCUdude** [comment]
@dl8dtl is there anything more that needs to be done in this PR before it can be merged? I've just resolved the newly emerged merge conflict.

**Comment by dl8dtl** [comment]
> @dl8dtl is there anything more that needs to be done in this PR before it can be merged? I've just resolved the newly emerged merge conflict.

Nope, I was about to merge it, but then discovered the documentation changes just got a new conflict.

Thanks for fixing that!

**Comment by yegorich** [comment]
@MCUdude I'm trying to create a PR for wAVR from the old patch (#734 ). This patch was also adding support for UPDI. Can it be this flag (`AVRPART_HAS_UPDI`) is missing in `jtagmkII_close()`:

 ```c
void jtagmkII_close(PROGRAMMER * pgm)
  {
    int status;
    unsigned char buf[1], *resp, c;

    avrdude_message(MSG_NOTICE2, "%s: jtagmkII_close()\n", progname);

    if (pgm->flag & (AVRPART_HAS_PDI | AVRPART_HAS_UPDI)) {
      /* When in PDI/UPDI mode, restart target. */
      buf[0] = CMND_GO;

```

**Comment by MCUdude** [comment]
@yegorich `PGM_FL_IS_PDI` includes UPDI devices too.

Look at how the current jtagmkII_initialize utilizes `PGM_FL_IS_PDI` (which works):
https://github.com/avrdudes/avrdude/blob/1b8b1d69e7eaeb625743a2f87b8ea68619f3a14a/src/jtagmkII.c#L1300-L1328

**Comment by yegorich** [comment]
OK. I see. So we don't need to introduce `#define PGM_FL_IS_UPDI          (0x0008)` as in the wAVR patch.

I just try to understand what parts I don't need from the #734.

**Comment by MCUdude** [comment]
> OK. I see. So we don't need to introduce #define PGM_FL_IS_UPDI (0x0008) as in the wAVR patch.

Nope, not in the current jtag2updi implementation.

Regarding #734, does it _really_ have to create all these new programmers? I mean, It's a pretty comprehensive patch compared to this one. Couldn't it just use the existing programmers, but just provide custom USB VID/PIDs in avrdude.conf?

**Comment by Scotti22221** [comment]
pls can annyone can correct the line 2 of my code. tanks. (fatal error:LiquidCrystal_I2C.h: No such file or directory ) : 

```
#include <Servo.h>
#include <LiquidCrystal_I2C.h>
#include <Keypad.h>
#include <Password.h>

#define buzzer 11

Servo servo;
LiquidCrystal_I2C lcd(0x27, 16, 2);

String newPasswordString; //hold the new password
char newPassword[6]; //charater string of newPasswordString
byte a = 5;
bool value = true;

Password password = Password("0123"); //Enter your password

byte maxPasswordLength = 6;
byte currentPasswordLength = 0;
const byte ROWS = 4; // Four rows
const byte COLS = 4; // Four columns

char keys[ROWS][COLS] = {
  {'D', 'C', 'B', 'A'},
  {'#', '9', '6', '3'},
  {'0', '8', '5', '2'},
  {'*', '7', '4', '1'},
};

byte rowPins[ROWS] = {2, 3, 4, 5};
byte colPins[COLS] = {6, 7, 8, 9};

Keypad keypad = Keypad( makeKeymap(keys), rowPins, colPins, ROWS, COLS );

void setup() {
  Serial.begin(9600);
  pinMode(buzzer, OUTPUT);
  servo.attach(10);
  servo.write(50);
  lcd.init();
  lcd.backlight();
  lcd.setCursor(3, 0);
  lcd.print("WELCOME TO");
  lcd.setCursor(0, 1);
  lcd.print("DOOR LOCK SYSTEM");
  delay(3000);
  lcd.clear();
}

void loop() {
  lcd.setCursor(1, 0);
  lcd.print("ENTER PASSWORD");

  char key = keypad.getKey();
  if (key != NO_KEY) {
    delay(60);
    if (key == 'C') {
      resetPassword();
    } else if (key == 'D') {
      if (value == true) {
        doorlocked();
        value = false;
      } else if (value == false) {
        dooropen();
        value = true;
      }
    } else {
      processNumberKey(key);
    }
  }
}

void processNumberKey(char key) {
  lcd.setCursor(a, 1);
  lcd.print("*");
  a++;
  if (a == 11) {
    a = 5;
  }
  currentPasswordLength++;
  password.append(key);

  if (currentPasswordLength == maxPasswordLength) {
    doorlocked();
    dooropen();
  }
}

void dooropen() {
  if (password.evaluate()) {
    digitalWrite(buzzer, HIGH);
    delay(300);
    digitalWrite(buzzer, LOW);
    servo.write(50);
    delay(100);
    lcd.setCursor(0, 0);
    lcd.print("CORRECT PASSWORD");
    lcd.setCursor(0, 1);
    lcd.print("DOOR OPENED");
    delay(2000);
    lcd.clear();
    a = 5;
  } else {
    digitalWrite(buzzer, HIGH);
    delay(200);
    digitalWrite(buzzer, LOW);
    delay(200);
    digitalWrite(buzzer, HIGH);
    delay(200);
    digitalWrite(buzzer, LOW);
    delay(200);
    digitalWrite(buzzer, HIGH);
    delay(200);
    digitalWrite(buzzer, LOW);
    delay(200);
    lcd.setCursor(0, 0);
    lcd.print("WRONG PASSWORD!");
    lcd.setCursor(0, 1);
    lcd.print("PLEASE TRY AGAIN");
    delay(2000);
    lcd.clear();
    a = 5;
  }
  resetPassword();
}

void resetPassword() {
  password.reset();
  currentPasswordLength = 0;
  lcd.clear();
  a = 5;
}

void doorlocked() {
  if (password.evaluate()) {
    digitalWrite(buzzer, HIGH);
    delay(300);
    digitalWrite(buzzer, LOW);
    servo.write(110);
    delay(100);
    lcd.setCursor(0, 0);
    lcd.print("CORRECT PASSWORD");
    lcd.setCursor(2, 1);
    lcd.print("DOOR LOCKED");
    delay(2000);
    lcd.clear();
    a = 5;
  } else {
    digitalWrite(buzzer, HIGH);
    delay(200);
    digitalWrite(buzzer, LOW);
    delay(200);
    digitalWrite(buzzer, HIGH);
    delay(200);
    digitalWrite(buzzer, LOW);
    delay(200);
    digitalWrite(buzzer, HIGH);
    delay(200);
    digitalWrite(buzzer, LOW);
    delay(200);
    lcd.setCursor(0, 0);
    lcd.print("WRONG PASSWORD!");
    lcd.setCursor(0, 1);
    lcd.print("PLEASE TRY AGAIN");
    delay(2000);
    lcd.clear();
    a = 5;
  }
  resetPassword();
}
```

**Pull request merged**
