### PR TITLE
Pad pages with input file contents before avr_write()

### LINKED ISSUE #1050: -U writes sometimes more bytes to flash/memory than input file has
**Problem.** -U writes sometimes more bytes to flash/memory than input file has. This happens when
 - The programmer provides a paged write routine and
 - The the input file leaves memory pages partially filled and
 - The memory does not look like an NOR-memory, which is true for 
     + EEPROM in general
     + For XMEGA flash (because AVRDUDE uses a `pgm->page_erase()` before `pgm->page_write()`)
     + For `is_bootloader` programmers that carry out SPM erase before a page write

**Solution.** The culprit is `avr_write()` that uses paged write routines when possible and assumes all memories look like NOR-memory (for which writing 0xff is a NOP). For now, I suggest always reading back the unset bytes in partially filled memory pages before the paged write. This is not necessary for flash that looks like NOR-memory, but there is (currently) no way of knowing which programmer/part combination makes flash look like  NOR-memory or not: Sometimes bootloaders pretend to be following  a certain protocol, but don't (think optiboot and `-c arduino` or  Trinket/Gemma that pose as `-c usbtiny`). The small delay for read-back of partially filled memory pages is a price worth paying to ensure AVRDUDE does not alter memory outside the input file.

**Example.** Use your own favourite programmer instead of ... and try below. Notice the `echo -n H` input should write one byte, but four bytes are written as evidenced by the three 0xff at addresses 1..3.

```
$ yes 'hello, world!!!' | head -2 | avrdude -qqp m328p -c ... -U eeprom:w:-:r && echo OK
OK

$ echo d ee 0 32 | avrdude -qqp m328p -c ... -t
avrdude> d ee 0 32
0000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

$ echo -n H | avrdude -qp m328p -c ... -U eeprom:w:-:r

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file "<stdin>"
avrdude: writing eeprom (1 bytes):
avrdude: 1 bytes of eeprom written
avrdude: verifying eeprom memory against -:
avrdude: 0 bytes of eeprom verified

avrdude done.  Thank you.

$ echo d ee 0 32 | avrdude -qqp m328p -c ... -t
avrdude> d ee 0 32
0000  48 ff ff ff 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |H...o, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |
```

### PR DESCRIPTION
**Pull request by stefanrueger**
Supposed to fix #1050 (not all memory is nor memory)

### CODE REVIEW

**Comment by stefanrueger** [comment]
This PR would benefit from tests. It is not specific to any one device. The problem (and repair) should appear/work in all parts with paged r/w for EEPROM and for all part-programmer combos using page erase (bootloaders, xMEGA etc) for flash. As such it is quite a high-level bug. Issue #1050 has examples of the problem.

**Comment by mcuee** [comment]
@stefanrueger 

Somehow it does not work for ATTiny88 using usbasp.
* https://github.com/avrdudes/avrdude/issues/1050#issuecomment-1325859812

**Comment by mcuee** [comment]
It does not seem to work for ATmega328P either. Strange.
```
$  yes 'hello, world!!!' | head -2 | ./avrdude_pr1188 -qqp m328p -c usbasp -U eeprom:w:-:r && echo OK
OK

$ echo d ee 0 32 | ./avrdude_pr1188 -qqp m328p -c usbasp -t
avrdude> d ee 0 32
>>> d ee 0 32
0000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude>
avrdude>

$ echo -n H | ./avrdude_pr1188 -qp m328p -c usbasp -U eeprom:w:-:r

avrdude_pr1188: AVR device initialized and ready to accept instructions
avrdude_pr1188: device signature = 0x1e950f (probably m328p)
avrdude_pr1188: reading input file <stdin> for eeprom
                with 1 byte in 1 section within [0, 0]
                using 1 page and 3 pad bytes
avrdude_pr1188: writing 1 byte eeprom ...
avrdude_pr1188: 1 byte of eeprom written
avrdude_pr1188: verifying eeprom memory against <stdin>
avrdude_pr1188: 1 byte of eeprom verified

avrdude_pr1188 done.  Thank you.

$ echo d ee 0 32 | ./avrdude_pr1188 -qqp m328p -c usbasp -t
avrdude> d ee 0 32
>>> d ee 0 32
0000  48 ff ff ff 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |H...o, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude>
avrdude>

```

**Comment by stefanrueger** [comment]
@mcuee Thanks for testing; there was an error in the patch preventing the pad bytes to be read in some programmers, it should work now

**Comment by mcuee** [comment]
@stefanrueger 

Yes now it works fine. Tested under Linux.
```
mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ yes 'hello, world!!!' | head -2 | ./avrdude_pr1188v1
 -qqp m328p -c urclock -P /dev/ttyUSB0 -U eeprom:w:-:r && echo OK
OK

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ echo d ee 0 32 | ./avrdude_pr1188v1 -qqp m328p -c urclock
 -P /dev/ttyUSB0 -qqt
avrdude> d ee 0 32
0000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude> 
avrdude> 

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ echo -n H | ./avrdude_pr1188v1 -qp m328p -c urclock -P /dev/ttyUSB0 -U eeprom:w:-:r

avrdude_pr1188v1: AVR device initialized and ready to accept instructions
avrdude_pr1188v1: device signature = 0x1e950f (probably m328p)
avrdude_pr1188v1: reading input file <stdin> for eeprom
                  with 1 byte in 1 section within [0, 0]
                  using 1 page and 3 pad bytes
avrdude_pr1188v1: writing 1 byte eeprom ...
avrdude_pr1188v1: 1 byte of eeprom written
avrdude_pr1188v1: verifying eeprom memory against <stdin>
avrdude_pr1188v1: 1 byte of eeprom verified

avrdude_pr1188v1 done.  Thank you.

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ echo d ee 0 32 | ./avrdude_pr1188v1 -qqp m328p
-c urclock -P /dev/ttyUSB0 -qqt
avrdude> d ee 0 32
0000  48 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |Hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude> 
avrdude>

```

**Comment by mcuee** [comment]
> Ahh, `urclock` has solved this on the programmer level. It was still a problem for other programmers (arduino, usbasp, etc).

Thanks. usbasp is okay now. Tested under Windows.
```
$ yes 'hello, world!!!' | head -2 | ./avrdude_pr1188v1 -qqp m328p -c usbasp -U eeprom:w:-:r && echo OK
OK

xiaof@LAPTOP-913SIMUD MINGW64 /c/work/avr/avrdude_test/avrdude_bin
$ echo d ee 0 32 | ./avrdude_pr1188v1 -qqp m328p -c usbasp -t
avrdude> d ee 0 32
>>> d ee 0 32
0000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude>
avrdude>
xiaof@LAPTOP-913SIMUD MINGW64 /c/work/avr/avrdude_test/avrdude_bin
$ echo -n H | ./avrdude_pr1188v1 -qp m328p -c usbasp -U eeprom:w:-:r

avrdude_pr1188v1: AVR device initialized and ready to accept instructions
avrdude_pr1188v1: device signature = 0x1e950f (probably m328p)
avrdude_pr1188v1: reading input file <stdin> for eeprom
                  with 1 byte in 1 section within [0, 0]
                  using 1 page and 3 pad bytes
avrdude_pr1188v1: writing 1 byte eeprom ...
avrdude_pr1188v1: 1 byte of eeprom written
avrdude_pr1188v1: verifying eeprom memory against <stdin>
avrdude_pr1188v1: 1 byte of eeprom verified

avrdude_pr1188v1 done.  Thank you.

$ echo d ee 0 32 | ./avrdude_pr1188 -qqp m328p -c usbasp -t
bash: ./avrdude_pr1188: No such file or directory

$ echo d ee 0 32 | ./avrdude_pr1188v1 -qqp m328p -c usbasp -t
avrdude> d ee 0 32
>>> d ee 0 32
0000  48 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |Hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude>
avrdude>

```

**Comment by mcuee** [comment]
`-c arduino` is also okay now.
```
$ yes 'hello, world!!!' | head -2 | ./avrdude_pr1188v1 -qqp m328p -c arduino -P COM10 -U eeprom:w:-:r && echo OK
OK

$ echo d ee 0 32 | ./avrdude_pr1188v1 -qqp m328p -c arduino -P COM10 -t
avrdude> d ee 0 32
>>> d ee 0 32
0000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude>
avrdude>

$ echo -n H | ./avrdude_pr1188v1 -qp m328p -c arduino -P COM10 -U eeprom:w:-:r

avrdude_pr1188v1: AVR device initialized and ready to accept instructions
avrdude_pr1188v1: device signature = 0x1e950f (probably m328p)
avrdude_pr1188v1: reading input file <stdin> for eeprom
                  with 1 byte in 1 section within [0, 0]
                  using 1 page and 3 pad bytes
avrdude_pr1188v1: writing 1 byte eeprom ...
avrdude_pr1188v1: 1 byte of eeprom written
avrdude_pr1188v1: verifying eeprom memory against <stdin>
avrdude_pr1188v1: 1 byte of eeprom verified

avrdude_pr1188v1 done.  Thank you.


$ echo d ee 0 32 | ./avrdude_pr1188v1 -qqp m328p -c arduino -P COM10 -t
avrdude> d ee 0 32
>>> d ee 0 32
0000  48 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |Hello, world!!! |
0010  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 21 21 21 0a  |hello, world!!! |

avrdude>
avrdude>

```

**Comment by stefanrueger** [comment]
@mcuee Perfect! Thanks for confirming (and for smoking out a problem earlier) - So, I'd say this PR is good to go.

**Comment by mcuee** [comment]
> @mcuee Perfect! Thanks for confirming (and for smoking out a problem earlier) - So, I'd say this PR is good to go.

I agree that this PR is good to go.

**Pull request merged**
