### PR TITLE
Hint at -xeepromrw option in EEPROM error messages

### PR DESCRIPTION
**Pull request by stefanrueger**
Addresses Issue #1224

### CODE REVIEW

**Comment by mcuee** [comment]
This is good to go. Tested to be good.

**Comment by mcuee** [comment]
@stefanrueger 

* https://github.com/avrdudes/avrdude/issues/1224#issuecomment-1356388626

After some thought, I think the following two are worth to be added as they are the few EEPROM supported Optiboot bootloader for the Uno.
```
    { 1024, 1, 0x6ca0f37b, 0x21124cde }, // bigboot_328p_8v3_uno_ch340_clone.hex
    { 1024, 1, 0xae42ebb8, 0xeb4b1b71 }, // bigboot_328p_8v0.hex 
```

**Comment by stefanrueger** [comment]
@mcuee and @MCUdude: Have added the hashes as requested; for @MCUdude's I have put them in a .h file to get "out of the way" in the .c file (also so you can modify them). Found it too much hassle to remove the duplicates as they occupy less than 1k space, but if you want, feel free to push a commit onto this PR.

Would like to merge Wednesday (European) evening to not delay the release.

**Comment by MCUdude** [comment]
As a last Optiboot flash fix, could you add the following hashes to the list as well?

```
    {  512, 0, 0x540e745c, 0x3eacc51c }, // optiboot_flash_atmega165a_UART0_57600_8000000L_B5.hex
    {  512, 0, 0x540e745c, 0x7fd86c1f }, // optiboot_flash_atmega165a_UART0_38400_8000000L_B5.hex
    {  512, 0, 0xfe267731, 0xe57f0c05 }, // optiboot_flash_atmega165a_UART0_9600_1000000L_B5.hex
    {  512, 0, 0x540e745c, 0x68a49c5a }, // optiboot_flash_atmega165a_UART0_115200_20000000L_B5.hex
    {  512, 0, 0x540e745c, 0xd3efd1b5 }, // optiboot_flash_atmega165a_UART0_115200_16000000L_B5.hex
```

**Comment by stefanrueger** [comment]
Done

> @MCUdude I've been wondering why your (8 MHz, 57600 baud) bootloaders are different from (16 MHz, 115200 baud) bootloaders, but I now suspect that optiboot flashes the LED for a while with a certain frequency - and that therefore the code will be different for these two bootloader versions. For the comms alone the code would be identical.

The bootloader for ATmega162 16 MHz/115200 baud is identical to 8 MHz/57600 baud, though:
```
$ grep 0x8785ab7e src/urclock_hash.h 
    {  512, 0, 0x7426b344, 0x8785ab7e }, // optiboot_flash_atmega162_UART1_57600_8000000L_B0.hex
    {  512, 0, 0x7426b344, 0x8785ab7e }, // optiboot_flash_atmega162_UART1_115200_16000000L_B0.hex
$ grep 0x9859287c src/urclock_hash.h 
    {  512, 0, 0xda8d468f, 0x9859287c }, // optiboot_flash_atmega162_UART0_57600_8000000L_B0.hex
    {  512, 0, 0xda8d468f, 0x9859287c }, // optiboot_flash_atmega162_UART0_115200_16000000L_B0.hex
```
Makes me wonder whether these flash the LED or whether there is another reason why your (8 MHz, 57600 baud) bootloaders are different from the (16 MHz, 115200 baud) ones.

**Comment by MCUdude** [comment]
IIRC, the ATmega162 was a special case. It's the only target where the pre-compiled bootloader doesn't toggle a pin after a reset pulse. If I enabled this, the bootloader simply wouldn't work. I have no idea why and didn't have time to investigate when I found the bug.

**Comment by stefanrueger** [comment]
Ahh that explains why those bootloader variants are identical (no LED flashing).

Off topic: @MCUdude Could you help me to test the **urboot** bootloaders for ATmega162 if they are difficult elsewhere; also ATmega161 and ATmega163, as the latter two do not have an UART_SR**C** and I needed to do the initialisation different for these to get the bootloader compiled? I don't have either part.

**Comment by MCUdude** [comment]
> Off topic: @MCUdude Could you help me to test the urboot bootloaders for ATmega162 if they are difficult elsewhere; also ATmega161 and ATmega163, as the latter two do not have an UART_SRC and I needed to do the initialisation different for these to get the bootloader compiled? I don't have either part.

I can help out with the ATmega162, but I don't own a 161 or a 163. Let me know which bootloader(s) and clock speed(s) you want to be tested.

**Comment by stefanrueger** [comment]
| help out with the ATmega162

Great! Just one (doesn't matter which one) of the ATmega162 autobaud ones would be fab: https://github.com/stefanrueger/urboot/blob/main/bootloaders/atmega162/autobaud/README.md

**Comment by mcuee** [comment]
Great. Now everything is working fine now. Tested with the two hex files and MiniCore default bootloader hex file for ATmega328P.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1226v1 -c urclock -P COM18 -p m328p -xshowall

avrdude_pr1226v1: AVR device initialized and ready to accept instructions
0000ffffffff 0000-00-00 00.00  application 0 store 0 meta 0 boot 1024 o8.3 -es-h-r-- vector 0 (RESET) ATmega328P

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1226v1 -c urclock -P COM18 -p m328p -xshowall

avrdude_pr1226v1: AVR device initialized and ready to accept instructions
0000ffffffff 0000-00-00 00.00  application 0 store 0 meta 0 boot 1024 o8.0 -es-h-r-- vector 0 (RESET) ATmega328P

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1226v1 -c urclock -P COM18 -p m328p -xshowall

avrdude_pr1226v1: AVR device initialized and ready to accept instructions
0 0000-00-00 00.00  application 0 store 0 meta 0 boot 512 o8.0 --s-h-r-- vector 0 (RESET) ATmega328P

```

**Comment by MCUdude** [comment]
@stefanrueger I gave Urboot a quick try on the ATmega162. I flashed the [urboot_atmega162_autobaud_ee_lednop_fr_ce_ur_vbl.hex](https://raw.githubusercontent.com/stefanrueger/urboot/main/bootloaders/atmega162/autobaud/urboot_atmega162_autobaud_ee_lednop_fr_ce_ur_vbl.hex) file, and so far everything seems to work great. I can read and write to flash, erase and read metadata. Auto baud works perfect too!

**Comment by stefanrueger** [comment]
@MCUdude Brilliant: thanks for checking. Always reassuring that non-standard parts work, too.

**Pull request merged**
