### PR TITLE
Ignore `-s` flag as safemode is no longer supported

### LINKED ISSUE #1032: Unknown option '-s' on command line
The so-called "safe mode" feature was removed in #859 and with it the option parsing for the `-s` flag.  That causes problems with scripts calling avrdude after upgrading to version 7.0.  A well-behaved command line program should accept, but ignore, deprecated options instead of choking on them.

### PR DESCRIPTION
**Pull request by MCUdude**
Resolves #1032

### CODE REVIEW

**Comment by acolomb** [comment]
Thanks for the quick fix!

Shouldn't these still be mentioned in `src/doc/avrdude.texi` and `src/avrdude.1` as deprecated options?  Just dropping every note about them has greater potential for confusion I would think.

**Review by dl8dtl — APPROVED** [review]

**Comment by dl8dtl** [comment]
Mentioning them in avrdude.1 and avrdude.texi might be fine, though I really think their only merit is to cater old scripts. Scripts usually don't read documentation anyway. ;-)

**Comment by acolomb** [comment]
Good argument ;-) Just thought I'd mention it in case nobody had thought about the docs yet.

**Comment by stefanrueger** [comment]
I like @acolomb's considered suggestion on documentation (never hurts).

**Comment by MCUdude** [comment]
I've updated the documentation! `-s` and `-u` are now mentioned.

**Review by stefanrueger — APPROVED** [review]
Perfect. Good to go.

**Pull request merged**
