### PR TITLE
Fix shell exit value when chip erase is delayed to next flash write

### LINKED ISSUE #1192: `&& echo OK` does not work after `-c urclock`
Reference:
* https://github.com/avrdudes/avrdude/pull/1171#issuecomment-1325151678

It is strange that `&& echo OK` does not work after `-c urclock`. No pronlems with `-c arduino`.

It is the same under Linux.
```
mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ ./avrdude -c arduino -P /dev/ttyUSB0 -p m328p
 -U ./Blink.ino.standard.hex -qq && echo OK
OK

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ ./avrdude -c urclock -P /dev/ttyUSB0 -p m328p
 -U ./Blink.ino.standard.hex -xbootsize=512 -qq && echo OK

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ 
```

### PR DESCRIPTION
**Pull request by stefanrueger**
Fixes #1192

### CODE REVIEW

**Comment by stefanrueger** [comment]
I notice the github runners fail here, but I cannot see why they would do so?

**Comment by stefanrueger** [comment]
https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171

D:\a\avrdude\avrdude\src\term.c(36,1): fatal  error C1083: Cannot open include file: 'readline/readline.h': No such file or directory [D:\a\avrdude\avrdude\build\src\avrdude.vcxproj

**Comment by mcuee** [comment]
> https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171
> 
> D:\a\avrdude\avrdude\src\term.c(36,1): fatal error C1083: Cannot open include file: 'readline/readline.h': No such file or directory [D:\a\avrdude\avrdude\build\src\avrdude.vcxproj

@stefanrueger 

I noticed that too. And now I know the problem. Somehow now they have Strawberry Perl installed and that has `libreadline.a` in the PATH. CMake wrongly detects that MSVC build also has GNU Readline.

You can see the configure log.
```
Run cmake -A x64 -D DEBUG_CMAKE=1 -D CMAKE_SYSTEM_VERSION=11 -D CMAKE_C_FLAGS_RELWITHDEBINFO="/MT /GL /Zi /O[2](https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171#step:4:2) /Ob1 /DNDEBUG" -D CMAKE_CXX_FLAGS_RELWITHDEBINFO="/MT /GL /Zi /O2 /Ob1 /DNDEBUG" -D CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO="/DEBUG /INCREMENTAL:NO /LTCG /OPT:REF /OPT:ICF" -D CMAKE_BUILD_TYPE=RelWithDebInfo -D USE_EXTERNAL=1 -B build
  cmake -A x64 -D DEBUG_CMAKE=1 -D CMAKE_SYSTEM_VERSION=11 -D CMAKE_C_FLAGS_RELWITHDEBINFO="/MT /GL /Zi /O2 /Ob1 /DNDEBUG" -D CMAKE_CXX_FLAGS_RELWITHDEBINFO="/MT /GL /Zi /O2 /Ob1 /DNDEBUG" -D CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO="/DEBUG /INCREMENTAL:NO /LTCG /OPT:REF /OPT:ICF" -D CMAKE_BUILD_TYPE=RelWithDebInfo -D USE_EXTERNAL=1 -B build
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    BUILD_TYPE: RelWithDebInfo
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 11.
-- The C compiler identification is MSVC 19.[3](https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171#step:4:3)3.31631.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/1[4](https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171#step:4:4).33.31629/bin/HostX64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: C:/Program Files/Git/bin/git.exe (found version "2.38.1.windows.1") 
-- Found FLEX: D:/a/avrdude/avrdude/winflexbison/win_flex.exe (found version "2.6.4") 
-- Found BISON: D:/a/avrdude/avrdude/winflexbison/win_bison.exe (found version "3.7.4")
-- Fetching external libraries, please wait...
-- The CXX compiler identification is MSVC 19.33.31631.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/HostX64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using external library 'libelf'
-- Using external library 'libusb'
-- Using external library 'libhidapi'
-- Using external library 'libftdi'
-- Configuration summary:
-- ----------------------
-- CMAKE_HOST_SYSTEM: Windows-10.0.20348
-- CMAKE_SYSTEM: Windows-11
-- CMAKE_FIND_ROOT_PATH: 
-- CMAKE_C_COMPILER: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/HostX64/x64/cl.exe
-- CONFIG_DIR: C:/Program Files/avrdude/etc
-- AVRDUDE_FULL_VERSION: 7.0-20221123 (c[5](https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171#step:4:5)dc051)
-- USE_EXTERNAL: 1
-- USE_LIBUSBWIN[32](https://github.com/avrdudes/avrdude/actions/runs/3535253524/jobs/5935583171#step:4:33): OFF
-- HAVE_LIBELF: 1
-- HAVE_LIBUSB: 1
-- HAVE_LIBUSB_1_0: HAVE_LIBUSB_1_0-NOTFOUND
-- HAVE_LIBUSB_WIN32: HAVE_LIBUSB_WIN32-NOTFOUND
-- HAVE_LIBHID: HAVE_LIBHID-NOTFOUND
-- HAVE_LIBHIDAPI: 1
-- HAVE_LIBFTDI: 1
-- HAVE_LIBFTDI1: HAVE_LIBFTDI1-NOTFOUND
-- HAVE_LIBREADLINE: C:/Strawberry/c/lib/libreadline.a
-- HAVE_LIBELF_H: 1
-- HAVE_LIBELF_LIBELF_H: 
-- HAVE_USB_H: 
-- HAVE_LUSB0_USB_H: 1
-- HAVE_LIBUSB_H: 
-- HAVE_LIBUSB_1_0_LIBUSB_H: 
-- HAVE_HIDAPI_HIDAPI_H: 1
-- LIBUSB_COMPAT_DIR: 
-- ----------------------
-- DO HAVE    libelf
-- DO HAVE    libusb
-- DON'T HAVE libusb_1_0
-- DO HAVE    libhidapi
-- DO HAVE    libftdi
-- DON'T HAVE libftdi1
-- DO HAVE    libreadline
-- DISABLED   doc
-- DISABLED   parport
-- DISABLED   linuxgpio
-- DISABLED   linuxspi

```

**Comment by mcuee** [comment]
@mariusgreuel 
Hopefully you will have some time to see how to detect GNU Readline a bit more robust in CMake.

**Comment by mcuee** [comment]
@stefanrueger 

This PR itself is good to go.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1188 -c usbasp -P COM5 -p m328p  -U .\atmega328p_16mhz_115200bps_ee_led+b1_fr_ce_ur_vbl.hex -qq && echo OK
OK

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1188 -c urclock -P COM5 -p m328p
  -U .\Blink_Uno.ino.hex -qq && echo OK
OK
```

**Comment by mcuee** [comment]
@stefanrueger 

As a workaround, I have created PR #1196 to disable GNU Readline for MSVC build.

**Pull request merged**
