### PR TITLE
Smallest possible fix for PL2303HX

### PR DESCRIPTION
**Pull request by dbuchwald**
This is all that is needed to get SerialUPDI to work with PL2303HX (and work better overall, in fact...).

### CODE REVIEW

**Comment by MCUdude** [comment]
I haven't yet tested it on actual hardware, but when building it I'm getting warnings. Would be nice if you could fix this:

```
  CCLD     avrdude
ld: warning: directory not found for option '-FCoreFoundation'
  CC       libavrdude_la-jtag3.lo
  CC       libavrdude_la-ser_avrdoper.lo
  CC       libavrdude_la-stk500v2.lo
  CC       libavrdude_la-updi_link.lo
updi_link.c:206:34: warning: passing 'char [1]' to parameter of type 'unsigned char *' converts between pointers to integer types with different
      sign [-Wpointer-sign]
  return updi_physical_send(pgm, init_buffer, 1);
                                 ^~~~~~~~~~~
updi_link.c:90:65: note: passing argument to parameter 'buf' here
static int updi_physical_send(PROGRAMMER * pgm, unsigned char * buf, size_t len)
```

**Comment by dbuchwald** [comment]
Thanks for pointing it out. Somehow my Linux box doesn't complain about this issue. Not that it matters, but you are right, it should be fixed.

**Comment by dl8dtl** [comment]
Confirm it works with the PL2303 on FreeBSD.

**Comment by dl8dtl** [comment]
… as well as on my MacOS (sorry Hans ;-).
```
% ./build_darwin/src/avrdude -c serialupdi -P /dev/cu.usbserial-1410 -p avr128db48 -t 

avrdude: UPDI link initialization OK
avrdude: Device is in SLEEP mode
avrdude: NVM type 2: 24-bit, word oriented write
avrdude: Entering NVM programming mode
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
avrdude> d fl
>>> d fl 
0000  0c 94 7a 00 0c 94 99 00  0c 94 99 00 0c 94 99 00  | .z. ... ... ...|
0010  0c 94 99 00 0c 94 99 00  0c 94 99 00 0c 94 99 00  | ... ... ... ...|
0020  0c 94 99 00 0c 94 99 00  0c 94 99 00 0c 94 0c 01  | ... ... ... . .|
0030  0c 94 99 00 0c 94 99 00  0c 94 99 00 0c 94 99 00  | ... ... ... ...|

avrdude> d fuses
>>> d fuses 
0000  00 00 00 ff ff c0 08 00  00                       |.........       |

avrdude> d prodsig
>>> d prodsig 
0000  ff fb 03 0d 0d ff ff ff  ff ff ff ff ff 42 05 01  |...  ........B..|
0010  19 60 00 55 11 01 23 01  49 00 00 00 00 ff ff ff  |.`.U..#.I.......|
0020  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0030  ff ff ff ff ff ff ff ff  ff ff ff ff ff 74 69 e3  |.............ti.|

avrdude> q
>>> q 
avrdude: Leaving NVM programming mode

avrdude done.  Thank you.
```

**Pull request merged**
