### PR TITLE
Remove comment and URL for arduino-ft232r programmer

### PR DESCRIPTION
**Pull request by stefanrueger**
Normally I would want to *add* comments and URLs to programmer definitions, but in this case the URL is not accessible in EEA and the UK (and the bootloader path element makes me doubt it is on topic). Anyone know better URLs for this?

Screenshot from 2023-06-21 16-21-09

### CODE REVIEW

**Comment by MCUdude** [comment]
I think it's OK to remove the URL I think

If you look at the Arduino Diecimila schematic, you can see that there is a four-pin header where you can connect things to the UART handshake likes. I'm sure the website describes how to connect these lines to the on-board ISP connector.

**Comment by stefanrueger** [comment]
>  website describes how to connect these lines to the on-board ISP connector

Thanks, do you have a better URL?

**Comment by mcuee** [comment]
I agree to remove the URL. The website is anyway not valid any more.

Here is the output from the website in Japanese.
```
サービス終了のお知らせ
いつもYahoo! JAPANのサービスをご利用いただき誠にありがとうございます。
お客様がアクセスされたサービスは本日までにサービスを終了いたしました。
今後ともYahoo! JAPANのサービスをご愛顧くださいますよう、よろしくお願いいたします。
```

Google English Translation:
```
Notice of service termination
Thank you for using Yahoo! JAPAN services.
The service you accessed has been terminated as of today.
We appreciate your continued patronage of Yahoo! JAPAN services.
```

**Comment by mcuee** [comment]
> If you look at the Arduino Diecimila schematic, you can see that there is a four-pin header where you can connect things to the UART handshake likes. I'm sure the website describes how to connect these lines to the on-board ISP connector.

@MCUdude 

Yes I can see the four-pin header mentioned in the schematics.
https://docs.arduino.cc/retired/boards/arduino-diecimila
https://www.arduino.cc/en/uploads/Main/Arduino-Diecimila-schematic.pdf

The following website mentioned the connection scheme.
https://make.kosakalab.com/arduino/bootloader/index_en.html

It mentions the following `diecimila` programmer, 
```
#arduino diecimila
programmer
  id="diecimila";
  desc = "FT232R Synchronous BitBang";
  type = ft245r;
  miso = 3;  # CTS X3(1)
  sck = 5;  # DSR X3(2)
  mosi = 6;  # DCD X3(3)
  reset = 7;  # RI X3(4)
;
```

Which is basically the same as `arduino-ft232r`.
```
#------------------------------------------------------------
# arduino-ft232r
#------------------------------------------------------------

# see http://www.geocities.jp/arduino_diecimila/bootloader/index_en.html
# Note: pins are numbered from 1!

programmer
    id                     = "arduino-ft232r";
    desc                   = "Arduino: FT232R connected to ISP";
    type                   = "ftdi_syncbb";
    prog_modes             = PM_TPI | PM_ISP;
    connection_type        = usb;
    reset                  = 7;  # RI  X3(4)
    sck                    = 5;  # DSR X3(2)
    sdo                    = 6;  # DCD X3(3)
    sdi                    = 3;  # CTS X3(1)
;
```

**Comment by mcuee** [comment]
Adafruit has similar documentation but the pin out is different.
https://learn.adafruit.com/ftdi-friend/programming-blank-avrs

**Comment by stefanrueger** [comment]
@mcuee Thanks. Have updated the description accordingly

**Comment by mcuee** [comment]
Now this PR is good to go.

**Pull request merged**
