### PR TITLE
Provide a programmer dryrun that emulates programming

### PR DESCRIPTION
**Pull request by stefanrueger**
There is no connection to a physical programmer or chip needed; this to test the workings of AVRDUDE (could be used for CI) and/or check out factory settings of fuses:
```
$ avrdude -qqp m328p -c dryrun -U lfuse:r:-:h
0x62

$ avrdude -qqp m328p -c dryrun -t
avrdude> read flash 0 32
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
0010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> read hfuse
0000  d9                                                |.               |
avrdude> read signature
0000  1e 95 0f                                          |...             |
avrdude> read calibration
0000  55                                                |U               |
avrdude> write cal 0 0x56
avrdude error: cannot write to write-protected memory ATmega328P calibration
avrdude error: (write) error writing 0x56 at 0x00000, rc=-1
                write operation not supported on memory type calibration
```

### CODE REVIEW

**Comment by stefanrueger** [comment]
Also emulates that flash memory looks like NOR-memory, so overwriting flash with two files (`blink.hex` and `blank.hex`) without erasing flash in between is bound to fail:

```
$ avrdude -qqp m328p -U blink.hex -U blank.hex -c dryrun 
avrdude warning: verification mismatch
        device 0x33 != input 0xff at addr 0x0000 (error)
avrdude error: verification mismatch
```

**Comment by mcuee** [comment]
Great. This is a very nice feature enhancement to avrdude. I will carry out tests over the weekend.

**Comment by MCUdude** [comment]
Awesome, I'll give it a spin this weekend!

Thanks for yet another great PR @stefanrueger!

**Comment by mcuee** [comment]
Looks pretty neat.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c dryrun  -p m4809
avrdude_pr1347: AVR device initialized and ready to accept instructions
avrdude_pr1347: device signature = 0x1e9651 (probably m4809)

avrdude_pr1347 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c dryrun  -p m4809 -U fuses:r:-:h
avrdude_pr1347: AVR device initialized and ready to accept instructions
avrdude_pr1347: device signature = 0x1e9651 (probably m4809)
avrdude_pr1347: reading fuses memory ...
avrdude_pr1347: writing output file <stdout>
0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff

avrdude_pr1347 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c dryrun  -p m4809 -qqt
avrdude> dump fuses
0000  ff ff ff ff ff ff ff ff  ff                       |.........       |
avrdude> sig
Device signature = 0x1e9651
avrdude> read flash 0 0x10
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> write flash 0 0xaa 0x55 0xaa
avrdude> flush
avrdude> read flash 0 0x10
0000  aa 55 aa ff ff ff ff ff  ff ff ff ff ff ff ff ff  |.U..............|
avrdude> read eeprom 0 0x10
0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
avrdude> write eeprom 0 0xaa 0x55 0xaa
avrdude> flush
avrdude> read eeprom 0 0x10
0000  aa 55 aa ff ff ff ff ff  ff ff ff ff ff ff ff ff  |.U..............|
avrdude> quit
```

**Comment by mcuee** [comment]
@stefanrueger 
`dryrun` is probably the fastest programmer for avrdude. :-)
But from the following results, we will know it is a bit against the physics. :-)

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c dryrun
  -p m2560 -U .\hex3\0xaa_256KB.hex
avrdude_pr1347: AVR device initialized and ready to accept instructions
avrdude_pr1347: device signature = 0x1e9801 (probably m2560)
avrdude_pr1347: Note: flash memory has been specified, an erase cycle will be performed.
                To disable this feature, specify the -D option.
avrdude_pr1347: erasing chip
avrdude_pr1347: reading input file .\hex3\0xaa_256KB.hex for flash
                with 262144 bytes in 1 section within [0, 0x3ffff]
                using 1024 pages and 0 pad bytes
avrdude_pr1347: writing 262144 bytes flash ...
Writing | ################################################## | 100% 0.26 s
avrdude_pr1347: 262144 bytes of flash written
avrdude_pr1347: verifying flash memory against .\hex3\0xaa_256KB.hex
Reading | ################################################## | 100% 0.26 s
avrdude_pr1347: 262144 bytes of flash verified

avrdude_pr1347 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c dryrun
  -p m2560 -U .\hex3\0xaa_128KB.hex
avrdude_pr1347: AVR device initialized and ready to accept instructions
avrdude_pr1347: device signature = 0x1e9801 (probably m2560)
avrdude_pr1347: Note: flash memory has been specified, an erase cycle will be performed.
                To disable this feature, specify the -D option.
avrdude_pr1347: erasing chip
avrdude_pr1347: reading input file .\hex3\0xaa_128KB.hex for flash
                with 131072 bytes in 1 section within [0, 0x1ffff]
                using 512 pages and 0 pad bytes
avrdude_pr1347: writing 131072 bytes flash ...
Writing | ################################################## | 100% 0.26 s
avrdude_pr1347: 131072 bytes of flash written
avrdude_pr1347: verifying flash memory against .\hex3\0xaa_128KB.hex
Reading | ################################################## | 100% 0.26 s
avrdude_pr1347: 131072 bytes of flash verified

avrdude_pr1347 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c dryrun
  -p m2560 -U .\hex3\0xaa_32KB.hex
avrdude_pr1347: AVR device initialized and ready to accept instructions
avrdude_pr1347: device signature = 0x1e9801 (probably m2560)
avrdude_pr1347: Note: flash memory has been specified, an erase cycle will be performed.
                To disable this feature, specify the -D option.
avrdude_pr1347: erasing chip
avrdude_pr1347: reading input file .\hex3\0xaa_32KB.hex for flash
                with 30720 bytes in 1 section within [0, 0x77ff]
                using 120 pages and 0 pad bytes
avrdude_pr1347: writing 30720 bytes flash ...
Writing | ################################################## | 100% 0.26 s
avrdude_pr1347: 30720 bytes of flash written
avrdude_pr1347: verifying flash memory against .\hex3\0xaa_32KB.hex
Reading | ################################################## | 100% 0.27 s
avrdude_pr1347: 30720 bytes of flash verified

avrdude_pr1347 done.  Thank you.
```

**Comment by mcuee** [comment]
@stefanrueger 

Just wondering if we can have a new `-xdryrun` for programmers as well.

I know there is a `-n` command but the output is a bit strange.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1347 -C .\avrdude_pr1347.conf -c xplainedmini
 -p m328pb -n -U .\hex3\zeros2KB.hex
avrdude_pr1347: AVR device initialized and ready to accept instructions
avrdude_pr1347: device signature = 0x1e9516 (probably m328pb)
avrdude_pr1347: Note: flash memory has been specified, an erase cycle will be performed.
                To disable this feature, specify the -D option.
avrdude_pr1347 warning: conflicting -e and -n options specified, NOT erasing chip
avrdude_pr1347: reading input file .\hex3\zeros2KB.hex for flash
                with 2048 bytes in 1 section within [0, 0x7ff]
                using 16 pages and 0 pad bytes
avrdude_pr1347: writing 2048 bytes flash ...
:200000000000000000000000000000000000000000000000000000000000000000000000E0
:200020000000000000000000000000000000000000000000000000000000000000000000C0
:200040000000000000000000000000000000000000000000000000000000000000000000A0
:20006000000000000000000000000000000000000000000000000000000000000000000080
:20008000000000000000000000000000000000000000000000000000000000000000000060
:2000A000000000000000000000000000000000000000000000000000000000000000000040
:2000C000000000000000000000000000000000000000000000000000000000000000000020
:2000E000000000000000000000000000000000000000000000000000000000000000000000
:200100000000000000000000000000000000000000000000000000000000000000000000DF
:200120000000000000000000000000000000000000000000000000000000000000000000BF
:2001400000000000000000000000000000000000000000000000000000000000000000009F
:2001600000000000000000000000000000000000000000000000000000000000000000007F
:2001800000000000000000000000000000000000000000000000000000000000000000005F
:2001A00000000000000000000000000000000000000000000000000000000000000000003F
:2001C00000000000000000000000000000000000000000000000000000000000000000001F
:2001E0000000000000000000000000000000000000000000000000000000000000000000FF
:200200000000000000000000000000000000000000000000000000000000000000000000DE
:200220000000000000000000000000000000000000000000000000000000000000000000BE
:2002400000000000000000000000000000000000000000000000000000000000000000009E
:2002600000000000000000000000000000000000000000000000000000000000000000007E
:2002800000000000000000000000000000000000000000000000000000000000000000005E
:2002A00000000000000000000000000000000000000000000000000000000000000000003E
:2002C00000000000000000000000000000000000000000000000000000000000000000001E
:2002E0000000000000000000000000000000000000000000000000000000000000000000FE
:200300000000000000000000000000000000000000000000000000000000000000000000DD
:200320000000000000000000000000000000000000000000000000000000000000000000BD
:2003400000000000000000000000000000000000000000000000000000000000000000009D
:2003600000000000000000000000000000000000000000000000000000000000000000007D
:2003800000000000000000000000000000000000000000000000000000000000000000005D
:2003A00000000000000000000000000000000000000000000000000000000000000000003D
:2003C00000000000000000000000000000000000000000000000000000000000000000001D
:2003E0000000000000000000000000000000000000000000000000000000000000000000FD
:200400000000000000000000000000000000000000000000000000000000000000000000DC
:200420000000000000000000000000000000000000000000000000000000000000000000BC
:2004400000000000000000000000000000000000000000000000000000000000000000009C
:2004600000000000000000000000000000000000000000000000000000000000000000007C
:2004800000000000000000000000000000000000000000000000000000000000000000005C
:2004A00000000000000000000000000000000000000000000000000000000000000000003C
:2004C00000000000000000000000000000000000000000000000000000000000000000001C
:2004E0000000000000000000000000000000000000000000000000000000000000000000FC
:200500000000000000000000000000000000000000000000000000000000000000000000DB
:200520000000000000000000000000000000000000000000000000000000000000000000BB
:2005400000000000000000000000000000000000000000000000000000000000000000009B
:2005600000000000000000000000000000000000000000000000000000000000000000007B
:2005800000000000000000000000000000000000000000000000000000000000000000005B
:2005A00000000000000000000000000000000000000000000000000000000000000000003B
:2005C00000000000000000000000000000000000000000000000000000000000000000001B
:2005E0000000000000000000000000000000000000000000000000000000000000000000FB
:200600000000000000000000000000000000000000000000000000000000000000000000DA
:200620000000000000000000000000000000000000000000000000000000000000000000BA
:2006400000000000000000000000000000000000000000000000000000000000000000009A
:2006600000000000000000000000000000000000000000000000000000000000000000007A
:2006800000000000000000000000000000000000000000000000000000000000000000005A
:2006A00000000000000000000000000000000000000000000000000000000000000000003A
:2006C00000000000000000000000000000000000000000000000000000000000000000001A
:2006E0000000000000000000000000000000000000000000000000000000000000000000FA
:200700000000000000000000000000000000000000000000000000000000000000000000D9
:200720000000000000000000000000000000000000000000000000000000000000000000B9
:20074000000000000000000000000000000000000000000000000000000000000000000099
:20076000000000000000000000000000000000000000000000000000000000000000000079
:20078000000000000000000000000000000000000000000000000000000000000000000059
:2007A000000000000000000000000000000000000000000000000000000000000000000039
:2007C000000000000000000000000000000000000000000000000000000000000000000019
:2007E0000000000000000000000000000000000000000000000000000000000000000000F9
:00000001FF
avrdude_pr1347: 2048 bytes of flash written
avrdude_pr1347: verifying flash memory against .\hex3\zeros2KB.hex
Reading | ################################################## | 100% 0.00 s 
avrdude_pr1347: 2048 bytes of flash verified

avrdude_pr1347 done.  Thank you.
```

**Comment by stefanrueger** [comment]
Thanks for testing @mcuee! I think you have uncovered a small but important problem of dryrun's part emulation (or the way AVRDUDE internally models parts, depending on your point of view):

>  -U fuses:r:-:h

The fuses memory is the concatenation of all `fuse[0-24-8]` memories with holes (there is no fuse3). When updating fuse then `-c dryrun` ought to also update the `X`*th*-byte of `fuses` and vice versa. Sth for the w/end to think about.

Yes, I am aware of the `-n` option. It's restricted to `-U` updates and doesn't extend to the terminal. I think `-n` was meant for debugging and therefore shows what would be written to the device when used in anger. In contrast, `-c dryrun` is a tool to check the logic of AVRDUDE, something particularly useful for testing terminal commands. I predict that in future `-c dryrun` is getting more traction.

@mcuee: What would `-xdryrun -c myprogrammer` do? If that requires implementation at programmer level then it's *quite* a bit of work seeing that there are currently 153 programmers and counting! (`avrdude -c? |& grep = | wc -l`).

**Comment by mcuee** [comment]
> @mcuee: What would `-xdryrun -c myprogrammer` do? If that requires implementation at programmer level then it's _quite_ a bit of work seeing that there are currently 153 programmers and counting! (`avrdude -c? |& grep = | wc -l`).

I think it should do similar thing as `-n` but without really trying to connect to the programmer. 

For CI use we do not need to implement for all the programmers, but rather only for a few `key` programmers like `urclock`,  `usbasp`, `stk500v2` and `jtag3updi`. Just wondering what will be the efforts in this case.

**Comment by stefanrueger** [comment]
Now the `fuses` memory and the `fuseX` memories are linked up when emulating a part:

```
avrdude -qqc dryrun -p avr64dd14 -t
avrdude> d fuses
0000  00 00 00 ff ff d0 08 00  00                       |.........       |
avrdude> w fuse5 0xd1
avrdude> d fuses
0000  00 00 00 ff ff d1 08 00  00                       |.........       |
avrdude> w fuses 5 0xd2
avrdude> d fuse5
0000  d2                                                |.               |
```

**Comment by stefanrueger** [comment]
>  without really trying to connect to the programmer [...] but yet follow the programmer's implementation

@mcuee Um, actually, that seems like a lot of work per programmer that quickly multiplies by those covered

**Comment by mcuee** [comment]
> > without really trying to connect to the programmer [...] but yet follow the programmer's implementation
> 
> @mcuee Um, actually, that seems like a lot of work per programmer that quickly multiplies by those covered

I see. No problem. I will raise another issue to talk about `-n` improvement so we do not cloud this PR.

**Comment by mcuee** [comment]
@stefanrueger 

I did some other tests and this PR is good to go from my side.

**Comment by stefanrueger** [comment]
OK,merging soon

**Comment by MCUdude** [comment]
I gave the PR a try, and it works great
I've not stumbled across any issues.

Excellent work @stefanrueger!

**Pull request merged**
