### PR TITLE
Harden test script against older bash versions

### LINKED ISSUE #1649: Test script issues
While testing #1647, I stumbled across this issue. I'm getting a sed rename() error, and the eesave fuse bit is still set to 1, which means that the EEPROM is preserved, even though it shouldn't be.

```
$ ./test-avrdude -d 0 -p "-c nanoevery -p atmega4809 -r -P /dev/cu.usbmodem14101" -v
Testing avrdude version 7.2-20230720
Prepare "-c nanoevery -p atmega4809 -r -P /dev/cu.usbmodem14101" and press 'enter' or 'space' to continue. Press any other key to skip
sed: rename(): No such file or directory
❌   3.452 s: fuse access: clear, set and read eesave fuse bit (failed command below)
$ avrdude -qq -c nanoevery -p atmega4809 -r -P /dev/cu.usbmodem14101 -l /tmp/test-avrdude.log.xcLt9q -T "config eesave=0; config eesave=1; config eesave"
config eesave=eex_preserved # 1
sed: rename(): No such file or directory
✅   3.431 s: fuse access: set eesave fusebit to delete EEPROM on chip erase
✅   3.551 s: chip erase
✅  10.358 s: flash -U write/verify holes_rjmp_loops_49152B.hex
✅   4.256 s: flash -T write/verify holes_rjmp_loops_49152B.hex
✅   3.523 s: eeprom check whether programmer can flip 0s to 1s
✅   3.541 s: eeprom -U write/verify holes_pack_my_box_256B.hex
✅   3.649 s: eeprom -T write/verify holes_{the_five_boxing_wizards,pack_my_box}_256B.hex
✅   4.398 s: chip erase and spot check flash is actually erased
❌   3.417 s: spot check eeprom is erased, too (failed command below)
$ avrdude -qq -c nanoevery -p atmega4809 -r -P /dev/cu.usbmodem14101 -l /tmp/test-avrdude.log.xcLt9q -Ueeprom:v:./test_files/holes_eeprom_0xff_256B.hex
avrdude warning: verification mismatch
        device 0x50 != input 0xff at addr 0x0022 (error)
avrdude error: verification mismatch
✅   3.601 s: usersig -T/-U write/read random_data_64B.bin

One or more AVRDUDE "-c nanoevery -p atmega4809 -r -P /dev/cu.usbmodem14101" tests failed. Do you want to retry this particular test? (y/n): n


$ avrdude -c nanoevery -p atmega4809 -r -P /dev/cu.usbmodem14101 -T "config eesave"
avrdude: touching serial port /dev/cu.usbmodem14101 at 1200 baud
avrdude: waiting for new port... using same port /dev/cu.usbmodem14101
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9651 (probably m4809)

avrdude: processing -T config eesave
config eesave=eex_preserved # 1

avrdude done.  Thank you.
```

### PR DESCRIPTION
**Pull request by stefanrueger**
Fixes #1649

### CODE REVIEW

**Comment by mcuee** [comment]
@stefanrueger 

This PR is good to go.

However, I do not quite agree it is due to old bash version.

macOS Homebrew is using the almost-latest bash 5.2 version.
https://ftp.gnu.org/gnu/bash/
https://github.com/Homebrew/homebrew-core/blob/0889088ebe050e0df4dde92a744ed1e1210c2dfc/Formula/b/bash.rb

```
mcuee@mcuees-Mac-mini tools % bash --version
GNU bash, version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mcuee** [comment]
@stefanrueger 

It would be good that you can change the commit message to remove the word "older".

**Comment by mcuee** [comment]
Other than the commit message, this PR is good.

Even with the following patch, there is no longer script error as seen in #1649.

#1649 discovered two issues. This PR fixes the script error issue. The fuse writing issue will still need to be addressed in another PR.

```
mcuee@mcuees-Mac-mini tools % git diff
diff --git a/tools/test-avrdude b/tools/test-avrdude
index fd3a8407..bce245bb 100755
--- a/tools/test-avrdude
+++ b/tools/test-avrdude
@@ -410,6 +410,9 @@ for (( p=0; p<$arraylength; p++ )); do
     ######
     # Chip erase and verify
     #
+    specify="fuse access: read eesave fuse bit"
+    command=(${avrdude[@]} -T '"config eesave"')
+    execute "${command[@]}"
     specify="chip erase and spot check flash is actually erased"
     command=(${avrdude[@]} -e -Uflash:v:$tfiles/holes_flash_0xff_${FLASH_SIZE}B.hex)
     execute "${command[@]}"

mcuee@mcuees-Mac-mini tools % ./test-avrdude -v -d 2 -p "-c nanoevery -p m4809 -P usb:2341:0058 -r" 
Testing avrdude version 7.2-20240201 (571a8063)
Prepare "-c nanoevery -p m4809 -P usb:2341:0058 -r" and press 'enter' or 'space' to continue. Press any other key to skip
✅   3.452 s: fuse access: clear, set and read eesave fuse bit
✅   3.467 s: fuse access: set eesave fusebit to delete EEPROM on chip erase
✅   3.626 s: chip erase
✅  10.564 s: flash -U write/verify holes_rjmp_loops_49152B.hex
✅   4.410 s: flash -T write/verify holes_rjmp_loops_49152B.hex
✅   3.597 s: eeprom check whether programmer can flip 0s to 1s
✅   3.604 s: eeprom -U write/verify holes_pack_my_box_256B.hex
✅   3.733 s: eeprom -T write/verify holes_{the_five_boxing_wizards,pack_my_box}_256B.hex
config eesave=eex_preserved # 1
✅   4.572 s: chip erase and spot check flash is actually erased
❌   3.475 s: spot check eeprom is erased, too (failed command below)
$ avrdude -qq -c nanoevery -p m4809 -P usb:2341:0058 -r -l /tmp/test-avrdude.log.9zCdrh -Ueeprom:v:./test_files/holes_eeprom_0xff_256B.hex
avrdude warning: verification mismatch
        device 0x50 != input 0xff at addr 0x0022 (error)
avrdude error: verification mismatch
✅   3.623 s: usersig -T/-U write/read random_data_64B.bin

One or more AVRDUDE "-c nanoevery -p m4809 -P usb:2341:0058 -r" tests failed. Do you want to retry this particular test? (y/n): n
```

**Comment by mcuee** [comment]
@stefanrueger 

While you are at this, maybe you want to harder `-e` option as well when the excutable is not there. Currently the error message is not helping.

```
mcuee@mcuees-Mac-mini tools % ./test-avrdude -e "./avrdude" -v -d 2 -p "-c nanoevery -p m4809 -P usb:2341:0058 -r"  
Testing ./avrdudePrepare "-c nanoevery -p m4809 -P usb:2341:0058 -r" and press 'enter' or 'space' to continue. Press any other key to skip
Cannot detect flash; check that "-c nanoevery -p m4809 -P usb:2341:0058 -r" are valid avrdude options; skipping this test
mcuee@mcuees-Mac-mini tools % ls
atdf-to-avrdude.xslt   avrdude_issue1649      bootloader-hash        get-dw-params.xsl      get-stk600-cards.xsl   test-avrdude
avrdude.conf           avrdude_issue1649.conf build-mingw32.sh       get-hv-params.xsl      get-stk600-devices.xsl test_files
```

**Comment by stefanrueger** [comment]
OK created another PR #1658

**Pull request closed without merging**
