### PR TITLE
CMake Enhancements

### LINKED ISSUE #954: Windows shared library build problem under both VS2019 and MSYS2
I am not able to build the shared library under either VS2019 or MSYS2. Static build is okay.
Ref: https://github.com/avrdudes/avrdude/issues/952#issuecomment-1120810691
Ref: https://github.com/avrdudes/avrdude/issues/951#issuecomment-1120991143

### LINKED ISSUE #959: CMake MSYS2 mingw32/mingw64 build is using libreadline.dll.a and not libreadline.a
There is a bit of inconsistency in the CMake build. It is using the static libraries for the dependancies like libusb-1.0, libfti1 and hidapi. But somehow it is using the dynamic link library for readline.

Ref: https://github.com/avrdudes/avrdude/issues/955#issuecomment-1122370149

```
cd /C/work/avr/avrdude-7.0_cmake/avrdude-7.0/build/src && /C/msys64/mingw64/bin/gcc.exe -Wl,--whole-archive CMakeFiles/avrdude.dir/objects.a -Wl,--no-whole-archive -o avrdude.exe -Wl,--out-implib,libavrdude.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavrdude.a /C/msys64/mingw64/lib/libelf.a /C/msys64/mingw64/lib/libusb.a /C/msys64/mingw64/lib/libusb-1.0.a /C/msys64/mingw64/lib/libhid.a /C/msys64/mingw64/lib/libhidapi.a /C/msys64/mingw64/lib/libftdi1.a /C/msys64/mingw64/lib/libreadline.dll.a -lsetupapi -lws2_32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
```

### PR DESCRIPTION
**Pull request by mariusgreuel**
This serves as a bucket for various CMake issues and wishes that came up recently.

I will merge myself.

- Fixes #959
- Partially fixes #954

### CODE REVIEW

**Comment by mcuee** [comment]
Tested with VS2019 for the option to link to shared library.
```
1> CMake generation started for configuration: 'x64-Debug'.
1> Found and using vcpkg toolchain file (C:/src/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\work\avr\avrdude_test\avrdude-fork\out\install\x64-Debug" -DUSE_EXTERNAL:BOOL="True" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/src/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\work\avr\avrdude_test\avrdude-fork" 2>&1"
1> Working directory: C:\work\avr\avrdude_test\avrdude-fork\out\build\x64-Debug
1> [CMake] -- Fetching external libraries, please wait...
1> [CMake] -- Using external library 'libelf'
1> [CMake] -- Using external library 'libusb'
1> [CMake] -- Using external library 'libhidapi'
1> [CMake] -- Using external library 'libftdi'
1> [CMake] -- Configuration summary:
1> [CMake] -- ----------------------
1> [CMake] -- DO HAVE    libelf
1> [CMake] -- DO HAVE    libusb
1> [CMake] -- DON'T HAVE libusb_1_0
1> [CMake] -- DO HAVE    libhidapi
1> [CMake] -- DO HAVE    libftdi (but prefer to use libftdi1)
1> [CMake] -- DO HAVE    libftdi1
1> [CMake] -- DISABLED   doc
1> [CMake] -- DISABLED   parport
1> [CMake] -- DISABLED   linuxgpio
1> [CMake] -- DISABLED   linuxspi
1> [CMake] -- ----------------------
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: C:/work/avr/avrdude_test/avrdude-fork/out/build/x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted toolchain configurations.
1> Extracted includes paths.
1> CMake generation finished.

>------ Build All started: Project: avrdude-fork, Configuration: x64-Debug ------
  [1/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.getshdr.c.obj
  [2/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.getphdr.c.obj
  [3/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\begin.c.obj
  [4/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\assert.c.obj
  [5/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.getehdr.c.obj
  [6/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.newphdr.c.obj
  [7/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.newehdr.c.obj
  [8/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\cook.c.obj
  [9/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\64.xlatetof.c.obj
  [10/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.xlatetof.c.obj
  [11/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\fill.c.obj
  [12/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\cntl.c.obj
  [13/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\end.c.obj
  [14/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\flag.c.obj
  [15/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\gelfehdr.c.obj
  [16/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\errmsg.c.obj
  [17/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\errno.c.obj
  [18/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\data.c.obj
  [19/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\gelftrans.c.obj
  [20/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\checksum.c.obj
  [21/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\gelfphdr.c.obj
  [22/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getaroff.c.obj
  [23/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getdata.c.obj
  [24/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getarhdr.c.obj
  [25/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\gelfshdr.c.obj
  [26/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getbase.c.obj
  [27/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getident.c.obj
  [28/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\hash.c.obj
  [29/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getarsym.c.obj
  [30/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\getscn.c.obj
  [31/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\memset.c.obj
  [32/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\kind.c.obj
  [33/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\input.c.obj
  [34/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\nlist.c.obj
  [35/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\newscn.c.obj
  [36/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\newdata.c.obj
  [37/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\ndxscn.c.obj
  [38/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\next.c.obj
  [39/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\nextscn.c.obj
  [40/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\rand.c.obj
  [41/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\swap64.c.obj
  [42/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\strptr.c.obj
  [43/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\opt.delscn.c.obj
  [44/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\update.c.obj
  [45/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\rawfile.c.obj
  [46/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\rawdata.c.obj
  [47/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\verdef_32_tof.c.obj
  [48/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\verdef_32_tom.c.obj
  [49/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\verdef_64_tof.c.obj
  [50/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\version.c.obj
  [51/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\x.remscn.c.obj
  [52/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\verdef_64_tom.c.obj
  [53/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\x.movscn.c.obj
  [54/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\x.elfext.c.obj
  [55/131] Building C object _deps\libelf-build\CMakeFiles\libelf.dir\src\32.fsize.c.obj
  [56/131] Building C object _deps\libusb-build\CMakeFiles\libusb.dir\src\usb.c.obj
  [57/131] Building C object _deps\libusb-build\CMakeFiles\libusb.dir\src\descriptors.c.obj
  [58/131] Linking C static library _deps\libelf-build\libelf.lib
  [59/131] Building CXX object _deps\libftdi-build\CMakeFiles\libftdi.dir\src\ftdi.cpp.obj
  [60/131] Linking CXX static library _deps\libftdi-build\libftdi.lib
  [61/131] Building CXX object _deps\libusb-build\CMakeFiles\libusb.dir\src\windows.cpp.obj
  [62/131] Building C object _deps\libusb-build\CMakeFiles\libusb.dir\src\error.c.obj
  [63/131] Building C object _deps\libusb-build\CMakeFiles\libusb.dir\src\registry.c.obj
  [64/131] Building C object _deps\libhidapi-build\CMakeFiles\libhidapi.dir\src\hid.c.obj
  [65/131] Linking CXX static library _deps\libusb-build\libusb.lib
  [66/131] Linking C static library _deps\libhidapi-build\libhidapi.lib
  [67/131] [FLEX][Parser] Building scanner with win_flex 2.6.4
  [68/131] [BISON][Parser] Building parser with bison 3.7.4
  [69/131] Building C object src\CMakeFiles\libavrdude.dir\arduino.c.obj
  [70/131] Building C object src\CMakeFiles\libavrdude.dir\avr910.c.obj
  [71/131] Building C object src\CMakeFiles\libavrdude.dir\avrftdi_tpi.c.obj
  [72/131] Building C object src\CMakeFiles\libavrdude.dir\avr.c.obj
  [73/131] Building C object src\CMakeFiles\libavrdude.dir\fileio.c.obj
  [74/131] Building C object src\CMakeFiles\libavrdude.dir\dfu.c.obj
  [75/131] Building C object src\CMakeFiles\libavrdude.dir\ft245r.c.obj
  [76/131] Building C object src\CMakeFiles\libavrdude.dir\flip2.c.obj
  [77/131] Building C object src\CMakeFiles\libavrdude.dir\jtagmkI.c.obj
  [78/131] Building C object src\CMakeFiles\libavrdude.dir\avrftdi.c.obj
  [79/131] Building C object src\CMakeFiles\libavrdude.dir\crc16.c.obj
  [80/131] Building C object src\CMakeFiles\libavrdude.dir\buspirate.c.obj
  [81/131] Building C object src\CMakeFiles\libavrdude.dir\config.c.obj
  [82/131] Building C object src\CMakeFiles\libavrdude.dir\flip1.c.obj
  [83/131] Building C object src\CMakeFiles\libavrdude.dir\butterfly.c.obj
  [84/131] Building C object src\CMakeFiles\libavrdude.dir\avrpart.c.obj
  [85/131] Building C object src\CMakeFiles\libavrdude.dir\micronucleus.c.obj
  [86/131] Building C object src\CMakeFiles\libavrdude.dir\ppi.c.obj
  [87/131] Building C object src\CMakeFiles\libavrdude.dir\linuxspi.c.obj
  [88/131] Building C object src\CMakeFiles\libavrdude.dir\lists.c.obj
  [89/131] Building C object src\CMakeFiles\libavrdude.dir\linuxgpio.c.obj
  [90/131] Building C object src\CMakeFiles\libavrdude.dir\jtagmkII.c.obj
  [91/131] Building C object src\CMakeFiles\libavrdude.dir\jtag3.c.obj
  [92/131] Building C object src\CMakeFiles\libavrdude.dir\par.c.obj
  [93/131] Building C object src\CMakeFiles\libavrdude.dir\ser_posix.c.obj
  [94/131] Building C object src\CMakeFiles\libavrdude.dir\serbb_posix.c.obj
  [95/131] Building C object src\CMakeFiles\libavrdude.dir\pgm.c.obj
  [96/131] Building C object src\CMakeFiles\libavrdude.dir\pgm_type.c.obj
  [97/131] Building C object src\CMakeFiles\libavrdude.dir\pindefs.c.obj
  [98/131] Building C object src\CMakeFiles\libavrdude.dir\ppiwin.c.obj
  [99/131] Building C object src\CMakeFiles\libavrdude.dir\bitbang.c.obj
  [100/131] Building C object src\CMakeFiles\libavrdude.dir\ser_avrdoper.c.obj
  [101/131] Building C object src\CMakeFiles\libavrdude.dir\teensy.c.obj
  [102/131] Building C object src\CMakeFiles\libavrdude.dir\serialupdi.c.obj
  [103/131] Building C object src\CMakeFiles\libavrdude.dir\confwin.c.obj
  [104/131] Building C object src\CMakeFiles\libavrdude.dir\stk500generic.c.obj
  [105/131] Building C object src\CMakeFiles\libavrdude.dir\stk500.c.obj
  [106/131] Building C object src\CMakeFiles\libavrdude.dir\serbb_win32.c.obj
  [107/131] Building C object src\CMakeFiles\libavrdude.dir\pickit2.c.obj
  [108/131] Building C object src\CMakeFiles\libavrdude.dir\updi_link.c.obj
  [109/131] Building C object src\CMakeFiles\libavrdude.dir\stk500v2.c.obj
  [110/131] Building C object src\CMakeFiles\libavrdude.dir\usbtiny.c.obj
  [111/131] Building C object src\CMakeFiles\libavrdude.dir\updi_readwrite.c.obj
  [112/131] Building C object src\CMakeFiles\libavrdude.dir\updi_nvm.c.obj
  [113/131] Building C object src\CMakeFiles\libavrdude.dir\usbasp.c.obj
  [114/131] Building C object src\CMakeFiles\libavrdude.dir\updi_state.c.obj
  [115/131] Building C object src\CMakeFiles\libavrdude.dir\__\config_gram.c.obj
  [116/131] Building C object src\CMakeFiles\libavrdude.dir\usb_libusb.c.obj
  [117/131] Building C object src\CMakeFiles\libavrdude.dir\update.c.obj
  [118/131] Building C object src\CMakeFiles\libavrdude.dir\usb_hidapi.c.obj
  [119/131] Building C object src\CMakeFiles\libavrdude.dir\__\lexer.c.obj
  [120/131] Building C object src\CMakeFiles\libavrdude.dir\ser_win32.c.obj
  [121/131] Building C object src\CMakeFiles\libavrdude.dir\wiring.c.obj
  [122/131] Building C object src\CMakeFiles\libavrdude.dir\xbee.c.obj
  [123/131] Building C object src\CMakeFiles\avrdude.dir\term.c.obj
  [124/131] Building C object src\CMakeFiles\libavrdude.dir\msvc\gettimeofday.c.obj
  [125/131] Building C object src\CMakeFiles\avrdude.dir\main.c.obj
  [126/131] Building C object src\CMakeFiles\libavrdude.dir\msvc\getopt.c.obj
  [127/131] Building RC object src\CMakeFiles\avrdude.dir\windows.rc.res
  Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
  
  
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  
  
  
  [128/131] Building CXX object src\CMakeFiles\libavrdude.dir\msvc\usleep.cpp.obj
  [129/131] Building C object src\CMakeFiles\avrdude.dir\whereami.c.obj
  [130/131] Linking CXX static library src\libavrdude.lib
  [131/131] Linking CXX executable src\avrdude.exe

Build All succeeded.
```

**Comment by mcuee** [comment]
Under MSYS2 mingw64, this works perfectly fine.

```
/c/work/avr/avrdude_test/avrdude-fork/build_sharedlib
$  cmake -G "MSYS Makefiles" .. -DUSE_STATIC_LIBS="OFF" -DCMAKE_VERBOSE_MAKEFILE="ON"
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/msys64/usr/bin/git.exe (found version "2.36.1")
-- Found FLEX: C:/msys64/usr/bin/flex.exe (found version "2.6.4")
-- Found BISON: C:/msys64/usr/bin/bison.exe (found version "3.8.2")
-- Looking for libelf.h
-- Looking for libelf.h - found
-- Looking for libelf/libelf.h
-- Looking for libelf/libelf.h - found
-- Looking for usb.h
-- Looking for usb.h - not found
-- Looking for lusb0_usb.h
-- Looking for lusb0_usb.h - found
-- Looking for libusb.h
-- Looking for libusb.h - not found
-- Looking for libusb-1.0/libusb.h
-- Looking for libusb-1.0/libusb.h - found
-- Looking for hidapi/hidapi.h
-- Looking for hidapi/hidapi.h - found
-- Looking for ftdi_tcioflush
-- Looking for ftdi_tcioflush - found
-- Configuration summary:
-- ----------------------
-- DO HAVE    libelf
-- DO HAVE    libusb
-- DO HAVE    libusb_1_0
-- DO HAVE    libhidapi
-- DON'T HAVE libftdi
-- DO HAVE    libftdi1
-- DISABLED   doc
-- DISABLED   parport
-- DISABLED   linuxgpio
-- DISABLED   linuxspi
-- ----------------------
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/avr/avrdude_test/avrdude-fork/build_sharedlib

```

**Review by mcuee — APPROVED** [review]

**Review by mcuee — COMMENTED** [review]
Tested under MSYS2 mingw64 and this works fine.

**Comment by mariusgreuel** [comment]
Note that the CMake files now include the option USE_STATIC_LIBS, which people can use to select either static or dynamic linking. Note, however, that I leave the implementation for somebody else in a separate PR. The current implementation will not work for non-defaults, i.e. statically linking for Linux or dynamically on Windows.

**Pull request merged**
