### PR TITLE
Review avrdude.conf and reconcile with ATDFs

### PR DESCRIPTION
**Pull request by stefanrueger**
Merging this PR will
  -  Populate avrdude.conf's variants from ATDFs
  -  Reconcile avrdude.conf's memory readsize with ATDFs
  -  Reconcile avrdude.conf's memory readback with ATDFs
  -  Reconcile avrdude.conf's memory blocksize with ATDFs
  -  Reconcile avrdude.conf's part togglevtg with ATDFs
  -  Reconcile avrdude.conf's part resetdelayus with ATDFs
  -  Reconcile avrdude.conf's part resetdelay with ATDFs
  -  Reconcile avrdude.conf's part resetdelayms with ATDFs
  -  Reconcile avrdude.conf's part programlockpolltimeout with ATDFs
  -  Reconcile avrdude.conf's part programfusepolltimeout with ATDFs
  -  Reconcile avrdude.conf's part progmodedelay with ATDFs
  -  Reconcile avrdude.conf's part pp_controlstack with ATDFs
  -  Reconcile avrdude.conf's part poweroffdelay with ATDFs
  -  Reconcile avrdude.conf's part pollmethod with ATDFs
  -  Reconcile avrdude.conf's part latchcycles with ATDFs
  -  Reconcile avrdude.conf's part hvspcmdexedelay with ATDFs
  -  Reconcile avrdude.conf's part hvleavestabdelay with ATDFs
  -  Reconcile avrdude.conf's part hventerstabdelay with ATDFs
  -  Reconcile avrdude.conf's part chiperasepolltimeout with ATDFs
  -  Add new component initval to memories in avrdude.conf
  -  Add new component variants to parts in avrdude.conf
  -  Reconcile avrdude.conf's ocdrev with ATDFs
  -  Add MCU registers needed for debugWIRE/JTAG
  -  Add flash_instr and eeprom_instr to 5 parts needed for debugWIRE
      + AT90USB162
      + AT90USB82
      + ATmega16U2
      + ATmega32U2
      + ATmega8U2
  - Add pagel/bs2 pins to 23 part where these were missing
      + ATmega103
      + ATmega169A
      + ATmega169
      + ATmega169PA
      + ATmega169P
      + ATmega3290A
      + ATmega3290
      + ATmega3290PA
      + ATmega3290P
      + ATmega329A
      + ATmega329
      + ATmega329PA
      + ATmega329P
      + ATmega6490A
      + ATmega6490
      + ATmega6490P
      + ATmega649A
      + ATmega649
      + ATmega649P
      + ATmega8515
      + ATtiny167
      + ATtiny43U
      + ATtiny87
  -  Add boot section size to modern AVR8X parts
  -  Update avrdude.conf ATmega165 entry:
      + Corrects signature to `signature = 0x1e 0x94 0x07;` [source](https://github.com/thegaragelab/arduino/blob/master/USB_Programmer/progisp172/eng/ATmega165.xml)
      + Lengthens EEPROM write delay to `min_write_delay = 9000;` # see [Application note AVR513](https://ww1.microchip.com/downloads/en/Appnotes/doc8064.pdf)
  -  Add XMEGA-E fuse for fault detection action on Px0..5
  -  Add 24 parts to avrdude.conf:
      + ATmega16M1
      + ATmega32C1
      + ATmega64C1
      + ATA5505
      + ATA6612C
      + ATA6613C
      + ATA6614Q
      + ATA6616C
      + ATA6617C
      + ATA664251
      + ATmega16HVA
      + ATmega8HVA
      + ATmega16HVB
      + ATmega16HVBrevB
      + ATmega32HVB
      + ATmega32HVBrevB
      + ATmega64HVE2
      + ATmega32HVE2
      + AT90PWM1
      + AT90PWM161
      + AT90PWM81
      + ATxmega32C3
      + ATxmega32D3
      + ATtiny416auto
  -  And modify approriately
      + ATmega32M1
      + ATmega64M1

### CODE REVIEW

**Comment by mcuee** [comment]
Looks like there are missing variants list from the ATDF files which are present in the datasheet and website ordering info. If the datasheet matches the website ordering info, then I think the datasheet should be correct.

I am okay either way.
1) Merge this as it is, and then we fix those missing info later. These are not super important for the purpose of avrdude.
2) Fix whatever we can from the above datasheet/website ordering info.

**Comment by MCUdude** [comment]
Thanks for the PR!

Regarding changing the ATmega165 signature, I see now that #897 didn't resolve the ATmega165 signature issue.
Thanks for fixing this as well!

I'm not at a computer where I can easily test this PR, but may the `variants` name be used as the target name?

```
avrdude -p ATtiny13-PU -t 
```

**Comment by mcuee** [comment]
> I'm not at a computer where I can easily test this PR, but may the `variants` name be used as the target name?
> 
> ```
> avrdude -p ATtiny13-PU -t 
> ```

As of now, not yet.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1343 -C .\avrdude_pr1343.conf -c avrisp2 -p ATmega32A
avrdude_pr1343: AVR device initialized and ready to accept instructions
avrdude_pr1343: device signature = 0x1e9502 (probably m32a)

avrdude_pr1343 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1343 -C .\avrdude_pr1343.conf -c avrisp2 -p ATmega32A-AN

avrdude_pr1343 error: AVR part ATmega32A-AN not found

Valid parts are:
...
```

**Comment by stefanrueger** [comment]
Tips on which tests might be useful @mcuee @MCUdude @dl8dtl:
 - 24 new parts defined, all from scratch (automatically extracted from ATDFs with a modicum of manual addition); some are [*bizarro* parts](https://github.com/avrdudes/avrdude/issues/1092#issuecomment-1321197843) (as per @SpenceKonde), but perhaps test
    + ATmega16M1, ATmega32M1, ATmega64M1, ATmega32C1, ATmega64C1 (m32m1 and m64m1 were rewritten)
    + AT90PWM1, AT90PWM81, AT90PWM161
 - Test the following with debugWIRE and jtagmkII (`eeprom_instr` and `flash_instr` had been missing)
    + AT90USB162, AT90USB82
    + ATmega8U2, ATmega16U2, ATmega32U2
 - Pagel/bs2 has been missing in some parts; prob of no significance as this is was only used for HV parallel programming using the stk500 (v1); but if your firmware is stuck in the early 00s you should be able to test, eg,
    + ATtiny87, ATtiny167
 - Using HV mode programming with STK500 (v2) to test the changed 32-bytes controlstack for
    + ATmega128RFA1, ATmega256RFR2, ATtiny1634

Other than that the main reconciliation happened with STK500 parameters from the ATDF files, so if anything the STK500 programmer (and derivatives) *should work on more parts*.

The diff of `avrdude.conf.in` shows that a *lot* of parameters were corrected to match the ATDFs. I am sure many entries in `avrdude.conf.in` were created with attention to detail and style, *but* I also think that some entries came about by rashly parenting off another part (with the only criterion being that sum of the digits in the part number *roughly* matched) and leaving it at that once the desired application worked (eg, boot-loading with optiboot) without giving a second thought to any of the other programmers. I am equally sure that not every ATDF entry can or should be read as holy scripture - they can have mistakes, too. All things considered I think this PR to be an improvement.


And, yes, @mcuee and @MCUdude, the new `variants` field is meant to help users find the right part. I still have to think about what's the best way to do so; here my thoughts
  1. `avrdude -p unknown` could show the variants with at least one `-v`
  2. The developer options (wildcard selection of parts) and normal selection should also consult the variants

Here an example for the first:
```
$ avrdude -vp dunno
[...]
  m165       = ATmega165          [/usr/local/etc/avrdude.conf:13806]
  m165a      = ATmega165A         [/usr/local/etc/avrdude.conf:13793]
    - ATmega165A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
  m165p      = ATmega165P         [/usr/local/etc/avrdude.conf:13668]
    - ATmega165P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
  m165pa     = ATmega165PA        [/usr/local/etc/avrdude.conf:13821]
    - ATmega165PA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
  m168       = ATmega168          [/usr/local/etc/avrdude.conf:7962]
    - ATmega168-20AU: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168-20MU: 'QFN32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168-20PU: 'PDIP28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168V-10AU: 'TQFP32', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168V-10MU: 'QFN32', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168V-10PU: 'PDIP28', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
  m168a      = ATmega168A         [/usr/local/etc/avrdude.conf:8099]
    - ATmega168A-AU: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168A-CCU: 'UFBGA32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168A-MMH: 'QFN28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168A-MU: 'QFN32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168A-PU: 'PDIP28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
  m168p      = ATmega168P         [/usr/local/etc/avrdude.conf:8115]
    - ATmega168P-20AU: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168P-20MU: 'QFN32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168P-20PU: 'PDIP28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168PV-10AU: 'TQFP32', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PV-10MU: 'QFN32', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PV-10PU: 'PDIP28', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
  m168pa     = ATmega168PA        [/usr/local/etc/avrdude.conf:8133]
    - ATmega168PA-AN: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 105 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-AU: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-CCU: 'UFBGA32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-MMH: 'QFN28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-MN: 'QFN32', Fmax=20000000 Hz, temp=[-40 C, 105 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-MU: 'QFN32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-PN: 'PDIP28', Fmax=20000000 Hz, temp=[-40 C, 105 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PA-PU: 'PDIP28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
  m168pb     = ATmega168PB        [/usr/local/etc/avrdude.conf:8153]
    - ATmega168PB-AN: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 105 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PB-AU: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PB-MN: 'VQFN32', Fmax=20000000 Hz, temp=[-40 C, 105 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PB-MU: 'VQFN32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
[...]
```


For the second I tend to think that the full variant name should work but also the portion up to the dash:
```
avrdude -p ATmega168PV
avrdude -p ATmega168P-20PU
```
but not, eg, `ATmega168PV-20AU`, `ATmega168PV-AU`,  `ATmega168PV-MMH`, etc. That is, there should be some evidence that variant exists and. As @mcuee pointed out, these can be easily added in another PR. I won't be reading 300+ data sheets to figure out all possible combinations, but maybe someone (different from me) can figure out from vendor (Mouser, Farnell or even Microchip) somewhere what legit variants of *Microchip's order number* are that might end up printed on the chip.

**Comment by MCUdude** [comment]
How about using [MHz] as the unit for Fmax instead of [Hz]? The datasheet does this, and is easier to read without all the zeros.

It would also be great if all the columns lined up nicely when printed on the screen. This would make it easier to compare the various variants:

```
  m168p      = ATmega168P         [/usr/local/etc/avrdude.conf:8115]
    - ATmega168P-20AU: 'TQFP32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168P-20MU: 'QFN32', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168P-20PU: 'PDIP28', Fmax=20000000 Hz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168PV-10AU: 'TQFP32', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PV-10MU: 'QFN32', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PV-10PU: 'PDIP28', Fmax=10000000 Hz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
  
  m168p      = ATmega168P         [/usr/local/etc/avrdude.conf:8115]
    - ATmega168P-20AU:  'TQFP32', Fmax=20 MHz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168P-20MU:  'QFN32',  Fmax=20 MHz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168P-20PU:  'PDIP28', Fmax=20 MHz, temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
    - ATmega168PV-10AU: 'TQFP32', Fmax=20 MHz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PV-10MU: 'QFN32',  Fmax=20 MHz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
    - ATmega168PV-10PU: 'PDIP28', Fmax=20 MHz, temp=[-40 C, 85 C], Vcc=[1.8 V, 5.5 V]
```

**Comment by stefanrueger** [comment]
@MCUdude OK, see how you like output of variants and matching against them for -p

**Comment by stefanrueger** [comment]
In absence of any further testing, I'd suggest to merge this PR. Regressions, if any, can (in theory) be traced back to a single commits (it is deliberate that each reconciled parameter has its own commit). 

This PR now also fixes #1092 

```
$ avrdude -c urclock -p atmega328p-au -xshowall
00000bd39209 2023-04-12 21.54 blink 736 store 31620 meta 28 boot 384 u7.7 weu-jPrac vector 25 (SPM_Ready) ATmega328P

$ avrdude -pATmega32L/s | head -20
#------------------------------------------------------------
# ATmega32
#------------------------------------------------------------

part
    desc                   = "ATmega32";
    id                     = "m32";
    variants               =
        "ATmega32L-8AU: 'TQFP44', Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]",
        "ATmega32L-8PU: 'PDIP40', Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]",
        "ATmega32L-8MU: 'QFN44',  Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]",
        "ATmega32-16AU: 'TQFP44', Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]",
        "ATmega32-16PU: 'PDIP40', Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]",
        "ATmega32-16MU: 'QFN44',  Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]";
    prog_modes             = PM_SPM | PM_ISP | PM_HVPP | PM_JTAG | PM_JTAGmkI;
    mcuid                  = 58;
    n_interrupts           = 21;
    n_boot_sections        = 4;
    boot_section_size      = 512;
    stk500_devcode         = 0x91;

$ avrdude -p\*L/d |cut -f2 -d\'
ATmega64
ATmega128
ATmega16
ATmega32
ATmega8
```

The latter gives a list of parts that have `L` variant, a modifier at the end of the part number that signifies *low voltage* operation (in newer parts this would be a `V` modifier).

**Comment by stefanrueger** [comment]
> to only print compatible variants

A very specialised application, not sure this has much use for development.

There is a general way to pick one parameter for a part using `grep`. For example, `avrdude -pm32/At | grep variants` will (almost) do what you want, and this works for *any* parameter. Here an application of this trick using a bit more mangling with general command line tools to get a neat list:
```
$ avrdude -pm32/At | grep variants | cut -f4- | sed 's/", "/\n/g' | tr -d \"
ATmega32L-8AU: 'TQFP44', Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
ATmega32L-8PU: 'PDIP40', Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
ATmega32L-8MU: 'QFN44',  Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
ATmega32-16AU: 'TQFP44', Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]
ATmega32-16PU: 'PDIP40', Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]
ATmega32-16MU: 'QFN44',  Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]

```

**Comment by MCUdude** [comment]
> There is a general way to pick one parameter for a part using grep

I'm fine using grep as long as I know what I'm searching for, but I'm pretty sure Windows' command prompt or Power shell doesn't have grep.

**Comment by mcuee** [comment]
> In absence of any further testing, I'd suggest to merge this PR. Regressions, if any, can (in theory) be traced back to a single commit: it is deliberate that each reconciled parameter has its own commit.

@stefanrueger 
I am fine with merging the PR now.

> There is a general way to pick one parameter for a part using `grep`. For example, `avrdude -pm32/At | grep variants` will (almost) do what you want, and this works for _any_ parameter. Here an application of this trick using a bit more mangling with general command line tools to get a neat list:
> 
> ```
> $ avrdude -pm32/At | grep variants | cut -f4- | sed 's/", "/\n/g' | tr -d \"
> ATmega32L-8AU: 'TQFP44', Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
> ATmega32L-8PU: 'PDIP40', Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
> ATmega32L-8MU: 'QFN44',  Fmax=8 MHz,  temp=[-40 C, 85 C], Vcc=[2.7 V, 5.5 V]
> ATmega32-16AU: 'TQFP44', Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]
> ATmega32-16PU: 'PDIP40', Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]
> ATmega32-16MU: 'QFN44',  Fmax=16 MHz, temp=[-40 C, 85 C], Vcc=[4.5 V, 5.5 V]
> ```

Nice one.

The follow command list some of the parts we need to fix in the future.

```
$ ./avrdude_pr1343 -C ./avrdude_pr1343.conf -p*/At | grep temp=\\[0 | cut -f4- | sed 's/", "/\n/g' | tr -d \"
ATtiny11: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATtiny12: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny15: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATmega162: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3290: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3290A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3290P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3290PA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega6490: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega6490A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega6490P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega8515: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATmega8535: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATtiny26: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATtiny261A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny461A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny861A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny28: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATtiny828: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.62 V, 5.5 V]
ATtiny87: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny167: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATA5505: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATA664251: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega16HVA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 4.5 V]
ATmega8HVA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 4.5 V]
ATmega16HVB: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[3.0 V, 4.5 V]
ATmega16HVBrevB: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[3.0 V, 4.5 V]
ATmega32HVB: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[3.0 V, 4.5 V]
ATmega32HVBrevB: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[3.0 V, 4.5 V]
ATmega64HVE2: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[3.0 V, 3.6 V]
ATtiny2313: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny2313A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny4313: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
AT90PWM1: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM3: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM2B: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM3B: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM161: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM81: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM316: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90PWM216: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATmega128RFA1: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 3.6 V]
ATtiny24: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny44: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny84: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATtiny43U: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[0.7 V, 5.5 V]
AT90USB646: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90USB647: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90USB1286: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.2 V, 5.5 V]
AT90USB1287: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.2 V, 5.5 V]
AT90USB162: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
AT90USB82: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[2.7 V, 5.5 V]
ATmega165P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega165A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega165PA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega325: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega325A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega325P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega325PA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega645: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega645A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega645P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3250: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3250A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3250P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega3250PA: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega6450: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega6450A: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega6450P: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATXMEGA16A4-AU: 'TQFP44', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA16A4-MU: 'VQFN44', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA32A4-AU: 'TQFP44', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA32A4-MU: 'VQFN44', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA64A1-AU: 'TQFP100', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA64A1-CU: 'CBGA100', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA64A3-AU: 'TQFP64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA64A3-MU: 'QFN64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA128A1-AU: 'TQFP100', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA128A1-CU: 'CBGA100', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA128A3-AU: 'TQFP64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA128A3-MU: 'QFN64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA192C3-AU: 'TQFP64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA192C3-MH: 'QFN64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA192A3-AU: 'TQFP64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA192A3-MU: 'QFN64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA256A3-AU: 'TQFP64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA256A3-MU: 'QFN64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA256A3B-AU: 'TQFP64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATXMEGA256A3B-MU: 'QFN64', Fmax=32000000 Hz, temp=[0 C, 0 C], Vcc=[1.6 V, 3.6 V]
ATtiny1634: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[1.8 V, 5.5 V]
ATmega406: '', Fmax=0 Hz, temp=[0 C, 0 C], Vcc=[4.0 V, 5.5 V]
```

**Comment by mcuee** [comment]
@stefanrueger 

BTW, I have checked quite some ATDF file and indeed your PR is consistent with the ATDF files where the variants are missing. Therefore I believe this PR is good to go.

Just curious the ATDF file parser you are using -- I belive you have written your own parser. I am not so sure if it makes sense to keep the parser in the tools directory. I think the existing parsers are kind of obsolete now.

**Comment by stefanrueger** [comment]
@MCUdude @mcuee I can tell you are hardware people. Hadn't crossed my mind that the exact contents of the variants strings is of strong interest. Since we trial them, we might as well do that well. I have added (automatically) from a large vendor website. So should have more and more relevant variants now. Also changed style (N/A, not 0 V etc). There are still a lot of N/A but at least the space of order numbers (b/c that's what variants are!) should be much more reliable what with them now having been added from a vendor site, where it is in Microchips's interest that stuff can be ordered (as opposed to the ATDF where the variants info is of no consequence to how the chips are programmed).

> written your own parser

No it's `xml_grep` followed by assiduous further (ordinary) *grep*ping. Microchip's ATDF are so unsystematic and erratic that there has to be legwork in the handling of exceptions.

**Comment by mcuee** [comment]
> No it's xml_grep followed by assiduous further (ordinary) grepping. Microchip's ATDF are so unsystematic and erratic that there has to be legwork in the handling of exceptions.

I see. Thanks for the info.

I think this PR is good to go now.

**Pull request merged**
