### PR TITLE
Write empty flash memory to file in correct format

### PR DESCRIPTION
**Pull request by stefanrueger**
`-U flash:r:<file>:<fmt>` produces an empty file if flash memory is empty (unless `-A` has switched off the trailing 0xff removal). However, an empty file is not a correct Intel Hex file as it misses the EOF marker:
```
$ avrdude -qq -c dryrun -p m328p -U flash:r:empty-flash.hex:i
$ avrdude -qq -c dryrun -p m328p -U flash:w:empty-flash.hex:i
avrdude error: no valid record found in Intel Hex file empty-flash.hex
avrdude error: read from file empty-flash.hex failed
srueger@medlar avrdude-main 2005$ (main 5U) ls -l empty-flash.hex 
-rw------- 1 srueger srueger 0 Jun 24 12:58 empty-flash.hex
```

This PR creates empty files with the correct format
 - Intel Hex (EOF record)
 - Motorola S-Record (Start record, EOF record)
 - Number lists (one empty line, ie, one character `\n`)
 - Raw binary (empty file, ie, zero characters)

### CODE REVIEW

**Comment by mcuee** [comment]
Indeed git main has the issue and this PR fixes the issue.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude -c usbasp -p m328pb -U flash:r:empty.hex:i
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9516 (probably m328pb)

avrdude: processing -U flash:r:empty.hex:i
avrdude: reading flash memory ...
Reading | ################################################## | 100% 5.67 s
avrdude: writing output file empty.hex

avrdude done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty.hex

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1438 -c usbasp -p m328pb -U flash:r:empty.hex:i
avrdude_pr1438: AVR device initialized and ready to accept instructions
avrdude_pr1438: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1438: processing -U flash:r:empty.hex:i
avrdude_pr1438: reading flash memory ...
Reading | ################################################## | 100% 5.93 s
avrdude_pr1438: writing output file empty.hex

avrdude_pr1438 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty.hex
:00000001FF
```

**Comment by mcuee** [comment]
BTW, this is a regression from avrdude 7.1 release. So it is good that we catch this and fix before 7.2 release.

The following run log shows that avrdude 7.1 does not have this issue.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude71 -C avrdude71.conf -c usbasp -p m328pb -U flash:r:empty.hex:i

avrdude71: AVR device initialized and ready to accept instructions
avrdude71: device signature = 0x1e9516 (probably m328pb)
avrdude71: reading flash memory ...

Reading | ################################################## | 100% 5.16 s

avrdude71: writing output file empty.hex

avrdude71 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty.hex
:00000001FF
```

**Comment by mcuee** [comment]
@stefanrueger 

I get a bit strange with this PR for s-record. Please take a look. Thanks.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1438 -c usbasp -p m328pb -U flash:r:empty.srec:s
avrdude_pr1438: AVR device initialized and ready to accept instructions
avrdude_pr1438: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1438: processing -U flash:r:empty.srec:s
avrdude_pr1438: reading flash memory ...
Reading | ################################################## | 100% 5.99 s
avrdude_pr1438: writing output file empty.srec

avrdude_pr1438 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty.srec
S026000068747470733A2F2F6769746875622E636F6D2F61767264756465732F6176726475646577
S9030000FC
```

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1438 -c dryrun -p m328pb -U flash:r:empty.srec:s
avrdude_pr1438: AVR device initialized and ready to accept instructions
avrdude_pr1438: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1438: processing -U flash:r:empty.srec:s
avrdude_pr1438: reading flash memory ...
Reading | ################################################## | 100% 0.26 s
avrdude_pr1438: writing output file empty.srec

avrdude_pr1438 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty.srec
S026000068747470733A2F2F6769746875622E636F6D2F61767264756465732F6176726475646577
S9030000FC

**Comment by mcuee** [comment]
Another difference is the addition of optional S50 line. I think that is not a problem.

The following is for empty EEPROM reading.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1438 -c usbasp -p m328pb -U eeprom:r:empty_eeprom.srec:s
avrdude_pr1438: AVR device initialized and ready to accept instructions
avrdude_pr1438: device signature = 0x1e9516 (probably m328pb)

avrdude_pr1438: processing -U eeprom:r:empty_eeprom.srec:s
avrdude_pr1438: reading eeprom memory ...
Reading | ################################################## | 100% 0.63 s
avrdude_pr1438: writing output file empty_eeprom.srec

avrdude_pr1438 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty_eeprom.srec
S026000068747470733A2F2F6769746875622E636F6D2F61767264756465732F6176726475646577
S1230000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
S1230020FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDC
S1230040FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBC
S1230060FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9C
S1230080FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7C
S12300A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5C
S12300C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3C
S12300E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1C
S1230100FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
S1230120FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDB
S1230140FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBB
S1230160FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9B
S1230180FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7B
S12301A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5B
S12301C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3B
S12301E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1B
S1230200FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
S1230220FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA
S1230240FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBA
S1230260FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9A
S1230280FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7A
S12302A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5A
S12302C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3A
S12302E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1A
S1230300FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9
S1230320FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD9
S1230340FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB9
S1230360FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99
S1230380FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF79
S12303A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF59
S12303C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF39
S12303E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF19
S5030020DC
S9030000FC
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude71 -C avrdude71.conf -c usbasp -p m328pb -U eeprom:r:empty_eeprom.srec:s

avrdude71: AVR device initialized and ready to accept instructions
avrdude71: device signature = 0x1e9516 (probably m328pb)
avrdude71: reading eeprom memory ...

Reading | ################################################## | 100% 0.42 s

avrdude71: writing output file empty_eeprom.srec

avrdude71 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> cat .\empty_eeprom.srec
S1230000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
S1230020FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDC
S1230040FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBC
S1230060FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9C
S1230080FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7C
S12300A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5C
S12300C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3C
S12300E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1C
S1230100FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
S1230120FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDB
S1230140FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBB
S1230160FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9B
S1230180FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7B
S12301A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5B
S12301C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3B
S12301E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1B
S1230200FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
S1230220FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA
S1230240FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBA
S1230260FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9A
S1230280FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7A
S12302A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5A
S12302C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3A
S12302E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1A
S1230300FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9
S1230320FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD9
S1230340FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB9
S1230360FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99
S1230380FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF79
S12303A0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF59
S12303C0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF39
S12303E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF19
S9030000FC
```

**Comment by stefanrueger** [comment]
>  this is a regression from avrdude 7.1

Correct. Caused by the relatively large rewrite of fileio functions to achieve sub-file granularity programming. Goes to show that `-U` and the new terminal `save` and `write file` *still need thorough testing* for all sorts of file formats and quirky files (empty files, files with holes, hex flash files with odd bytes, especially with a single byte etc). It is sufficient to test with the dryrun programmer only because the code base separates file I/O from the programming itself.

> [do we really want to add the] comment `https://github.com/avrdudes/avrdude`

I think so! The comment record `S0` is optional but `srec_cat` warns about the missing header, adds its own header `http://srecord.sourceforge.net` and a S5 record count:
``` console
$ git checkout 3ea05c4d3343792024b7863b448e961bc7933541
$ # Previous empty Motorola S-Record file
$ avrdude -qqp m328p -c dryrun -U flash:r:-:s
S9030000FC

$ avrdude -qqp m328p -c dryrun -U flash:r:-:s | srec_cat
srec_cat: standard input: 1: warning: no header record
srec_cat: standard input: 2: warning: file contains no data
S0220000687474703A2F2F737265636F72642E736F75726365666F7267652E6E65742F1D
S5030000FC
S9030000FC
```

Aha, `srec_cat` also adds a record count when it is zero. Just pushing a commit to do likewise.

**Comment by mcuee** [comment]
Okay, I think this PR is good to go now.

**Pull request merged**
