### PR TITLE
Support AVR64DU28 and AVR64DU32

### PR DESCRIPTION
**Pull request by stefanrueger**
Untested b/c the parts are not (yet) available but this PR utilises the new .atdf files.

@askn37 - please could you review?

### CODE REVIEW

**Comment by askn37** [comment]
Unfortunately, it appears that some items are mismatched between the configuration file and ATDF.

*In order to reuse the previous parts, it may be better to create a dedicated ".avrdu" base part as there are many differences. (IO map changes are very similar between his AVR_DU and AVR_EB. NVMCTRLversion is also different) *

*avrdude.conf.in*
```
    memory "tempsense"
        offset             = 0x1084;
    ;

    memory "bootrow"
        size               = 64;
        page_size          = 64;
        offset             = 0x1100;
        readsize           = 256;
    ;
```

- Is `hvupdi_variant = 2;` missing?
- "tempsense" has 4 bytes (2 words).
- "bootrow" is 256 bytes (Big!).
- The only differences between AVR64DU28 and AVR64DU32 appear to be signature, product details (variant), and pin count.

*AVR64DU32(28).atdf*
```
            <module id="nvm_ctrl_avr_v4" name="NVMCTRL">
               <instance name="NVMCTRL">
                  <register-group address-space="data"
                                  name="NVMCTRL"
                                  name-in-module="NVMCTRL"
                                  offset="0x1000"/>

            <property-group name="UPDI_INTERFACE">
               <property name="HV_IMPLEMENTATION" value="2"/>
               <property name="PROGMEM_OFFSET" value="0x00800000"/>
            </property-group>

            <register caption="Temperature Calibration 0"
                      name="TEMPSENSE0"
                      offset="0x04"
                      rw="R"
                      size="2">
               <bitfield caption="Temperature Calibration 0"
                         mask="0xFFFF"
                         name="TEMPSENSE0"
                         rw="R"/>
            </register>
            <register caption="Temperature Calibration 1"
                      name="TEMPSENSE1"
                      offset="0x06"
                      rw="R"
                      size="2">
               <bitfield caption="Temperature Calibration 1"
                         mask="0xFFFF"
                         name="TEMPSENSE1"
                         rw="R"/>

               <memory-segment exec="0"
                               name="BOOTROW"
                               pagesize="0x100"
                               rw="RW"
                               size="0x100"
                               start="0x1100"
                               type="user_signatures"/>
```

*ioavr64du32(28).h*
```
/* SIGROW - Signature row */
#define SIGROW_DEVICEID0  _SFR_MEM8(0x1080)
#define SIGROW_DEVICEID1  _SFR_MEM8(0x1081)
#define SIGROW_DEVICEID2  _SFR_MEM8(0x1082)
#define SIGROW_TEMPSENSE0  _SFR_MEM16(0x1084)
#define SIGROW_TEMPSENSE0L  _SFR_MEM8(0x1084)
#define SIGROW_TEMPSENSE0H  _SFR_MEM8(0x1085)
#define SIGROW_TEMPSENSE1  _SFR_MEM16(0x1086)
#define SIGROW_TEMPSENSE1L  _SFR_MEM8(0x1086)
#define SIGROW_TEMPSENSE1H  _SFR_MEM8(0x1087)

#if (defined(__ASSEMBLER__) || defined(__IAR_SYSTEMS_ASM__))
#  define BOOTROW_START     (0x1100)
#  define BOOTROW_SIZE      (256)
#  define BOOTROW_PAGE_SIZE (256)
#else
#  define BOOTROW_START     (0x1100U)
#  define BOOTROW_SIZE      (256U)
#  define BOOTROW_PAGE_SIZE (256U)
#endif
#define BOOTROW_END       (BOOTROW_START + BOOTROW_SIZE - 1)
```

concern. It seems that "nvmctrl_version=N" is required in the component settings. As far as I know, there are currently five types of SIB: 0, 2, 3, 4, and 5, but it's amazing that the number has more than doubled in just one year. However, ATDF does not have a consistent explanation and numbers on this. It probably cannot be derived unless there is a rule to convert the NVMCTRL module ID label to a numerical value.

**Comment by stefanrueger** [comment]
Thanks for cross-checking, @askn37!

Good catch with bootrow size. Corrected now. 

> differences between AVR64DU28 and AVR64DU32 appear to be signature, product details (variant), and pin count

True. Parenting the 64DU32 off 64DU28 neatly expresses this now.

`avrdude -p AVR64DU28/S` (note the capital `/S`) shows the full definition from scratch, so you can convince yourself that the remainder is as it should be. `nvmctrl_version` might be a good addition, but we would need a way to tell which part has which version. Currently AVRDUDE find this out during runtime.

**Comment by MCUdude** [comment]
The variants names are a bit unfortunate. The name (AVR64DU28) shouldn't contain the package name (SSOP/SPDIP), as this messes up the variants table:

```
$ ./avrdude -cdryrun -pavr64du28 -T 'part'
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9622 (probably avr64du28)

avrdude: processing -T part
AVR64DU28 with programming modes UPDI, SPM

Memory            Size  Pg size    Offset
-----------------------------------------
eeprom             256        1    0x1400 
flash            65536      512  0x800000 
fuses               16        1    0x1050 
fuse0/wdtcfg         1        1    0x1050 
fuse1/bodcfg         1        1    0x1051 
fuse2/osccfg         1        1    0x1052 
fuse5/syscfg0        1        1    0x1055 
fuse6/syscfg1        1        1    0x1056 
fuse7/codesize       1        1    0x1057 
fuse8/bootsize       1        1    0x1058 
fusea/pdicfg         2        1    0x105a 
lock                 4        1    0x1040 
prodsig/sigrow     128      128    0x1080 
signature            3        1    0x1080 
tempsense            4        1    0x1084 
sernum              16        1    0x1090 
bootrow            256      256    0x1100 
userrow/usersig    512      512    0x1200 
io                4160        1         0 
sram              8192        1    0x6000 
sib                 32        1         0 

Variants              Package  F max   T range        V range       
--------------------------------------------------------------------
AVR64DU28-SSOP/SPDIP  DIP28    32 MHz  [-40 C, 85 C]  [1.8 V, 5.5 V]
AVR64DU28-VQFN        QFP28    32 MHz  [-40 C, 85 C]  [1.8 V, 5.5 V]

avrdude done.  Thank you.
```

It would be much better if each package option could get its own line.

For reference, here's what the same table for AVR64DA28 looks like:
```
Variants         Package  F max   T range         V range       
----------------------------------------------------------------
AVR64DA28        SOIC28   24 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
AVR64DA28-E/SO   SOIC28   24 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
AVR64DA28-E/SP   SPDIP28  N/A     [N/A,     N/A]  [N/A,     N/A]
AVR64DA28-E/SS   SSOP28   24 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
AVR64DA28-I/SO   SOIC28   24 MHz  [-40 C,  85 C]  [1.8 V, 5.5 V]
AVR64DA28-I/SP   SPDIP28  24 MHz  [-40 C,  85 C]  [1.8 V, 5.5 V]
AVR64DA28-I/SS   SSOP28   24 MHz  [-40 C,  85 C]  [1.8 V, 5.5 V]
AVR64DA28T-E/SO  SOIC28   24 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
AVR64DA28T-E/SS  SSOP28   24 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
AVR64DA28T-I/SO  SOIC28   24 MHz  [-40 C,  85 C]  [1.8 V, 5.5 V]
AVR64DA28T-I/SS  SSOP28   24 MHz  [-40 C,  85 C]  [1.8 V, 5.5 V]
```

**Comment by stefanrueger** [comment]
> The variants names are a bit unfortunate. The name (AVR64DU28) shouldn't contain the package name

Not sure we can do sth about this as this is straight from the `AVR6428.atdf` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<avr-tools-device-file xmlns:NumHelper="NumHelper"
                       xmlns:xalan="http://xml.apache.org/xalan"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       schema-version="4.5"
                       xsi:noNamespaceSchemaLocation="schema/atdf.xsd">
   <variants>
      <variant ordercode="AVR64DU28-SSOP/SPDIP"
               package="DIP28"
               pinout="SSOP28USB"
               speedmax="32000000"
               tempmax="85"
               tempmin="-40"
               vccmax="5.5"
               vccmin="1.8"/>
      <variant ordercode="AVR64DU28-VQFN"
               package="QFP28"
               pinout="QFN28USB"
               speedmax="32000000"
               tempmax="85"
               tempmin="-40"
               vccmax="5.5"
               vccmin="1.8"/>
   </variants>
```

It is hard enough to parse those files let alone figure out why a slash in one name is OK but another one isn't. How would a program know?

**Pull request merged**
