### PR TITLE
Rewrite authors/copyrights

### PR DESCRIPTION
**Pull request by dl8dtl**
Rewrite the list of authors and copyright message.

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks for the PR!

My only thought is that referring to a file called AUTHORS may not make sense where the user has just been handed a binary (Arduino installation, etc.). How about providing a link to the AUTHORS file on GitHub as well? Just a thought.

**Comment by mcuee** [comment]
Thanks a lot for the PR and thanks for adding me in the team.

**Comment by stefanrueger** [comment]
Thanks, I think this is a brilliant team.

**Comment by dl8dtl** [comment]
> Thanks for the PR!
> 
> My only thought is that referring to a file called AUTHORS may not make sense where the user has just been handed a binary (Arduino installation, etc.). How about providing a link to the AUTHORS file on GitHub as well? Just a thought.

Replacing it by an URL is a brilliant idea. I already thought about how to include the full list e.g. with `-vv`, but using the URL is much more convenient.

Pushed.

Let's seen what Brian says to all this. As it modifies the copyright display, I'd like to obtain his consent as well.

**Comment by bd34n** [comment]
Looks great to me!

**Pull request merged**
