### PR TITLE
Fix Type 2 HV UPDI

### LINKED ISSUE #1163: HV UPDI type 2 doesn't work
Thanks to @mcuee for discovering this bug.

It turns out that the logic for determining if a target supports HV UPDI is broken, at least for type 2 devices (AVR-DD and AVR-EA).

Here's the HV UPDI logic in jtag3.c where I've added two print statements to show what's going on:
```c
    // Generate UPDI high-voltage pulse if user asks for it and hardware supports it
     msg_info("HV UPDI support: %d\n", p->hvupdi_variant);
    LNODEID support;
    if (p->prog_modes & PM_UPDI &&
        PDATA(pgm)->use_hvupdi == true &&
        p->hvupdi_variant != HV_UPDI_VARIANT_1) {
      parm[0] = PARM3_UPDI_HV_NONE;
      for (support = lfirst(pgm->hvupdi_support); support != NULL; support = lnext(support)) {
        msg_info("HV UPDI support list: %d\n", *(int *)ldata(support));
        if(*(int *) ldata(support) == p->hvupdi_variant) {
          pmsg_notice("sending HV pulse to targets %s pin\n",
            p->hvupdi_variant == HV_UPDI_VARIANT_0? "UPDI": "RESET");
          parm[0] = PARM3_UPDI_HV_SIMPLE_PULSE;
          break;
        }
        if (parm[0] == PARM3_UPDI_HV_NONE) {
          pmsg_error("%s does not support sending HV pulse to target %s\n", pgm->desc, p->desc);
          return -1;
        }
      }
      if (jtag3_setparm(pgm, SCOPE_AVR, 3, PARM3_OPT_12V_UPDI_ENABLE, parm, 1) < 0)
        return -1;
    }
```

And here's the output:
```
$ ./avrdude -p avr64dd32 -cpickit4_updi -xhvupdi

         Vtarget                      : 0.05 V
         JTAG clock megaAVR/program   : 1000 kHz
         JTAG clock megaAVR/debug     : 100 kHz
         PDI/UPDI clock Xmega/megaAVR : 100 kHz
HV UPDI support: 2
HV UPDI support list: 0
avrdude error: MPLAB(R) PICkit 4 in UPDI mode does not support sending HV pulse to target AVR64DD32
avrdude error: initialization failed, rc=-1
        - double check the connections and try again
        - use -B to set lower ISP clock frequency, e.g. -B 125kHz
        - use -F to override this check


avrdude done.  Thank you.
```

It happens to work with ATtinys, because these are using HVUPDI type 0.
To me, it appears that the linked list isn't being filled, but I don't know enough about linked lists to trace down the bug myself.

### PR DESCRIPTION
**Pull request by MCUdude**
Looks like a brain fart from when I implemented HV UPDI support earlier this year.
It's a very simple fix. Thanks for finding this @mcuee!

Resolves #1163

### CODE REVIEW

**Comment by MCUdude** [comment]
@mcuee please let me know if this works on your hardware. I didn't have time to test it on my AVR64DD32 board before I went on vaccation

**Comment by mcuee** [comment]
@MCUdude 

Yes this works perfectly fine. You can merge it.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1164 -c pickit4_updi -p avr64dd32 -q

                Vtarget                      : 3.30 V
                JTAG clock megaAVR/program   : 1000 kHz
                JTAG clock megaAVR/debug     : 100 kHz
                PDI/UPDI clock Xmega/megaAVR : 100 kHz
avrdude_pr1164 error: initialization failed, rc=-1
               - double check the connections and try again
               - use -B to set lower ISP clock frequency, e.g. -B 200kHz
               - use -F to override this check


avrdude_pr1164 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1164 -p avr64dd32 -c pickit4_updi -xhvupdi -q

                Vtarget                      : 3.30 V
                JTAG clock megaAVR/program   : 1000 kHz
                JTAG clock megaAVR/debug     : 100 kHz
                PDI/UPDI clock Xmega/megaAVR : 100 kHz
avrdude_pr1164: AVR device initialized and ready to accept instructions
avrdude_pr1164: device signature = 0x1e961a (probably avr64dd32)

avrdude_pr1164 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_git -c pkobn_updi -p avr64dd32 -q

             Vtarget                      : 3.31 V
             PDI/UPDI clock Xmega/megaAVR : 100 kHz
avrdude_git: AVR device initialized and ready to accept instructions
avrdude_git: device signature = 0x1e961a (probably avr64dd32)

avrdude_git done.  Thank you.
```

**Review by mcuee — APPROVED** [review]
Tested to be good.

**Comment by mcuee** [comment]
I am not sure what I have done, my AVR64DD32 board seems to be dead now. Guess I can not carry out any test on the AVR64DD32 anytime soon.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude -p avr64dd32 -c pickit4_updi -xhvupdi -v

avrdude: Version 7.0-20221101 (4c92030)
         Copyright (c) Brian Dean, http://www.bdmicro.com/
         Copyright (c) Joerg Wunsch

         System wide configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude.conf

         Using Port                    : usb
         Using Programmer              : pickit4_updi
avrdude: found CMSIS-DAP compliant device, using EDBG protocol
         AVR Part                      : AVR64DD32
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           fuse0       wdtcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse1       bodcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse2       osccfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse4       tcd0cfg     0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse5       syscfg0     0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse6       syscfg1     0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse7       codesize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse8       bootsize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuses                   0     0     0    0 no          9   16      0     0     0 0x00 0x00
           lock                    0     0     0    0 no          4    1      0     0     0 0x00 0x00
           tempsense               0     0     0    0 no          2    1      0     0     0 0x00 0x00
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
           prodsig                 0     0     0    0 no        125  125      0     0     0 0x00 0x00
           sernum                  0     0     0    0 no         16    1      0     0     0 0x00 0x00
           userrow     usersig     0     0     0    0 no         32   32      0     0     0 0x00 0x00
           data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
           eeprom                  0     0     0    0 no        256    1      0     0     0 0x00 0x00
           flash                   0     0     0    0 no      65536  512      0     0     0 0x00 0x00

         Programmer Type : JTAGICE3_UPDI
         Description     : MPLAB(R) PICkit 4 in UPDI mode
         ICE HW version  : 4
         ICE FW version  : 1.14 (rel. 268)
         Serial number   :
         Vtarget         : 3.27 V
         JTAG clock megaAVR/program   : 1000 kHz
         JTAG clock megaAVR/debug     : 100 kHz
         PDI/UPDI clock Xmega/megaAVR : 100 kHz
avrdude: sending HV pulse to targets RESET pin
avrdude: bad response to AVR sign-on command: 0xa0
avrdude: retrying with external reset applied
avrdude: bad response to AVR sign-on command: 0xa0
avrdude: retrying with external reset applied
avrdude main() error: initialization failed, rc=-1
        - double check the connections and try again
        - use -B to set lower ISP clock frequency, e.g. -B 200kHz
        - use -F to override this check


avrdude done.  Thank you.

(py39venv) C:\work\avr\avrdude_test\avrdude_bin> pymcuprog ping -tpickit4 -davr64dd32 -Hsimple-unsafe-pulse -C
Connecting to any pickit4
Connected to MPLAB PICkit 4 CMSIS-DAP from Microchip Technology Incorporated (serial number BUR200973052)
Debugger firmware version 1.14.268
Debugger hardware revision 4
pyedbglib.protocols.jtagice3protocol - ERROR - JTAGICE3 error response code 0x19: 'AVR8_FAILURE_PDI_TIMEOUT: PDI physical timed out'
pymcuprog.pymcuprog - ERROR - Operation failed with Jtagice3ResponseError: AVR8_FAILURE_PDI_TIMEOUT: PDI physical timed out
```

**Pull request merged**
