### PR TITLE
Provide sib memory for AVR8X parts

### PR DESCRIPTION
**Pull request by stefanrueger**
A proposal to address Issue #1479

### CODE REVIEW

**Comment by MCUdude** [comment]
Works great with the serialupdi programmer! Would you mind having a look at the jtag3 implementation as well? Here you'll have to change the size of `AVR_SIBLEN` to 32.

```
$ avrdude -cserialupdi -pavr128da32 -Usib:r:-:r -T 'read sib'
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9709 (probably avr128da32)

avrdude: processing -U sib:r:-:r
avrdude: reading sib memory ...
avrdude: writing output file <stdout>

    AVR P:2D:1-3M2 (A6.KV001.0)avrdude: processing -T read sib
Reading | ################################################## | 100% 0.00 s 
0000  20 20 20 20 41 56 52 20  50 3a 32 44 3a 31 2d 33  |    AVR P:2D:1-3|
0010  4d 32 20 28 41 36 2e 4b  56 30 30 31 2e 30 29 00  |M2 (A6.KV001.0).|

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
>  jtag3 implementation

I don't get a sense of what's happening here. This may need to be done by someone who knows how to get jtag3 to return 32 bytes SIB from the device.

> Why `Return()`?

Density and clarity. My screen is wider than high. I prefer to see much of the code on screen, so my programming style compresses lines. The Return macro saves two lines on each use, the closing `\n` in the message and  a pair of braces.

**Comment by stefanrueger** [comment]
... having said this, it's OK if someone takes the draft and turns into a fully-fledged PR in different style. I'd like to encourage sanity checks, though, eg, the address against the memory size, as these functions might be called in the context of a library.

**Comment by MCUdude** [comment]
I've created a PR that adds JTAG SIB read support: [github.com/stefanrueger/avrdude/pull/3](https://github.com/stefanrueger/avrdude/pull/3)

**Comment by stefanrueger** [comment]
@MCUdude Now your contribution is included and this PR should be ready for tests/critical review

**Comment by stefanrueger** [comment]
BTW, planning to merge all 5 current PR on Friday European evening.

**Comment by MCUdude** [comment]
> BTW, planning to merge all 5 current PRs on Friday European evening.

If you merge all except for #1474, I can fix the merge conflict that's likely to happen. And while I'm at it, I'd like to replace `strcmp` with str_eq in a few places if that's OK. I've made quite a few changes to the jtag3 source code in the last year, but I've yet to do anything about the stick checking.

**Comment by stefanrueger** [comment]
@MCUdude You were right about the merge conflicts. Thanks for dealing with them.

I did another sanity cross check of the `io` sizes against the .atdf files:

| `io` start | `io` size | No of parts | Parts |
| --: | :-- | --: | :-- |
| 0x00 | 0x1000 | 45 | ATxmega128A1 ATxmega128A1U ATxmega128A3 ATxmega128A3U ATxmega128A4U ATxmega128B1 ATxmega128B3 ATxmega128C3 ATxmega128D3 ATxmega128D4 ATxmega16A4 ATxmega16A4U ATxmega16C4 ATxmega16D4 ATxmega16E5 ATxmega192A3 ATxmega192A3U ATxmega192C3 ATxmega192D3 ATxmega256A3 ATxmega256A3B ATxmega256A3BU ATxmega256A3U ATxmega256C3 ATxmega256D3 ATxmega32A4 ATxmega32A4U ATxmega32C3 ATxmega32C4 ATxmega32D3 ATxmega32D4 ATxmega32E5 ATxmega384C3 ATxmega384D3 ATxmega64A1 ATxmega64A1U ATxmega64A3 ATxmega64A3U ATxmega64A4U ATxmega64B1 ATxmega64B3 ATxmega64C3 ATxmega64D3 ATxmega64D4 ATxmega8E5 |
| 0x00 | 0x103f(!) | 43 | AVR128DA28 AVR128DA32 AVR128DA48 AVR128DA64 AVR128DB28 AVR128DB32 AVR128DB48 AVR128DB64 AVR16DD14 AVR16DD20 AVR16DD28 AVR16DD32 AVR16EA28 AVR16EA32 AVR16EA48 AVR32DA28 AVR32DA32 AVR32DA48 AVR32DB28 AVR32DB32 AVR32DB48 AVR32DD14 AVR32DD20 AVR32DD28 AVR32DD32 AVR32EA28 AVR32EA32 AVR32EA48 AVR64DA28 AVR64DA32 AVR64DA48 AVR64DA64 AVR64DB28 AVR64DB32 AVR64DB48 AVR64DB64 AVR64DD14 AVR64DD20 AVR64DD28 AVR64DD32 AVR64EA28 AVR64EA32 AVR64EA48 |
| 0x00 | 0x1100 | 46 | ATmega1608 ATmega1609 ATmega3208 ATmega3209 ATmega4808 ATmega4809 ATmega808 ATmega809 ATtiny1604 ATtiny1606 ATtiny1607 ATtiny1614 ATtiny1616 ATtiny1617 ATtiny1624 ATtiny1626 ATtiny1627 ATtiny202 ATtiny204 ATtiny212 ATtiny214 ATtiny3216 ATtiny3217 ATtiny3224 ATtiny3226 ATtiny3227 ATtiny402 ATtiny404 ATtiny406 ATtiny412 ATtiny414 ATtiny416 ATtiny416auto ATtiny417 ATtiny424 ATtiny426 ATtiny427 ATtiny804 ATtiny806 ATtiny807 ATtiny814 ATtiny816 ATtiny817 ATtiny824 ATtiny826 ATtiny827 |
| 0x00 | 0x0040 | 11 | ATtiny10 ATtiny102 ATtiny104 ATtiny11 ATtiny12 ATtiny15 ATtiny20 ATtiny4 ATtiny40 ATtiny5 ATtiny9 |
| 0x20 | 0x0040 | 31 | ATmega16 ATmega16A ATmega32 ATmega32A ATmega8 ATmega8515 ATmega8535 ATmega8A ATtiny13 ATtiny13A ATtiny2313 ATtiny2313A ATtiny24 ATtiny24A ATtiny25 ATtiny26 ATtiny261 ATtiny261A ATtiny28 ATtiny4313 ATtiny43U ATtiny44 ATtiny44A ATtiny45 ATtiny461 ATtiny461A ATtiny84 ATtiny84A ATtiny85 ATtiny861 ATtiny861A |
| 0x20 | 0x00e0 | 127 | AT90CAN128 AT90CAN32 AT90CAN64 AT90PWM1 AT90PWM161 AT90PWM216 AT90PWM2B AT90PWM3 AT90PWM316 AT90PWM3B AT90PWM81 AT90USB1286 AT90USB1287 AT90USB162 AT90USB646 AT90USB647 AT90USB82 ATA5272 ATA5505 ATA5790 ATA5790N ATA5791 ATA5795 ATA6285 ATA6286 ATA6612C ATA6613C ATA6614Q ATA6616C ATA6617C ATA664251 ATmega128 ATmega1284 ATmega1284P ATmega128A ATmega162 ATmega164A ATmega164P ATmega164PA ATmega165A ATmega165P ATmega165PA ATmega168 ATmega168A ATmega168P ATmega168PA ATmega168PB ATmega169A ATmega169P ATmega169PA ATmega16HVA ATmega16HVB ATmega16HVBrevB ATmega16M1 ATmega16U2 ATmega16U4 ATmega324A ATmega324P ATmega324PA ATmega324PB ATmega325 ATmega3250 ATmega3250A ATmega3250P ATmega3250PA ATmega325A ATmega325P ATmega325PA ATmega328 ATmega328P ATmega328PB ATmega329 ATmega3290 ATmega3290A ATmega3290P ATmega3290PA ATmega329A ATmega329P ATmega329PA ATmega32C1 ATmega32HVB ATmega32HVBrevB ATmega32M1 ATmega32U2 ATmega32U4 ATmega406 ATmega48 ATmega48A ATmega48P ATmega48PA ATmega48PB ATmega64 ATmega644 ATmega644A ATmega644P ATmega644PA ATmega645 ATmega6450 ATmega6450A ATmega6450P ATmega645A ATmega645P ATmega649 ATmega6490 ATmega6490A ATmega6490P ATmega649A ATmega649P ATmega64A ATmega64C1 ATmega64HVE2 ATmega64M1 ATmega88 ATmega88A ATmega88P ATmega88PA ATmega88PB ATmega8HVA ATmega8U2 ATtiny1634 ATtiny167 ATtiny441 ATtiny48 ATtiny828 ATtiny841 ATtiny87 ATtiny88 |
| 0x20 | 0x01e0 | 26 | ATA5700M322 ATA5702M322 ATA5781 ATA5782 ATA5783 ATA5787 ATA5831 ATA5832 ATA5833 ATA5835 ATA8210 ATA8215 ATA8510 ATA8515 ATmega1280 ATmega1281 ATmega1284RFR2 ATmega128RFA1 ATmega128RFR2 ATmega2560 ATmega2561 ATmega2564RFR2 ATmega256RFR2 ATmega640 ATmega644RFR2 ATmega64RFR2 |

Ignoring the classic parts for now (I will deal with them in an automated way for completeness later) there are still differences between the .atdf files and this PR *but* I think this PR is right. The 0x103f size looks wrong (probably caused by mistaking the last address for the size of a memory).

**Pull request merged**
