### PR TITLE
Add target_power_ctrl

### PR DESCRIPTION
**Pull request by stefanrueger**
Helps towards Issue #1235 by implementing a `target_power_ctrl` field in the programmer structure, see [comment here](https://github.com/avrdudes/avrdude/issues/1235#issuecomment-1365116615)

### CODE REVIEW

**Comment by mcuee** [comment]
I think this should be safe to merge.

**Comment by mcuee** [comment]
@stefanrueger 
Please merge git main to triger the new github action. Thanks.

**Comment by dl8dtl** [comment]
It just occurs me: back from the "old days" with parallel-port adapters, there's already the `-E exitspec` option that handles (among others) the target power after AVRDUDE terminates.
Wouldn't it make sense to re-use that option here?

**Comment by stefanrueger** [comment]
Closing PR as no longer needed

**Pull request closed without merging**
