### PR TITLE
To adopt PR #1264 approach of using Readline replacement for MinGW build (WIP, DNM)

### PR DESCRIPTION
**Pull request by mcuee**
PR https://github.com/avrdudes/avrdude/pull/1264 has been merged and it performs much better than using GNU Readline under Windows. It is good to adopt the same approach for MinGW.

This PR will fix Issue #1271.

This PR was initially developed by Xiaofan Chen based on PR #1264 but it does not work.
@Youw (Ihor Dutchak) helps to sort out the remaining issues.

### CODE REVIEW

**Comment by mcuee** [comment]
This PR needs review and testing. Please do not merge yet.

**Comment by mcuee** [comment]
One potential side effect of using `readline.cpp` is that this may bring more dependancies to MinGW build. It is not a real problem for MSVC build but it may be not so desired with MinGW.

**Comment by Youw** [comment]
> may bring

I guarantee it will as it uses staff from C++ Standard Library (notably `thread` and `mutex`).
One potential way of fixing it is to use `-static-libstdc++` linker flag. Since none of C++ standard classes are using in any public API, it is safe to do so.

**Comment by Youw** [comment]
> One potential side effect of using tje C++ readline.cpp is that this may bring more dependancies (GCC C++ related run time files) to MinGW build. It is not a real problem for MSVC build but it may be not so desired with MinGW.

> Just wondering how difficult it is to rewrite readline.cpp to readline.c. I am for sure not up to the task but I think maybe you can sort it out fast.

More analysys:
Wih `readline.cpp` we get 3 new dependencies:
- `libgcc_s_seh-1.dll` - C++ exceptions handling library;
- `libwinpthread-1.dll` - pthread implementation;
- `libstdc++-6.dll` - libstdc++;

With `-static-libstdc++` we only get rid of `libstdc++-6.dll`. To get rid of `libgcc_s_seh-1.dll` we would need to disable C++ exceptions (just another compiler/linker flag.
But even if we rewrite to from C++ to C - I don't believe `libwinpthread-1.dll` would go away, as we would have to use some kind threading library (probably `pthread` directly) anyway.

So instead I've tried `-static` linker flag and it seem to be working even with C++ implementation.
But I'm not sure what other side-effect it may have (other than making it 5.9MB in size instead of 3.6MB w/o `-static`).

**Comment by Youw** [comment]
And I can no longer push to your branch :)

This is the patch:
```cpp
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index db1c85d..ef07127 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -319,6 +319,10 @@ add_executable(avrdude

 target_link_libraries(avrdude PUBLIC libavrdude)

+if(MINGW)
+    target_link_options(avrdude PRIVATE -static)
+endif()
+
 # =====================================
 # Install
 # =====================================
```

**Comment by mcuee** [comment]
> And I can no longer push to your branch :)

Strange, you should be able to do that. I just checked and you are still listed as collaborator.

**Comment by Youw** [comment]
Ah, right, I used a wrong key.

**Comment by mcuee** [comment]
> So instead I've tried -static linker flag and it seem to be working even with C++ implementation.
> But I'm not sure what other side-effect it may have (other than making it 5.9MB in size instead of 3.6MB w/o -static).

Static build is okay for MinGW build. 

For avrdude project, the default for MSVC/MinGW build is static build. Then the default for Linux/macOS/FreeBSD is dynamic build. But people actually want static build for Linux/macOS as well.

**Comment by mcuee** [comment]
Now it is good in terms of dependancies.

```
MINGW64 /c/work/avr/avrdude_test/avrdude_bin/github_bin/pr1553/avrdude-mingw-x86_64
$ ldd ./avrdude.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff8f8590000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff8f62f0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff8f5ec0000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7ff8f68e0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff8f69b0000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7ff8f7f60000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7ff8f8430000)
        HID.DLL => /c/WINDOWS/SYSTEM32/HID.DLL (0x7ff8f4120000)
        SETUPAPI.dll => /c/WINDOWS/System32/SETUPAPI.dll (0x7ff8f77f0000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7ff8f6850000)
        cfgmgr32.DLL => /c/WINDOWS/SYSTEM32/cfgmgr32.DLL (0x7ff8f5580000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff8f5da0000)
```

**Comment by mcuee** [comment]
This PR is not working yet. I encountered the previous issue that I need extra return to excute the command.

```
PS>.\avrdude_pr1553v1 -C .\avrdude_pr1553v1.conf -c urclock -P ch340 -p m168p -qqt
avrdude> dump signature (need two returns here)
0000  1e 94 0b                                          |..              |
avrdude>
avrdude>
avrdude> quit (need two returns here)
PS>

```

**Comment by mcuee** [comment]
The good thing is that it does not get time out so easily compared to git main MinGW build, which is a known issue.

Example from git main MSYS2 mingw64 build.
```
PS>.\avrdude_git -c urclock -P ch340 -p m168p -qqt
avrdude> dump signature
0000  1e 94 0b                                          |..              |
avrdude> dump calibration
avrdude_git error: bootloader cannot read from calibration
avrdude_git error: (dump) error reading calibration address 0x00000 of part ATmega168P
                   read operation not supported on memory calibration
avrdude> write signature 0 0x11
avrdude_git error: bootloader does not implement bytewise write to signature
avrdude_git error: (write) error writing 0x11 at 0x00000, rc=-1
                    write operation not supported on memory signature
avrdude> quit
avrdude_git warning: programmer is not responding
```

**Comment by mcuee** [comment]
> This PR is not working yet. I encountered the previous issue that I need extra return to excute the command.

Previous issue reported by @MCUdude under macOS when using libedit.
* https://github.com/avrdudes/avrdude/issues/1173

Similar issues when I was testing PR #1132.
* #1132 

@dl8dtl sorted out the issue with libedit with a clever PR. I need to see if it helps in this case or not.
* #1207

**Comment by mcuee** [comment]
@Youw 
FYI only. 

In case you want to see the issue under Windows, you do not need a real setup, just use the `-c dryrun` programmer emulator.
```
avrdude -c dryrun -p m328p -qqt
```

**Comment by mcuee** [comment]
The following work-around does not work (similar to PR #1207).
* #1207 

```
$ git diff
diff --git a/src/mingw/readline.cpp b/src/mingw/readline.cpp
index 4fed1b1e..35f70b6c 100644
--- a/src/mingw/readline.cpp
+++ b/src/mingw/readline.cpp
@@ -13,7 +13,7 @@
 #include "readline/readline.h"
 #include "readline/history.h"

-int rl_readline_version = 0x0502;
+int rl_readline_version = 0x0402;

 static rl_vcpfunc_t* rl_handler;
 static std::unique_ptr<std::thread> rl_thread;
```

**Comment by mcuee** [comment]
Other problems: wrong first line

```
PS>echo 'read eeprom' | .\avrdude_pr1553 -C .\avrdude_pr1553.conf -c urclock -p m328p -P ch340 -qq -t
avrdude> 0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
0030  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
0040  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
0050  61 7a 79 20 64 6f 67 0a  54 68 65 20 71 75 69 63  |azy dog The quic|
0060  6b 20 62 72 6f 77 6e 20  66 6f 78 20 6a 75 6d 70  |k brown fox jump|
0070  73 20 6f 76 65 72 20 74  68 65 20 6c 61 7a 79 20  |s over the lazy |
0080  64 6f 67 0a 54 68 65 20  71 75 69 63 6b 20 62 72  |dog The quick br|
0090  6f 77 6e 20 66 6f 78 20  6a 75 6d 70 73 20 6f 76  |own fox jumps ov|
00a0  65 72 20 74 68 65 20 6c  61 7a 79 20 64 6f 67 0a  |er the lazy dog |
00b0  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
00c0  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
00d0  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
00e0  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
00f0  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
avrdude>

PS>echo 'read eeprom' | .\avrdude_pr1553_mod -C .\avrdude_pr1553.conf -c urclock -p m328p -P ch340 -qq -t
avrdude> 0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
0030  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
0040  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
0050  61 7a 79 20 64 6f 67 0a  54 68 65 20 71 75 69 63  |azy dog The quic|
0060  6b 20 62 72 6f 77 6e 20  66 6f 78 20 6a 75 6d 70  |k brown fox jump|
0070  73 20 6f 76 65 72 20 74  68 65 20 6c 61 7a 79 20  |s over the lazy |
0080  64 6f 67 0a 54 68 65 20  71 75 69 63 6b 20 62 72  |dog The quick br|
0090  6f 77 6e 20 66 6f 78 20  6a 75 6d 70 73 20 6f 76  |own fox jumps ov|
00a0  65 72 20 74 68 65 20 6c  61 7a 79 20 64 6f 67 0a  |er the lazy dog |
00b0  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
00c0  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
00d0  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
00e0  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
00f0  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
avrdude>
PS>echo 'read eeprom' | .\avrdude_git -c urclock -p m328p -P ch340 -qq -t
avrdude> read eeprom
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
0030  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
0040  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
0050  61 7a 79 20 64 6f 67 0a  54 68 65 20 71 75 69 63  |azy dog The quic|
0060  6b 20 62 72 6f 77 6e 20  66 6f 78 20 6a 75 6d 70  |k brown fox jump|
0070  73 20 6f 76 65 72 20 74  68 65 20 6c 61 7a 79 20  |s over the lazy |
0080  64 6f 67 0a 54 68 65 20  71 75 69 63 6b 20 62 72  |dog The quick br|
0090  6f 77 6e 20 66 6f 78 20  6a 75 6d 70 73 20 6f 76  |own fox jumps ov|
00a0  65 72 20 74 68 65 20 6c  61 7a 79 20 64 6f 67 0a  |er the lazy dog |
00b0  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
00c0  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
00d0  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
00e0  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
00f0  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
avrdude>
```

**Comment by mcuee** [comment]
Looks like I can not sorted out the issue without help from others. I will still keep this PR open for a while, at least until when @stefanrueger is back.

And there are good changes to CMake by @Youw. Even if we close this PR, I may raise another to adopt CMake improvements from this PR into git main.

**Comment by mcuee** [comment]
The following changes reverted the addition of embedded MinGW Readline and use GNU Readline (if GNU Readline is installed). And it works properly (except existing issues that it may time out in terminal mode sometimes).

**So the issue is really related to the embedded readline implementation, which works under MSVC but not MinGW. Strange.**

```
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e69844b1..6bae9f88 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -221,8 +221,8 @@ endif()

 if(MSVC)
     set(HAVE_LIBREADLINE "Embedded MSVC")
-elseif(MINGW)
-    set(HAVE_LIBREADLINE "Embedded MINGW")
+#elseif(MINGW)
+#    set(HAVE_LIBREADLINE "Embedded MINGW")
 else()
     find_library(HAVE_LIBREADLINE NAMES ${PREFERRED_LIBREADLINE})
     if(HAVE_LIBREADLINE)
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ef071274..70e5e262 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -80,12 +80,12 @@ if(MSVC)
         )
     list(APPEND EXTRA_WINDOWS_INCLUDES "msvc")
 elseif(MINGW)
-    enable_language(CXX)
+#    enable_language(CXX)

     set(LIB_MATH m)
     add_compile_options(-Wall -Wextra -Wno-unused-parameter)
-    list(APPEND EXTRA_WINDOWS_SOURCES "mingw/readline.cpp")
-    list(APPEND EXTRA_WINDOWS_INCLUDES "mingw")
+#    list(APPEND EXTRA_WINDOWS_SOURCES "mingw/readline.cpp")
+#    list(APPEND EXTRA_WINDOWS_INCLUDES "mingw")
 else()
     set(LIB_MATH m)
     add_compile_options(-Wall -Wextra -Wno-unused-parameter)

PS>echo 'read eeprom' | .\avrdude_pr1553_readline -C .\avrdude_pr1553.conf -c urclock -p m328p -P ch340 -qq -t
avrdude> read eeprom
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
0030  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
0040  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
0050  61 7a 79 20 64 6f 67 0a  54 68 65 20 71 75 69 63  |azy dog The quic|
0060  6b 20 62 72 6f 77 6e 20  66 6f 78 20 6a 75 6d 70  |k brown fox jump|
0070  73 20 6f 76 65 72 20 74  68 65 20 6c 61 7a 79 20  |s over the lazy |
0080  64 6f 67 0a 54 68 65 20  71 75 69 63 6b 20 62 72  |dog The quick br|
0090  6f 77 6e 20 66 6f 78 20  6a 75 6d 70 73 20 6f 76  |own fox jumps ov|
00a0  65 72 20 74 68 65 20 6c  61 7a 79 20 64 6f 67 0a  |er the lazy dog |
00b0  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
00c0  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
00d0  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
00e0  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
00f0  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
avrdude>

PS>.\avrdude_pr1553_readline -C .\avrdude_pr1553.conf -c urclock -p m328p -P ch340 -qq -t
avrdude> read eeprom
0000  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
0010  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
0020  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
0030  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
0040  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
0050  61 7a 79 20 64 6f 67 0a  54 68 65 20 71 75 69 63  |azy dog The quic|
0060  6b 20 62 72 6f 77 6e 20  66 6f 78 20 6a 75 6d 70  |k brown fox jump|
0070  73 20 6f 76 65 72 20 74  68 65 20 6c 61 7a 79 20  |s over the lazy |
0080  64 6f 67 0a 54 68 65 20  71 75 69 63 6b 20 62 72  |dog The quick br|
0090  6f 77 6e 20 66 6f 78 20  6a 75 6d 70 73 20 6f 76  |own fox jumps ov|
00a0  65 72 20 74 68 65 20 6c  61 7a 79 20 64 6f 67 0a  |er the lazy dog |
00b0  54 68 65 20 71 75 69 63  6b 20 62 72 6f 77 6e 20  |The quick brown |
00c0  66 6f 78 20 6a 75 6d 70  73 20 6f 76 65 72 20 74  |fox jumps over t|
00d0  68 65 20 6c 61 7a 79 20  64 6f 67 0a 54 68 65 20  |he lazy dog The |
00e0  71 75 69 63 6b 20 62 72  6f 77 6e 20 66 6f 78 20  |quick brown fox |
00f0  6a 75 6d 70 73 20 6f 76  65 72 20 74 68 65 20 6c  |jumps over the l|
avrdude> quit
```

**Comment by Youw** [comment]
> So the issue is really related to the embedded readline implementation, which works under MSVC but not MinGW. Strange.

Could be a difference between GNU/MSVC standard on line endings (`\n` vs `\r\n` on Windows) and different terminals used.

**Comment by mcuee** [comment]
> > So the issue is really related to the embedded readline implementation, which works under MSVC but not MinGW. Strange.
> 
> Could be a difference between GNU/MSVC standard on line endings (`\n` vs `\r\n` on Windows) 

Ineed I also suspect this reason. By the way, I have also tried MSYS2 clang64 and it has the same problem as MinGW.

> and different terminals used.

I have tried Windows Command prompt, WIndows Terminal and MSYS2 terminal, the results are the same.

**Comment by Youw** [comment]
> I have tried Windows Command prompt, WIndows Terminal and MSYS2 terminal, the results are the same.

I find that a good thing - less workarounds in the code would be required.

**Comment by mcuee** [comment]
> I have lost track of this PR. Should it be merged? 

This PR is not working and it should not be merged.

> Afraid I cannot help with Windows issues.

Fair enough.

**Comment by mcuee** [comment]
> > I have tried Windows Command prompt, WIndows Terminal and MSYS2 terminal, the results are the same.
> 
> I find that a good thing - less workarounds in the code would be required.

As I can not fix the issue myself, I will close this PR for now. 

Thanks a lot for the help. I will still keep the following branch open.
https://github.com/mcuee/avrdude/tree/issue1271

**Pull request closed without merging**
